import Mathlib

/-!
# Effective Global Bounds and Critical Families for Lonely Runners

Global height, off-critical speed, and denominator bounds under explicit lower-speed
Lonely Runner hypotheses; sharp 3q bounds on the three explicit six-speed families;
and exact optimization. The unrestricted sharp six-speed Question 6.6 is still open
in this development. The geometric estimates are proved conclusions, not hypotheses.
-/

namespace LonelyRunner

/-- Distance to the nearest integer, using the standard unit-circle norm. -/
noncomputable def intDist (x : ℝ) : ℝ := ‖(x : AddCircle (1 : ℝ))‖

/-- Maximum simultaneous distance over all real times; attainment is proved below. -/
noncomputable def loneliness {n : ℕ} [NeZero n] (v : Fin n → ℤ) : ℝ :=
  sSup (Set.range fun t : ℝ => Finset.univ.inf' Finset.univ_nonempty
    (fun i => intDist (t * v i)))

/-- Loneliness on the entire real plane generated by two integer columns,
viewed modulo the integer lattice. No chosen one-dimensional direction is built in. -/
noncomputable def planeLoneliness {n : ℕ} [NeZero n] (v z : Fin n → ℤ) : ℝ :=
  sSup (Set.range fun p : ℝ × ℝ => Finset.univ.inf' Finset.univ_nonempty
    (fun i => intDist (p.1*v i+p.2*z i)))

noncomputable def speedNorm {n : ℕ} (v : Fin n → ℤ) : ℝ :=
  Real.sqrt (∑ i, (v i : ℝ)^2)

/-- The area of the displayed integer parallelogram. This definition does not
assert that the two columns generate the saturated integer lattice of their plane. -/
noncomputable def planeHeight {n : ℕ} (v z : Fin n → ℤ) : ℝ :=
  Real.sqrt ((∑ i, (v i : ℝ)^2)*(∑ i, (z i : ℝ)^2)-
    (∑ i, (v i : ℝ)*(z i : ℝ))^2)

/-- Cordella Table 2, tuple 1. -/
def sporadic1 : Fin 6 → ℤ := ![1, 2, 5, 6, 7, 8]

/-- Cordella Table 2, tuple 2. -/
def sporadic2 : Fin 6 → ℤ := ![2, 5, 6, 8, 10, 11]

/-- Cordella Table 2, tuple 3. -/
def sporadic3 : Fin 6 → ℤ := ![1, 4, 5, 6, 7, 22]

/-- Cordella Table 2, tuple 4. -/
def sporadic4 : Fin 6 → ℤ := ![1, 2, 3, 5, 8, 18]

/-- Cordella Table 2, tuple 5. -/
def sporadic5 : Fin 6 → ℤ := ![2, 3, 5, 6, 8, 11]

/-- Cordella Table 2, tuple 6. -/
def sporadic6 : Fin 6 → ℤ := ![2, 5, 6, 7, 8, 11]

/-- Cordella Table 2, tuple 7. -/
def sporadic7 : Fin 6 → ℤ := ![1, 3, 4, 5, 18, 46]

/-- Cordella Table 2, tuple 8. -/
def sporadic8 : Fin 6 → ℤ := ![1, 3, 4, 5, 7, 24]

/-- Cordella Table 2, tuple 9. -/
def sporadic9 : Fin 6 → ℤ := ![1, 4, 5, 6, 7, 33]

/-- Primitive boundary speeds with `d = n^(e+1)`. -/
def boundarySpeeds (n e : ℕ) (i : Fin n) : ℤ :=
  if i.val = 0 then 1 else (i.val : ℤ) * (n : ℤ) ^ (e + 1)

/-- An explicit rational maximizing time for the boundary family. -/
def boundaryTime (n e : ℕ) : ℚ :=
  ((n ^ (e + 1) + 1 : ℕ) : ℚ) / ((n * n ^ (e + 1) : ℕ) : ℚ)

/-- Simultaneously multiplying all nonzero speeds changes the time parameter, not loneliness. -/
theorem loneliness_scale {n : ℕ} [NeZero n] (v : Fin n → ℤ) (c : ℤ) (hc : c ≠ 0) :
    loneliness (fun i => c * v i) = loneliness v := by sorry

/-- Every tuple's supremum is attained at an actual time in the unit interval. -/
theorem exists_maximizing_time {n : ℕ} [NeZero n] (v : Fin n → ℤ) :
    ∃ t ∈ Set.Icc (0 : ℝ) 1, ∀ i, loneliness v ≤ intDist (t * v i) := by sorry

/-- Separation of a rational number above `1/n` from that threshold. -/
theorem rational_gap (a b n : ℕ) (hb : 0 < b) (hn : 0 < n)
    (h : (1 : ℝ) / n < (a : ℝ) / b) :
    1 / ((n : ℝ) * b) ≤ (a : ℝ) / b - 1 / n := by sorry

/-- Exact loneliness of `(1, 2, 5, 6, 7, 8)` over all real times. -/
theorem sporadic1_value : loneliness sporadic1 = ((2 / 13) : ℝ) := by sorry

/-- Exact loneliness of `(2, 5, 6, 8, 10, 11)` over all real times. -/
theorem sporadic2_value : loneliness sporadic2 = ((2 / 13) : ℝ) := by sorry

/-- Exact loneliness of `(1, 4, 5, 6, 7, 22)` over all real times. -/
theorem sporadic3_value : loneliness sporadic3 = ((2 / 13) : ℝ) := by sorry

/-- Exact loneliness of `(1, 2, 3, 5, 8, 18)` over all real times. -/
theorem sporadic4_value : loneliness sporadic4 = ((3 / 19) : ℝ) := by sorry

/-- Exact loneliness of `(2, 3, 5, 6, 8, 11)` over all real times. -/
theorem sporadic5_value : loneliness sporadic5 = ((3 / 19) : ℝ) := by sorry

/-- Exact loneliness of `(2, 5, 6, 7, 8, 11)` over all real times. -/
theorem sporadic6_value : loneliness sporadic6 = ((3 / 19) : ℝ) := by sorry

/-- Exact loneliness of `(1, 3, 4, 5, 18, 46)` over all real times. -/
theorem sporadic7_value : loneliness sporadic7 = ((4 / 25) : ℝ) := by sorry

/-- Exact loneliness of `(1, 3, 4, 5, 7, 24)` over all real times. -/
theorem sporadic8_value : loneliness sporadic8 = ((5 / 31) : ℝ) := by sorry

/-- Exact loneliness of `(1, 4, 5, 6, 7, 33)` over all real times. -/
theorem sporadic9_value : loneliness sporadic9 = ((6 / 37) : ℝ) := by sorry

/-- The reduced denominator 25 need not be a denominator of a maximizing time. -/
theorem sporadic7_grid25_miss : ∀ k : Fin 25, ∃ i : Fin 6,
    intDist ((k.val / 25 : ℝ) * sporadic7 i) < 4 / 25 := by sorry

/-- Common dilation shows why primitive speeds are required in Question 6.6. -/
theorem nonprimitive_counterexample :
    loneliness ![2, 6, 8, 10, 36, 92] = (4 / 25 : ℝ) ∧ (3 * 25 : ℤ) < 92 := by sorry

/-- Every maximizing time for positive integer speeds has denominator `v i + v j`
for some indices, which may coincide. The same denominator represents the loneliness.
This strengthens the candidate set in Cordella's Lemma 2.2 by using sums only. -/
theorem maximizing_time_pair_sum {n : ℕ} [NeZero n] (v : Fin n → ℤ)
    (hpos : ∀ i, 0 < v i) (t : ℝ)
    (hmax : ∀ i, loneliness v ≤ intDist (t * v i)) :
    ∃ i j : Fin n, ∃ m a : ℤ,
      t = (m : ℝ) / (v i + v j) ∧
      loneliness v = (a : ℝ) / (v i + v j) := by sorry

/-- The continuous optimization reduces to finitely many sum-denominator times. -/
theorem exists_pair_sum_maximizer {n : ℕ} [NeZero n] (v : Fin n → ℤ)
    (hpos : ∀ i, 0 < v i) :
    ∃ i j : Fin n, ∃ m a : ℤ,
      0 ≤ m ∧ m ≤ v i + v j ∧
      loneliness v = (a : ℝ) / (v i + v j) ∧
      ∀ r, loneliness v ≤ intDist (((m : ℝ) / (v i + v j)) * v r) := by sorry

/-- An exact finite-grid criterion for an upper bound over all real times. -/
theorem loneliness_le_iff_pair_sum_grid {n : ℕ} [NeZero n] (v : Fin n → ℤ)
    (hpos : ∀ i, 0 < v i) (L : ℝ) :
    loneliness v ≤ L ↔ ∀ i j : Fin n, ∀ m : ℤ, 0 ≤ m → m ≤ v i + v j →
      ∃ r, intDist (((m : ℝ) / (v i + v j)) * v r) ≤ L := by sorry

/-- The reduced denominator of the loneliness divides a sum of two speeds. -/
theorem reduced_denominator_dvd_pair_sum {n : ℕ} [NeZero n] (v : Fin n → ℤ)
    (hpos : ∀ i, 0 < v i) (a q : ℕ) (hq : 0 < q) (hcop : a.Coprime q)
    (hvalue : loneliness v = (a : ℝ) / q) :
    ∃ i j : Fin n, (q : ℤ) ∣ v i + v j := by sorry

/-- A denominator bound valid for every positive integer tuple, with no near-tightness assumption. -/
theorem reduced_denominator_le_twice_max {n : ℕ} [NeZero n] (v : Fin n → ℤ)
    (hpos : ∀ i, 0 < v i) (a q M : ℕ) (hq : 0 < q) (hcop : a.Coprime q)
    (hvalue : loneliness v = (a : ℝ) / q) (hM : ∀ i, v i ≤ M) : q ≤ 2 * M := by sorry

/-- A maximizing time has an increasing and a decreasing active runner.
The floor values locate their opposing sides of the same feasible cell. -/
theorem maximizing_time_active_pair {n : ℕ} [NeZero n] (v : Fin n → ℤ)
    (hpos : ∀ i, 0 < v i) (t : ℝ)
    (hmax : ∀ i, loneliness v ≤ intDist (t * v i)) :
    ∃ i j : Fin n,
      t * v i = (⌊t * v i⌋ : ℝ) + loneliness v ∧
      t * v j = (⌊t * v j⌋ : ℝ) + 1 - loneliness v := by sorry

/-- The reduced denominator of a rational runner distance is determined exactly
by the reduced time denominator and the speed. -/
theorem active_runner_denominator (t L : ℚ) (v : ℤ)
    (h : intDist ((t : ℝ) * v) = (L : ℝ)) :
    L.den = t.den / Nat.gcd t.den v.natAbs := by sorry

/-- The value denominator divides an active-pair sum after removing that pair's gcd. -/
theorem reduced_denominator_dvd_normalized_pair_sum {n : ℕ} [NeZero n]
    (v : Fin n → ℤ) (hpos : ∀ i, 0 < v i) (a q : ℕ)
    (hq : 0 < q) (hcop : a.Coprime q) (hvalue : loneliness v = (a : ℝ) / q) :
    ∃ i j : Fin n, (q : ℤ) ∣ (v i + v j) / (Int.gcd (v i) (v j) : ℤ) := by sorry

/-- Every maximizing rational time has a reduced denominator controlled exactly
by the gcd of an opposing active pair. -/
theorem maximizing_time_denominators {n : ℕ} [NeZero n] (v : Fin n → ℤ)
    (hpos : ∀ i, 0 < v i) (t L : ℚ) (hL : loneliness v = (L : ℝ))
    (hmax : ∀ i, loneliness v ≤ intDist ((t : ℝ) * v i)) :
    ∃ i j : Fin n,
      (i = j → L = 1 / 2) ∧ L.den ∣ t.den ∧
      (t.den : ℤ) ∣ v i + v j ∧
      t.den / L.den = Nat.gcd t.den (Int.gcd (v i) (v j)) := by sorry

/-- Pairwise-coprime positive speeds force equality of the value and time
reduced denominators whenever the loneliness is below one half. -/
theorem coprime_speeds_maximizing_denominator {n : ℕ} [NeZero n]
    (v : Fin n → ℤ) (hpos : ∀ i, 0 < v i)
    (hcop : ∀ i j, i ≠ j → Int.gcd (v i) (v j) = 1)
    (t L : ℚ) (hL : loneliness v = (L : ℝ)) (hlt : L < 1 / 2)
    (hmax : ∀ i, loneliness v ≤ intDist ((t : ℝ) * v i)) : t.den = L.den := by sorry

/-- Distinct positive speeds improve the general denominator bound by one. -/
theorem reduced_denominator_le_twice_max_sub_one {n : ℕ} [NeZero n]
    (hn : 2 ≤ n) (v : Fin n → ℤ) (hpos : ∀ i, 0 < v i)
    (hinj : Function.Injective v) (a q M : ℕ) (hq : 0 < q) (hc : a.Coprime q)
    (hL : loneliness v = (a : ℝ) / q) (hM : ∀ i, v i ≤ M) : q ≤ 2 * M - 1 := by sorry

/-- Consecutive positive speeds attain the denominator bound `q = 2*max(v)-1`. -/
theorem consecutive_pair_loneliness (m : ℕ) (hm : 0 < m) :
    loneliness ![(m : ℤ), (m : ℤ) + 1] = (m : ℝ) / (2 * m + 1) := by sorry

/-- The exact value for consecutive speeds is in lowest terms. -/
theorem consecutive_pair_coprime (m : ℕ) : m.Coprime (2 * m + 1) := by sorry

/-- Every coordinate reaches distance at least `1/n` at the explicit boundary time. -/
theorem boundary_time_witness (n e : ℕ) [NeZero n] (hn : 3 ≤ n) :
    ∀ i, 1 / (n : ℝ) ≤ intDist ((boundaryTime n e : ℝ) * boundarySpeeds n e i) := by sorry

/-- The boundary family has exact loneliness `1/n` in every dimension at least three. -/
theorem boundary_loneliness (n e : ℕ) [NeZero n] (hn : 3 ≤ n) :
    loneliness (boundarySpeeds n e) = 1 / (n : ℝ) := by sorry

/-- Every member of the family has positive distinct speeds and gcd one. -/
theorem boundary_primitive (n e : ℕ) [NeZero n] (hn : 3 ≤ n) :
    (∀ i, 0 < boundarySpeeds n e i) ∧ Function.Injective (boundarySpeeds n e) ∧
    Finset.univ.gcd (fun i => (boundarySpeeds n e i).natAbs) = 1 := by sorry

/-- With the reduced loneliness denominator fixed at `n`, primitive boundary
families have unbounded largest speed. Strict near-tightness is therefore essential. -/
theorem primitive_boundary_unbounded (n C : ℕ) [NeZero n] (hn : 3 ≤ n) :
    ∃ e : ℕ, loneliness (boundarySpeeds n e) = 1 / (n : ℝ) ∧
      Finset.univ.gcd (fun i => (boundarySpeeds n e i).natAbs) = 1 ∧
      ∃ i, (C : ℤ) * n < boundarySpeeds n e i := by sorry

/-- The explicit maximizing time is already reduced, with denominator `n^(e+2)`. -/
theorem boundary_time_denominator (n e : ℕ) (hn : 3 ≤ n) :
    (boundaryTime n e).den = n ^ (e + 2) := by sorry

/-! Verified development toward the unrestricted Question 6.6 target.
The critical-family theorem retains explicit membership. No global classification
or global Question 6.6 theorem is asserted. -/

def torusSpeeds {n : ℕ} (c d : Fin n → ℤ) (A B : ℤ) : Fin n → ℤ :=
  fun i => c i * A + d i * B

def PrimitiveSpeeds {n : ℕ} (v : Fin n → ℤ) : Prop :=
  Finset.univ.gcd (fun i => (v i).natAbs) = 1

def fastCoreA : Fin 6 → ℤ := ![1, 2, 3, 4, 5, 0]

def fastCoreB : Fin 6 → ℤ := ![1, 3, 4, 5, 9, 0]

def fastDirection : Fin 6 → ℤ := ![0, 0, 0, 0, 0, 1]

def ucC : Fin 6 → ℤ := ![1, 0, 1, 2, 3, 3]

def ucD : Fin 6 → ℤ := ![0, 1, 1, 1, 1, 2]

def CriticalPresentation (c d : Fin 6 → ℤ) : Prop :=
  (c = fastCoreA ∧ d = fastDirection) ∨
  (c = fastCoreB ∧ d = fastDirection) ∨ (c = ucC ∧ d = ucD)

def ProperSpeeds {n : ℕ} (v : Fin n → ℤ) : Prop :=
  (∀ i, v i ≠ 0) ∧ ∀ i j, i ≠ j → v i ≠ v j ∧ v i ≠ -v j

def exampleTorusC : Fin 6 → ℤ := ![0, 0, 1, 1, 1, 2]

def exampleTorusD : Fin 6 → ℤ := ![1, 2, -2, -1, 1, 1]

def frequency {n : ℕ} (a v : Fin n → ℤ) : ℤ := ∑ i, a i * v i

noncomputable def cosinePolynomial {n : ℕ} (S : Finset (Fin n → ℤ))
    (c : (Fin n → ℤ) → ℝ) (x : Fin n → ℝ) : ℝ :=
  ∑ a ∈ S, c a * Real.cos (2 * Real.pi * ∑ i, (a i : ℝ) * x i)

theorem critical_families_question66 (v c d : Fin 6 → ℤ)
    (hc : CriticalPresentation c d) (A B : ℤ) (e : Equiv.Perm (Fin 6))
    (hprim : PrimitiveSpeeds v) (hnz : ∀ i, v i ≠ 0)
    (he : ∀ i, (v i).natAbs = (torusSpeeds c d A B (e i)).natAbs)
    (a q : ℕ) (hq : 0 < q) (hval : loneliness v = (a : ℝ)/q)
    (hnear : loneliness v < (1 : ℝ)/6) : ∀ i, |v i| < 3*(q : ℤ) := by sorry

theorem uc_question66 (A B : ℤ) (hprim : Int.gcd A B = 1)
    (hnz : ∀ i, torusSpeeds ucC ucD A B i ≠ 0)
    (a q : ℕ) (hq : 0 < q)
    (hval : loneliness (torusSpeeds ucC ucD A B) = (a : ℝ)/q)
    (hnear : loneliness (torusSpeeds ucC ucD A B) < (1 : ℝ)/6) :
    ∀ i, |torusSpeeds ucC ucD A B i| < 3*(q : ℤ) := by sorry

theorem fast_families_signed_question66 (c : Fin 6 → ℤ) (hc : c = fastCoreA ∨ c = fastCoreB)
    (A B : ℤ) (hnz : ∀ i, torusSpeeds c fastDirection A B i ≠ 0)
    (hprim : Int.gcd A B = 1) (a q : ℕ) (hq : 0 < q)
    (hval : loneliness (torusSpeeds c fastDirection A B) = (a : ℝ)/q)
    (hnear : loneliness (torusSpeeds c fastDirection A B) < (1 : ℝ)/6) :
    ∀ i, |torusSpeeds c fastDirection A B i| < 3*(q : ℤ) := by sorry

theorem good_triangle_parameter_bounds {n : ℕ} [NeZero n]
    (c d : Fin n → ℤ) (A B : ℤ) (hprim : Int.gcd A B = 1)
    (x y : Fin 3 → ℝ) (L : ℝ) (m : Fin n → ℤ)
    (hnear : loneliness (torusSpeeds c d A B) < L)
    (hlo : ∀ j i, (m i : ℝ) + L ≤ c i * x j + d i * y j)
    (hhi : ∀ j i, (c i : ℝ) * x j + d i * y j ≤ m i + 1 - L)
    (hD : (x 1-x 0)*(y 2-y 0)-(y 1-y 0)*(x 2-x 0) ≠ 0) :
    |(A : ℝ)| < (|x 1-x 0|+|x 2-x 0|) /
      |(x 1-x 0)*(y 2-y 0)-(y 1-y 0)*(x 2-x 0)| ∧
    |(B : ℝ)| < (|y 1-y 0|+|y 2-y 0|) /
      |(x 1-x 0)*(y 2-y 0)-(y 1-y 0)*(x 2-x 0)| := by sorry

theorem example_torus_all_directions (A B : ℤ)
    (hproper : ProperSpeeds (torusSpeeds exampleTorusC exampleTorusD A B)) :
    (1 : ℝ)/6 ≤ loneliness (torusSpeeds exampleTorusC exampleTorusD A B) := by sorry

theorem integral_cosinePolynomial {n : ℕ} (S : Finset (Fin n → ℤ))
    (c : (Fin n → ℤ) → ℝ) (v : Fin n → ℤ) :
    (∫ t in (0 : ℝ)..1, cosinePolynomial S c (fun i => t * v i)) =
      ∑ a ∈ S, if frequency a v = 0 then c a else 0 := by sorry

/-- The explicit support shape of the short Fourier obstruction. -/
def SmallFourierVector (a : Fin 6 → ℤ) : Prop :=
  ∃ j, |a j| ≤ 4 ∧ ∀ i, i ≠ j → |a i| ≤ 2

/-- Global necessary condition for near-tightness, with no speed cutoff or
assumed modular cover. This does not assert a complete relation-space classification. -/
theorem near_tight_short_relation (v : Fin 6 → ℤ) (hv : loneliness v ≤ (1:ℝ)/6) :
    ∃ a : Fin 6 → ℤ, a ≠ 0 ∧ SmallFourierVector a ∧ frequency a v=0 := by sorry

theorem near_tight_relation_norm36 (v : Fin 6 → ℤ) (hv : loneliness v ≤ (1:ℝ)/6) :
    ∃ a : Fin 6 → ℤ, a ≠ 0 ∧ (∑ i, a i^2) ≤ 36 ∧ frequency a v=0 := by sorry

/-- The full-plane maximum is attained on the unit parameter square. -/
theorem exists_plane_maximizer {n : ℕ} [NeZero n] (v z : Fin n → ℤ) :
    ∃ x ∈ Set.Icc (0:ℝ) 1, ∃ y ∈ Set.Icc (0:ℝ) 1,
      ∀ i, planeLoneliness v z ≤ intDist (x*v i+y*z i) := by sorry

/-- The projection-height density estimate used in the effective-bound proof.
The area and norm are defined from the integer columns; the estimate is not a hypothesis. -/
theorem planeLoneliness_le_add_height {n : ℕ} [NeZero n] (v z : Fin n → ℤ) (hv : v ≠ 0) :
    planeLoneliness v z ≤ loneliness v+planeHeight v z/(2*speedNorm v) := by sorry

/-- An effective denominator bound for the actual whole-plane optimum.
The universal constant three also covers both boundary levels. -/
theorem planeLoneliness_denominator_bound {n : ℕ} [NeZero n] (v z : Fin n → ℤ)
    (i j : Fin n) (hij : v i*z j-z i*v j ≠ 0) :
    ∃ q : ℚ, planeLoneliness v z=(q : ℝ) ∧ (q.den : ℝ) ≤ 3*planeHeight v z := by sorry

/-- A containing noncritical integer plane now gives an actual speed bound
from its displayed height alone. Its rational value, denominator bound and
density estimate are all proved in this development. -/
theorem speedNorm_bound_of_noncritical_plane {n : ℕ} [NeZero n] (v z : Fin n → ℤ)
    (i j : Fin n) (hij : v i*z j-z i*v j ≠ 0)
    (hnear : loneliness v < 1/(n : ℝ)) (hplane : 1/(n : ℝ) < planeLoneliness v z) :
    speedNorm v < (3*(n : ℝ)/2)*planeHeight v z^2 := by sorry

/-- All primitive near-tight directions in a fixed noncritical integer plane
have a uniform norm bound depending only on that plane's original basis.
There is no bound or search assumption on the integer parameters. -/
theorem primitive_directions_bound_of_noncritical_plane {n : ℕ} [NeZero n]
    (c d : Fin n → ℤ) (i j : Fin n) (hij : c i*d j-d i*c j ≠ 0)
    (hplane : 1/(n : ℝ) < planeLoneliness c d)
    (A B : ℤ) (hprim : Int.gcd A B=1)
    (hnear : loneliness (torusSpeeds c d A B) < 1/(n : ℝ)) :
    speedNorm (torusSpeeds c d A B) < (3*(n : ℝ)/2)*planeHeight c d^2 := by sorry

def LonelyRunnerConjecture (n : ℕ) : Prop :=
  ∀ v : Fin n → ℤ, (∀ i, v i ≠ 0) →
    ∃ t : ℝ, ∀ i, 1/((n : ℝ)+1) ≤ intDist (t*v i)

noncomputable def boxHeightConstant (n : ℕ) : ℝ :=
  (n:ℝ)^n*((n:ℝ)*((n:ℝ)-1))^(n-2)

def OffCritical {n : ℕ} [NeZero n] (v : Fin n → ℤ) : Prop :=
  ∀ z : Fin n → ℤ, (∃ i j, v i*z j-z i*v j ≠ 0) →
    planeLoneliness v z ≠ 1/(n:ℝ)

theorem planeLoneliness_lower_bound_of_lrc {n : ℕ} (hLRC : LonelyRunnerConjecture n)
    (c d : Fin (n+1) → ℤ) (hc : ∀ i, c i ≠ 0)
    (a b : Fin (n+1)) (hab : c a*d b-d a*c b ≠ 0) :
    1/((n : ℝ)+1) ≤ planeLoneliness c d := by sorry

theorem exists_planeHeight_lt_box_constant {m : ℕ}
    (hLRC : LonelyRunnerConjecture (m+1)) (v : Fin (m+3) → ℤ)
    (hv : ∀ i, 0 < v i) (hprim : PrimitiveSpeeds v)
    (hnear : loneliness v < 1/((m:ℝ)+3)) :
    ∃ z : Fin (m+3) → ℤ, (∃ i j, v i*z j-z i*v j ≠ 0) ∧
      planeHeight v z < boxHeightConstant (m+3) := by sorry

theorem offCritical_speedNorm_bound {m : ℕ}
    (hLRC₂ : LonelyRunnerConjecture (m+1)) (hLRC₁ : LonelyRunnerConjecture (m+2))
    (v : Fin (m+3) → ℤ) (hv : ∀ i, 0 < v i) (hprim : PrimitiveSpeeds v)
    (hnear : loneliness v < 1/((m:ℝ)+3)) (hoff : OffCritical v) :
    speedNorm v < (3*((m:ℝ)+3)/2)*boxHeightConstant (m+3)^2 := by sorry

theorem finite_offCritical_near_tight {m : ℕ}
    (hLRC₂ : LonelyRunnerConjecture (m+1)) (hLRC₁ : LonelyRunnerConjecture (m+2)) :
    Set.Finite {v : Fin (m+3) → ℤ | (∀ i, 0 < v i) ∧ PrimitiveSpeeds v ∧
      loneliness v < 1/((m:ℝ)+3) ∧ OffCritical v} := by sorry

theorem large_near_tight_has_critical_plane {m : ℕ}
    (hLRC₂ : LonelyRunnerConjecture (m+1)) (hLRC₁ : LonelyRunnerConjecture (m+2))
    (v : Fin (m+3) → ℤ) (hv : ∀ i, 0 < v i) (hprim : PrimitiveSpeeds v)
    (hnear : loneliness v < 1/((m:ℝ)+3))
    (hlarge : (3*((m:ℝ)+3)/2)*boxHeightConstant (m+3)^2 ≤ speedNorm v) :
    ∃ z : Fin (m+3) → ℤ, (∃ i j, v i*z j-z i*v j ≠ 0) ∧
      planeLoneliness v z=1/((m:ℝ)+3) := by sorry

theorem speedNorm_bound_by_loneliness_gap {m : ℕ}
    (hLRC₂ : LonelyRunnerConjecture (m+1)) (hLRC₁ : LonelyRunnerConjecture (m+2))
    (v : Fin (m+3) → ℤ) (hv : ∀ i, 0 < v i) (hprim : PrimitiveSpeeds v)
    (hnear : loneliness v < 1/((m:ℝ)+3)) :
    speedNorm v < boxHeightConstant (m+3)/(2*(1/((m:ℝ)+3)-loneliness v)) := by sorry

theorem speedNorm_bound_by_reduced_denominator {m : ℕ}
    (hLRC₂ : LonelyRunnerConjecture (m+1)) (hLRC₁ : LonelyRunnerConjecture (m+2))
    (v : Fin (m+3) → ℤ) (hv : ∀ i, 0 < v i) (hprim : PrimitiveSpeeds v)
    (p q : ℕ) (hq : 0<q) (hvalue : loneliness v=(p:ℝ)/q)
    (hnear : loneliness v < 1/((m:ℝ)+3)) :
    speedNorm v < (((m:ℝ)+3)*boxHeightConstant (m+3)/2)*q/
      ((q:ℝ)-((m:ℝ)+3)*p) := by sorry

theorem speedNorm_lt_constant_mul_denominator {m : ℕ}
    (hLRC₂ : LonelyRunnerConjecture (m+1)) (hLRC₁ : LonelyRunnerConjecture (m+2))
    (v : Fin (m+3) → ℤ) (hv : ∀ i, 0 < v i) (hprim : PrimitiveSpeeds v)
    (p q : ℕ) (hq : 0<q) (hvalue : loneliness v=(p:ℝ)/q)
    (hnear : loneliness v < 1/((m:ℝ)+3)) :
    speedNorm v < (((m:ℝ)+3)*boxHeightConstant (m+3)/2)*q := by sorry

/-! Repeat-plane classification, with all lower-speed inputs explicit. -/

def RepeatVector {n : ℕ} (v : Fin n → ℤ) : Prop :=
  (∀ i, v i ≠ 0) ∧ ∃ i j, i ≠ j ∧ (v i).natAbs=(v j).natAbs

def integerPlane {n : ℕ} (c d : Fin n → ℤ) : Set (Fin n → ℝ) :=
  Set.range (fun p : ℝ × ℝ => fun i => p.1*c i+p.2*d i)

def canonicalRepeatVectors : Fin 10 → Fin 6 → ℤ := ![
![1,1,2,3,4,5],
![2,2,1,3,4,5],
![3,3,1,2,4,5],
![4,4,1,2,3,5],
![5,5,1,2,3,4],
![1,1,3,4,5,9],
![3,3,1,4,5,9],
![4,4,1,3,5,9],
![5,5,1,3,4,9],
![9,9,1,3,4,5]]

def KnownCriticalPlane (u w : Fin 6 → ℤ) : Prop :=
  ∃ c d : Fin 6 → ℤ, CriticalPresentation c d ∧ ∃ e : Equiv.Perm (Fin 6),
    ∃ s : Fin 6 → ℤ, (∀ i, s i=1 ∨ s i= -1) ∧
      integerPlane u w=integerPlane (fun i => s i*c (e i)) (fun i => s i*d (e i))

def TightFiveClassification : Prop :=
  ∀ v : Fin 5 → ℤ, PrimitiveSpeeds v → (∀ i, v i ≠ 0) → loneliness v=(1:ℝ)/6 →
    (List.ofFn (fun i => |v i|)).Perm [1,2,3,4,5] ∨
    (List.ofFn (fun i => |v i|)).Perm [1,3,4,5,9]

/-- Classification of all primitive zero-free tight five-tuples, up to signs and order. -/
theorem tight_five_classification : TightFiveClassification := by sorry

theorem exists_primitive_repeat_plane_basis {n : ℕ} (c d : Fin n → ℤ)
    (hc : ∀ i, c i ≠ 0) (a b : Fin n) (hab : c a*d b-d a*c b ≠ 0) :
    ∃ u w : Fin n → ℤ, PrimitiveSpeeds u ∧ PrimitiveSpeeds w ∧
      RepeatVector u ∧ RepeatVector w ∧
      (∃ i j, u i*w j-w i*u j ≠ 0) ∧ integerPlane u w=integerPlane c d := by sorry

theorem critical_plane_has_tight_repeat_basis {n : ℕ}
    (hLRC : LonelyRunnerConjecture n) (c d : Fin (n+1) → ℤ)
    (hc : ∀ i, c i ≠ 0) (a b : Fin (n+1)) (hab : c a*d b-d a*c b ≠ 0)
    (hcrit : planeLoneliness c d=1/((n:ℝ)+1)) :
    ∃ u w : Fin (n+1) → ℤ, PrimitiveSpeeds u ∧ PrimitiveSpeeds w ∧
      RepeatVector u ∧ RepeatVector w ∧
      loneliness u=1/((n:ℝ)+1) ∧ loneliness w=1/((n:ℝ)+1) ∧
      (∃ i j, u i*w j-w i*u j ≠ 0) ∧ integerPlane u w=integerPlane c d := by sorry

theorem finite_critical_planes_of_finite_tight {n : ℕ} [NeZero n]
    (hLRC : LonelyRunnerConjecture n)
    (hfinite : Set.Finite {v : Fin n → ℤ | PrimitiveSpeeds v ∧ (∀ i, v i ≠ 0) ∧
      loneliness v=1/((n:ℝ)+1)}) :
    Set.Finite {U : Set (Fin (n+1) → ℝ) | ∃ c d : Fin (n+1) → ℤ,
      (∀ i, c i ≠ 0) ∧ (∃ a b, c a*d b-d a*c b ≠ 0) ∧
      planeLoneliness c d=1/((n:ℝ)+1) ∧ U=integerPlane c d} := by sorry

theorem critical_repeat_pair_classified (i j : Fin 10) (w : Fin 6 → ℤ)
    (hw : (List.ofFn (fun k => |w k|)).Perm (List.ofFn (canonicalRepeatVectors j)))
    (hfirst : 0<w 0) (a b : Fin 6)
    (hm : canonicalRepeatVectors i a*w b-w a*canonicalRepeatVectors i b ≠ 0)
    (hL : planeLoneliness (canonicalRepeatVectors i) w ≤ (1:ℝ)/6) :
    KnownCriticalPlane (canonicalRepeatVectors i) w := by sorry

theorem critical_planes_classified (c d : Fin 6 → ℤ) (hc : ∀ i, c i ≠ 0)
    (a b : Fin 6) (hab : c a*d b-d a*c b ≠ 0)
    (hcrit : planeLoneliness c d=(1:ℝ)/6) : KnownCriticalPlane c d := by sorry

theorem critical_plane_question66 (c d v : Fin 6 → ℤ) (hc : ∀ i, c i ≠ 0)
    (a b : Fin 6) (hab : c a*d b-d a*c b ≠ 0)
    (hcrit : planeLoneliness c d=(1:ℝ)/6)
    (hv : (fun i => (v i:ℝ)) ∈ integerPlane c d)
    (hprim : PrimitiveSpeeds v) (hnz : ∀ i, v i ≠ 0)
    (p q : ℕ) (hq : 0<q) (hval : loneliness v=(p:ℝ)/q)
    (hnear : loneliness v<(1:ℝ)/6) : ∀ i, |v i|<3*(q:ℤ) := by sorry

theorem large_six_question66
    (v : Fin 6 → ℤ) (hv : ∀ i, 0<v i) (hprim : PrimitiveSpeeds v)
    (p q : ℕ) (hq : 0<q) (hval : loneliness v=(p:ℝ)/q)
    (hnear : loneliness v<(1:ℝ)/6)
    (hlarge : 9*boxHeightConstant 6^2 ≤ speedNorm v) : ∀ i, v i<3*(q:ℤ) := by sorry

theorem question66_violation_speed_bound
    (v : Fin 6 → ℤ) (hv : ∀ i, 0<v i) (hprim : PrimitiveSpeeds v)
    (p q : ℕ) (hq : 0<q) (hval : loneliness v=(p:ℝ)/q)
    (hnear : loneliness v<(1:ℝ)/6) (hbad : ∃ i, 3*(q:ℤ) ≤ v i) :
    speedNorm v<9*boxHeightConstant 6^2 := by sorry

theorem lonely_runner_four : LonelyRunnerConjecture 4 := by sorry

theorem lonely_runner_five : LonelyRunnerConjecture 5 := by sorry


/-- Question 6.7 for six speeds: the global effective bound has no unproved
lower-speed input. The off-critical assumption is the domain of the question. -/
theorem six_offCritical_speedNorm_bound
    (v : Fin 6 → ℤ) (hv : ∀ i, 0 < v i) (hprim : PrimitiveSpeeds v)
    (hnear : loneliness v < (1:ℝ)/6) (hoff : OffCritical v) :
    speedNorm v < 9*boxHeightConstant 6^2 := by sorry

/-- The six-speed off-critical near-tight exceptions form a finite set. -/
theorem six_finite_offCritical_near_tight :
    Set.Finite {v : Fin 6 → ℤ | (∀ i, 0 < v i) ∧ PrimitiveSpeeds v ∧
      loneliness v < (1:ℝ)/6 ∧ OffCritical v} := by sorry

/-- A global linear denominator bound for all positive primitive near-tight
sextuples. This coarse constant does not assert the sharp constant three. -/
theorem six_speedNorm_lt_constant_mul_denominator
    (v : Fin 6 → ℤ) (hv : ∀ i, 0 < v i) (hprim : PrimitiveSpeeds v)
    (p q : ℕ) (hq : 0<q) (hvalue : loneliness v=(p:ℝ)/q)
    (hnear : loneliness v < (1:ℝ)/6) :
    speedNorm v < (3*boxHeightConstant 6)*q := by sorry


end LonelyRunner
