import LonelyRunner.SixModular239Root106

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime239

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 18 => Root18.pairs x
  | 19 => Root19.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 31 => Root31.pairs x
  | 32 => Root32.pairs x
  | 35 => Root35.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 38 => Root38.pairs x
  | 39 => Root39.pairs x
  | 42 => Root42.pairs x
  | 43 => Root43.pairs x
  | 45 => Root45.pairs x
  | 47 => Root47.pairs x
  | 51 => Root51.pairs x
  | 55 => Root55.pairs x
  | 56 => Root56.pairs x
  | 57 => Root57.pairs x
  | 58 => Root58.pairs x
  | 59 => Root59.pairs x
  | 63 => Root63.pairs x
  | 65 => Root65.pairs x
  | 66 => Root66.pairs x
  | 67 => Root67.pairs x
  | 68 => Root68.pairs x
  | 69 => Root69.pairs x
  | 70 => Root70.pairs x
  | 71 => Root71.pairs x
  | 72 => Root72.pairs x
  | 77 => Root77.pairs x
  | 78 => Root78.pairs x
  | 79 => Root79.pairs x
  | 82 => Root82.pairs x
  | 89 => Root89.pairs x
  | 96 => Root96.pairs x
  | 98 => Root98.pairs x
  | 104 => Root104.pairs x
  | 106 => Root106.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 239 := by
  apply sorted_cover_of_checks 239 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 239 120 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 239 120 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 239 120 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 239 120 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 239 120 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 239 120 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 239 120 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 239 120 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 239 120 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 239 120 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 239 120 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 239 120 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 239 120 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 239 120 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · change pairCheck 239 120 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 239 120 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 239 120 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 239 120 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 239 120 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · change pairCheck 239 120 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 239 120 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · change pairCheck 239 120 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · change pairCheck 239 120 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 239 120 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · change pairCheck 239 120 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · change pairCheck 239 120 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · change pairCheck 239 120 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 51 inv Root51.pairs=true
      exact Root51.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 55 inv Root55.pairs=true
      exact Root55.pairs_ok
    · change pairCheck 239 120 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · change pairCheck 239 120 57 inv Root57.pairs=true
      exact Root57.pairs_ok
    · change pairCheck 239 120 58 inv Root58.pairs=true
      exact Root58.pairs_ok
    · change pairCheck 239 120 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 63 inv Root63.pairs=true
      exact Root63.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · change pairCheck 239 120 66 inv Root66.pairs=true
      exact Root66.pairs_ok
    · change pairCheck 239 120 67 inv Root67.pairs=true
      exact Root67.pairs_ok
    · change pairCheck 239 120 68 inv Root68.pairs=true
      exact Root68.pairs_ok
    · change pairCheck 239 120 69 inv Root69.pairs=true
      exact Root69.pairs_ok
    · change pairCheck 239 120 70 inv Root70.pairs=true
      exact Root70.pairs_ok
    · change pairCheck 239 120 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · change pairCheck 239 120 72 inv Root72.pairs=true
      exact Root72.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 77 inv Root77.pairs=true
      exact Root77.pairs_ok
    · change pairCheck 239 120 78 inv Root78.pairs=true
      exact Root78.pairs_ok
    · change pairCheck 239 120 79 inv Root79.pairs=true
      exact Root79.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 82 inv Root82.pairs=true
      exact Root82.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 89 inv Root89.pairs=true
      exact Root89.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 96 inv Root96.pairs=true
      exact Root96.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 98 inv Root98.pairs=true
      exact Root98.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 104 inv Root104.pairs=true
      exact Root104.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 239 120 106 inv Root106.pairs=true
      exact Root106.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 120 2 good Root2.pairs (triples 239 120) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 120 3 good Root3.pairs (triples 239 120) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 120 4 good Root4.pairs (triples 239 120) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 120 5 good Root5.pairs (triples 239 120) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 120 6 good Root6.pairs (triples 239 120) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 120 7 good Root7.pairs (triples 239 120) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 120 8 good Root8.pairs (triples 239 120) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 120 9 good Root9.pairs (triples 239 120) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 120 10 good Root10.pairs (triples 239 120) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 120 11 good Root11.pairs (triples 239 120) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 120 12 good Root12.pairs (triples 239 120) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 120 13 good Root13.pairs (triples 239 120) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 120 14 good Root14.pairs (triples 239 120) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 120 15 good Root15.pairs (triples 239 120) pivot=true
      exact Root15.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 18 good Root18.pairs (triples 239 120) pivot=true
      exact Root18.search_ok
    · change ModularSearch.rootCheck 120 19 good Root19.pairs (triples 239 120) pivot=true
      exact Root19.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 21 good Root21.pairs (triples 239 120) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 120 22 good Root22.pairs (triples 239 120) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 120 23 good Root23.pairs (triples 239 120) pivot=true
      exact Root23.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 25 good Root25.pairs (triples 239 120) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 120 26 good Root26.pairs (triples 239 120) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 120 27 good Root27.pairs (triples 239 120) pivot=true
      exact Root27.search_ok
    · change ModularSearch.rootCheck 120 28 good Root28.pairs (triples 239 120) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 120 29 good Root29.pairs (triples 239 120) pivot=true
      exact Root29.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 31 good Root31.pairs (triples 239 120) pivot=true
      exact Root31.search_ok
    · change ModularSearch.rootCheck 120 32 good Root32.pairs (triples 239 120) pivot=true
      exact Root32.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 35 good Root35.pairs (triples 239 120) pivot=true
      exact Root35.search_ok
    · change ModularSearch.rootCheck 120 36 good Root36.pairs (triples 239 120) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 120 37 good Root37.pairs (triples 239 120) pivot=true
      exact Root37.search_ok
    · change ModularSearch.rootCheck 120 38 good Root38.pairs (triples 239 120) pivot=true
      exact Root38.search_ok
    · change ModularSearch.rootCheck 120 39 good Root39.pairs (triples 239 120) pivot=true
      exact Root39.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 42 good Root42.pairs (triples 239 120) pivot=true
      exact Root42.search_ok
    · change ModularSearch.rootCheck 120 43 good Root43.pairs (triples 239 120) pivot=true
      exact Root43.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 45 good Root45.pairs (triples 239 120) pivot=true
      exact Root45.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 47 good Root47.pairs (triples 239 120) pivot=true
      exact Root47.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 51 good Root51.pairs (triples 239 120) pivot=true
      exact Root51.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 55 good Root55.pairs (triples 239 120) pivot=true
      exact Root55.search_ok
    · change ModularSearch.rootCheck 120 56 good Root56.pairs (triples 239 120) pivot=true
      exact Root56.search_ok
    · change ModularSearch.rootCheck 120 57 good Root57.pairs (triples 239 120) pivot=true
      exact Root57.search_ok
    · change ModularSearch.rootCheck 120 58 good Root58.pairs (triples 239 120) pivot=true
      exact Root58.search_ok
    · change ModularSearch.rootCheck 120 59 good Root59.pairs (triples 239 120) pivot=true
      exact Root59.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 63 good Root63.pairs (triples 239 120) pivot=true
      exact Root63.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 65 good Root65.pairs (triples 239 120) pivot=true
      exact Root65.search_ok
    · change ModularSearch.rootCheck 120 66 good Root66.pairs (triples 239 120) pivot=true
      exact Root66.search_ok
    · change ModularSearch.rootCheck 120 67 good Root67.pairs (triples 239 120) pivot=true
      exact Root67.search_ok
    · change ModularSearch.rootCheck 120 68 good Root68.pairs (triples 239 120) pivot=true
      exact Root68.search_ok
    · change ModularSearch.rootCheck 120 69 good Root69.pairs (triples 239 120) pivot=true
      exact Root69.search_ok
    · change ModularSearch.rootCheck 120 70 good Root70.pairs (triples 239 120) pivot=true
      exact Root70.search_ok
    · change ModularSearch.rootCheck 120 71 good Root71.pairs (triples 239 120) pivot=true
      exact Root71.search_ok
    · change ModularSearch.rootCheck 120 72 good Root72.pairs (triples 239 120) pivot=true
      exact Root72.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 77 good Root77.pairs (triples 239 120) pivot=true
      exact Root77.search_ok
    · change ModularSearch.rootCheck 120 78 good Root78.pairs (triples 239 120) pivot=true
      exact Root78.search_ok
    · change ModularSearch.rootCheck 120 79 good Root79.pairs (triples 239 120) pivot=true
      exact Root79.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 82 good Root82.pairs (triples 239 120) pivot=true
      exact Root82.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 89 good Root89.pairs (triples 239 120) pivot=true
      exact Root89.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 96 good Root96.pairs (triples 239 120) pivot=true
      exact Root96.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 98 good Root98.pairs (triples 239 120) pivot=true
      exact Root98.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 104 good Root104.pairs (triples 239 120) pivot=true
      exact Root104.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 120 106 good Root106.pairs (triples 239 120) pivot=true
      exact Root106.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 239 :=
  sixModularCover_of_normalized 239 (by norm_num)
    (normalizedSixCover_of_sorted 239 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime239
