import LonelyRunner.SixModular223Root94

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime223

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 38 => Root38.pairs x
  | 39 => Root39.pairs x
  | 41 => Root41.pairs x
  | 42 => Root42.pairs x
  | 43 => Root43.pairs x
  | 44 => Root44.pairs x
  | 45 => Root45.pairs x
  | 46 => Root46.pairs x
  | 48 => Root48.pairs x
  | 49 => Root49.pairs x
  | 50 => Root50.pairs x
  | 53 => Root53.pairs x
  | 54 => Root54.pairs x
  | 55 => Root55.pairs x
  | 57 => Root57.pairs x
  | 61 => Root61.pairs x
  | 64 => Root64.pairs x
  | 66 => Root66.pairs x
  | 68 => Root68.pairs x
  | 70 => Root70.pairs x
  | 72 => Root72.pairs x
  | 75 => Root75.pairs x
  | 77 => Root77.pairs x
  | 80 => Root80.pairs x
  | 94 => Root94.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 223 := by
  apply sorted_cover_of_checks 223 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 223 112 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 223 112 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 223 112 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 223 112 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 223 112 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 223 112 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 223 112 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 223 112 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 223 112 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 223 112 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 223 112 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 223 112 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 223 112 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 223 112 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 223 112 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · change pairCheck 223 112 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 223 112 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 223 112 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 223 112 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 223 112 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 223 112 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 223 112 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 223 112 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 223 112 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 223 112 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 223 112 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 223 112 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · change pairCheck 223 112 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · change pairCheck 223 112 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · change pairCheck 223 112 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · change pairCheck 223 112 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · change pairCheck 223 112 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · change pairCheck 223 112 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · change pairCheck 223 112 49 inv Root49.pairs=true
      exact Root49.pairs_ok
    · change pairCheck 223 112 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 53 inv Root53.pairs=true
      exact Root53.pairs_ok
    · change pairCheck 223 112 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · change pairCheck 223 112 55 inv Root55.pairs=true
      exact Root55.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 57 inv Root57.pairs=true
      exact Root57.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 61 inv Root61.pairs=true
      exact Root61.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 64 inv Root64.pairs=true
      exact Root64.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 66 inv Root66.pairs=true
      exact Root66.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 68 inv Root68.pairs=true
      exact Root68.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 70 inv Root70.pairs=true
      exact Root70.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 72 inv Root72.pairs=true
      exact Root72.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 75 inv Root75.pairs=true
      exact Root75.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 77 inv Root77.pairs=true
      exact Root77.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 80 inv Root80.pairs=true
      exact Root80.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 223 112 94 inv Root94.pairs=true
      exact Root94.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 112 2 good Root2.pairs (triples 223 112) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 112 3 good Root3.pairs (triples 223 112) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 112 4 good Root4.pairs (triples 223 112) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 112 5 good Root5.pairs (triples 223 112) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 112 6 good Root6.pairs (triples 223 112) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 112 7 good Root7.pairs (triples 223 112) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 112 8 good Root8.pairs (triples 223 112) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 112 9 good Root9.pairs (triples 223 112) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 112 10 good Root10.pairs (triples 223 112) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 112 11 good Root11.pairs (triples 223 112) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 112 12 good Root12.pairs (triples 223 112) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 112 13 good Root13.pairs (triples 223 112) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 112 14 good Root14.pairs (triples 223 112) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 112 15 good Root15.pairs (triples 223 112) pivot=true
      exact Root15.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 17 good Root17.pairs (triples 223 112) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 112 18 good Root18.pairs (triples 223 112) pivot=true
      exact Root18.search_ok
    · change ModularSearch.rootCheck 112 19 good Root19.pairs (triples 223 112) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 112 20 good Root20.pairs (triples 223 112) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 112 21 good Root21.pairs (triples 223 112) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 112 22 good Root22.pairs (triples 223 112) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 112 23 good Root23.pairs (triples 223 112) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 112 24 good Root24.pairs (triples 223 112) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 112 25 good Root25.pairs (triples 223 112) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 112 26 good Root26.pairs (triples 223 112) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 112 27 good Root27.pairs (triples 223 112) pivot=true
      exact Root27.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 29 good Root29.pairs (triples 223 112) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 112 30 good Root30.pairs (triples 223 112) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 112 31 good Root31.pairs (triples 223 112) pivot=true
      exact Root31.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 34 good Root34.pairs (triples 223 112) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 112 35 good Root35.pairs (triples 223 112) pivot=true
      exact Root35.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 38 good Root38.pairs (triples 223 112) pivot=true
      exact Root38.search_ok
    · change ModularSearch.rootCheck 112 39 good Root39.pairs (triples 223 112) pivot=true
      exact Root39.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 41 good Root41.pairs (triples 223 112) pivot=true
      exact Root41.search_ok
    · change ModularSearch.rootCheck 112 42 good Root42.pairs (triples 223 112) pivot=true
      exact Root42.search_ok
    · change ModularSearch.rootCheck 112 43 good Root43.pairs (triples 223 112) pivot=true
      exact Root43.search_ok
    · change ModularSearch.rootCheck 112 44 good Root44.pairs (triples 223 112) pivot=true
      exact Root44.search_ok
    · change ModularSearch.rootCheck 112 45 good Root45.pairs (triples 223 112) pivot=true
      exact Root45.search_ok
    · change ModularSearch.rootCheck 112 46 good Root46.pairs (triples 223 112) pivot=true
      exact Root46.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 48 good Root48.pairs (triples 223 112) pivot=true
      exact Root48.search_ok
    · change ModularSearch.rootCheck 112 49 good Root49.pairs (triples 223 112) pivot=true
      exact Root49.search_ok
    · change ModularSearch.rootCheck 112 50 good Root50.pairs (triples 223 112) pivot=true
      exact Root50.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 53 good Root53.pairs (triples 223 112) pivot=true
      exact Root53.search_ok
    · change ModularSearch.rootCheck 112 54 good Root54.pairs (triples 223 112) pivot=true
      exact Root54.search_ok
    · change ModularSearch.rootCheck 112 55 good Root55.pairs (triples 223 112) pivot=true
      exact Root55.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 57 good Root57.pairs (triples 223 112) pivot=true
      exact Root57.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 61 good Root61.pairs (triples 223 112) pivot=true
      exact Root61.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 64 good Root64.pairs (triples 223 112) pivot=true
      exact Root64.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 66 good Root66.pairs (triples 223 112) pivot=true
      exact Root66.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 68 good Root68.pairs (triples 223 112) pivot=true
      exact Root68.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 70 good Root70.pairs (triples 223 112) pivot=true
      exact Root70.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 72 good Root72.pairs (triples 223 112) pivot=true
      exact Root72.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 75 good Root75.pairs (triples 223 112) pivot=true
      exact Root75.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 77 good Root77.pairs (triples 223 112) pivot=true
      exact Root77.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 80 good Root80.pairs (triples 223 112) pivot=true
      exact Root80.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 112 94 good Root94.pairs (triples 223 112) pivot=true
      exact Root94.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 223 :=
  sixModularCover_of_normalized 223 (by norm_num)
    (normalizedSixCover_of_sorted 223 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime223
