import LonelyRunner.SixModular193Root86

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime193

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 28 => Root28.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 33 => Root33.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 38 => Root38.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 44 => Root44.pairs x
  | 47 => Root47.pairs x
  | 49 => Root49.pairs x
  | 51 => Root51.pairs x
  | 60 => Root60.pairs x
  | 65 => Root65.pairs x
  | 67 => Root67.pairs x
  | 68 => Root68.pairs x
  | 70 => Root70.pairs x
  | 71 => Root71.pairs x
  | 81 => Root81.pairs x
  | 83 => Root83.pairs x
  | 84 => Root84.pairs x
  | 86 => Root86.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 193 := by
  apply sorted_cover_of_checks 193 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 193 97 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 193 97 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 193 97 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 193 97 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 193 97 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 193 97 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 193 97 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 193 97 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 193 97 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 193 97 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 193 97 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 193 97 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 193 97 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 193 97 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 193 97 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · change pairCheck 193 97 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 193 97 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 193 97 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 193 97 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 193 97 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 193 97 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 193 97 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · change pairCheck 193 97 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 193 97 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 193 97 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · change pairCheck 193 97 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · change pairCheck 193 97 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 193 97 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 193 97 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 49 inv Root49.pairs=true
      exact Root49.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 51 inv Root51.pairs=true
      exact Root51.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 60 inv Root60.pairs=true
      exact Root60.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 67 inv Root67.pairs=true
      exact Root67.pairs_ok
    · change pairCheck 193 97 68 inv Root68.pairs=true
      exact Root68.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 70 inv Root70.pairs=true
      exact Root70.pairs_ok
    · change pairCheck 193 97 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 83 inv Root83.pairs=true
      exact Root83.pairs_ok
    · change pairCheck 193 97 84 inv Root84.pairs=true
      exact Root84.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 193 97 86 inv Root86.pairs=true
      exact Root86.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 97 2 good Root2.pairs (triples 193 97) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 97 3 good Root3.pairs (triples 193 97) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 97 4 good Root4.pairs (triples 193 97) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 97 5 good Root5.pairs (triples 193 97) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 97 6 good Root6.pairs (triples 193 97) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 97 7 good Root7.pairs (triples 193 97) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 97 8 good Root8.pairs (triples 193 97) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 97 9 good Root9.pairs (triples 193 97) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 97 10 good Root10.pairs (triples 193 97) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 97 11 good Root11.pairs (triples 193 97) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 97 12 good Root12.pairs (triples 193 97) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 97 13 good Root13.pairs (triples 193 97) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 97 14 good Root14.pairs (triples 193 97) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 97 15 good Root15.pairs (triples 193 97) pivot=true
      exact Root15.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 17 good Root17.pairs (triples 193 97) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 97 18 good Root18.pairs (triples 193 97) pivot=true
      exact Root18.search_ok
    · change ModularSearch.rootCheck 97 19 good Root19.pairs (triples 193 97) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 97 20 good Root20.pairs (triples 193 97) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 97 21 good Root21.pairs (triples 193 97) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 97 22 good Root22.pairs (triples 193 97) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 97 23 good Root23.pairs (triples 193 97) pivot=true
      exact Root23.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 25 good Root25.pairs (triples 193 97) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 97 26 good Root26.pairs (triples 193 97) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 97 27 good Root27.pairs (triples 193 97) pivot=true
      exact Root27.search_ok
    · change ModularSearch.rootCheck 97 28 good Root28.pairs (triples 193 97) pivot=true
      exact Root28.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 30 good Root30.pairs (triples 193 97) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 97 31 good Root31.pairs (triples 193 97) pivot=true
      exact Root31.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 33 good Root33.pairs (triples 193 97) pivot=true
      exact Root33.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 36 good Root36.pairs (triples 193 97) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 97 37 good Root37.pairs (triples 193 97) pivot=true
      exact Root37.search_ok
    · change ModularSearch.rootCheck 97 38 good Root38.pairs (triples 193 97) pivot=true
      exact Root38.search_ok
    · change ModularSearch.rootCheck 97 39 good Root39.pairs (triples 193 97) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 97 40 good Root40.pairs (triples 193 97) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 97 41 good Root41.pairs (triples 193 97) pivot=true
      exact Root41.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 44 good Root44.pairs (triples 193 97) pivot=true
      exact Root44.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 47 good Root47.pairs (triples 193 97) pivot=true
      exact Root47.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 49 good Root49.pairs (triples 193 97) pivot=true
      exact Root49.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 51 good Root51.pairs (triples 193 97) pivot=true
      exact Root51.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 60 good Root60.pairs (triples 193 97) pivot=true
      exact Root60.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 65 good Root65.pairs (triples 193 97) pivot=true
      exact Root65.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 67 good Root67.pairs (triples 193 97) pivot=true
      exact Root67.search_ok
    · change ModularSearch.rootCheck 97 68 good Root68.pairs (triples 193 97) pivot=true
      exact Root68.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 70 good Root70.pairs (triples 193 97) pivot=true
      exact Root70.search_ok
    · change ModularSearch.rootCheck 97 71 good Root71.pairs (triples 193 97) pivot=true
      exact Root71.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 81 good Root81.pairs (triples 193 97) pivot=true
      exact Root81.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 83 good Root83.pairs (triples 193 97) pivot=true
      exact Root83.search_ok
    · change ModularSearch.rootCheck 97 84 good Root84.pairs (triples 193 97) pivot=true
      exact Root84.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 97 86 good Root86.pairs (triples 193 97) pivot=true
      exact Root86.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 193 :=
  sixModularCover_of_normalized 193 (by norm_num)
    (normalizedSixCover_of_sorted 193 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime193
