import LonelyRunner.SixModular191Root88

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime191

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 25 => Root25.pairs x
  | 27 => Root27.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 36 => Root36.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 42 => Root42.pairs x
  | 46 => Root46.pairs x
  | 47 => Root47.pairs x
  | 55 => Root55.pairs x
  | 56 => Root56.pairs x
  | 57 => Root57.pairs x
  | 59 => Root59.pairs x
  | 61 => Root61.pairs x
  | 62 => Root62.pairs x
  | 63 => Root63.pairs x
  | 71 => Root71.pairs x
  | 74 => Root74.pairs x
  | 76 => Root76.pairs x
  | 87 => Root87.pairs x
  | 88 => Root88.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 191 := by
  apply sorted_cover_of_checks 191 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 191 96 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 191 96 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 191 96 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 191 96 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 191 96 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 191 96 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 191 96 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 191 96 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 191 96 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 191 96 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 191 96 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 191 96 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 191 96 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 191 96 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 191 96 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 191 96 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 191 96 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 191 96 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · change pairCheck 191 96 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 191 96 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 191 96 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 191 96 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 191 96 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 191 96 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · change pairCheck 191 96 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 191 96 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · change pairCheck 191 96 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 55 inv Root55.pairs=true
      exact Root55.pairs_ok
    · change pairCheck 191 96 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · change pairCheck 191 96 57 inv Root57.pairs=true
      exact Root57.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 61 inv Root61.pairs=true
      exact Root61.pairs_ok
    · change pairCheck 191 96 62 inv Root62.pairs=true
      exact Root62.pairs_ok
    · change pairCheck 191 96 63 inv Root63.pairs=true
      exact Root63.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 74 inv Root74.pairs=true
      exact Root74.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 76 inv Root76.pairs=true
      exact Root76.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 191 96 87 inv Root87.pairs=true
      exact Root87.pairs_ok
    · change pairCheck 191 96 88 inv Root88.pairs=true
      exact Root88.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 96 2 good Root2.pairs (triples 191 96) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 96 3 good Root3.pairs (triples 191 96) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 96 4 good Root4.pairs (triples 191 96) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 96 5 good Root5.pairs (triples 191 96) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 96 6 good Root6.pairs (triples 191 96) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 96 7 good Root7.pairs (triples 191 96) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 96 8 good Root8.pairs (triples 191 96) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 96 9 good Root9.pairs (triples 191 96) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 96 10 good Root10.pairs (triples 191 96) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 96 11 good Root11.pairs (triples 191 96) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 96 12 good Root12.pairs (triples 191 96) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 96 13 good Root13.pairs (triples 191 96) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 96 14 good Root14.pairs (triples 191 96) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 96 15 good Root15.pairs (triples 191 96) pivot=true
      exact Root15.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 17 good Root17.pairs (triples 191 96) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 96 18 good Root18.pairs (triples 191 96) pivot=true
      exact Root18.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 20 good Root20.pairs (triples 191 96) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 96 21 good Root21.pairs (triples 191 96) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 96 22 good Root22.pairs (triples 191 96) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 96 23 good Root23.pairs (triples 191 96) pivot=true
      exact Root23.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 25 good Root25.pairs (triples 191 96) pivot=true
      exact Root25.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 27 good Root27.pairs (triples 191 96) pivot=true
      exact Root27.search_ok
    · change ModularSearch.rootCheck 96 28 good Root28.pairs (triples 191 96) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 96 29 good Root29.pairs (triples 191 96) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 96 30 good Root30.pairs (triples 191 96) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 96 31 good Root31.pairs (triples 191 96) pivot=true
      exact Root31.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 33 good Root33.pairs (triples 191 96) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 96 34 good Root34.pairs (triples 191 96) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 96 35 good Root35.pairs (triples 191 96) pivot=true
      exact Root35.search_ok
    · change ModularSearch.rootCheck 96 36 good Root36.pairs (triples 191 96) pivot=true
      exact Root36.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 39 good Root39.pairs (triples 191 96) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 96 40 good Root40.pairs (triples 191 96) pivot=true
      exact Root40.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 42 good Root42.pairs (triples 191 96) pivot=true
      exact Root42.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 46 good Root46.pairs (triples 191 96) pivot=true
      exact Root46.search_ok
    · change ModularSearch.rootCheck 96 47 good Root47.pairs (triples 191 96) pivot=true
      exact Root47.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 55 good Root55.pairs (triples 191 96) pivot=true
      exact Root55.search_ok
    · change ModularSearch.rootCheck 96 56 good Root56.pairs (triples 191 96) pivot=true
      exact Root56.search_ok
    · change ModularSearch.rootCheck 96 57 good Root57.pairs (triples 191 96) pivot=true
      exact Root57.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 59 good Root59.pairs (triples 191 96) pivot=true
      exact Root59.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 61 good Root61.pairs (triples 191 96) pivot=true
      exact Root61.search_ok
    · change ModularSearch.rootCheck 96 62 good Root62.pairs (triples 191 96) pivot=true
      exact Root62.search_ok
    · change ModularSearch.rootCheck 96 63 good Root63.pairs (triples 191 96) pivot=true
      exact Root63.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 71 good Root71.pairs (triples 191 96) pivot=true
      exact Root71.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 74 good Root74.pairs (triples 191 96) pivot=true
      exact Root74.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 76 good Root76.pairs (triples 191 96) pivot=true
      exact Root76.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 96 87 good Root87.pairs (triples 191 96) pivot=true
      exact Root87.search_ok
    · change ModularSearch.rootCheck 96 88 good Root88.pairs (triples 191 96) pivot=true
      exact Root88.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 191 :=
  sixModularCover_of_normalized 191 (by norm_num)
    (normalizedSixCover_of_sorted 191 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime191
