import LonelyRunner.SixModular251Root117

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime251

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 32 => Root32.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 37 => Root37.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 44 => Root44.pairs x
  | 45 => Root45.pairs x
  | 46 => Root46.pairs x
  | 48 => Root48.pairs x
  | 51 => Root51.pairs x
  | 52 => Root52.pairs x
  | 53 => Root53.pairs x
  | 54 => Root54.pairs x
  | 55 => Root55.pairs x
  | 56 => Root56.pairs x
  | 61 => Root61.pairs x
  | 62 => Root62.pairs x
  | 65 => Root65.pairs x
  | 70 => Root70.pairs x
  | 71 => Root71.pairs x
  | 72 => Root72.pairs x
  | 74 => Root74.pairs x
  | 75 => Root75.pairs x
  | 76 => Root76.pairs x
  | 77 => Root77.pairs x
  | 80 => Root80.pairs x
  | 82 => Root82.pairs x
  | 83 => Root83.pairs x
  | 86 => Root86.pairs x
  | 89 => Root89.pairs x
  | 98 => Root98.pairs x
  | 100 => Root100.pairs x
  | 116 => Root116.pairs x
  | 117 => Root117.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 251 := by
  apply sorted_cover_of_checks 251 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 251 126 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 251 126 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 251 126 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 251 126 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 251 126 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 251 126 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 251 126 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 251 126 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 251 126 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 251 126 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 251 126 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 251 126 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 251 126 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 251 126 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 251 126 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 251 126 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 251 126 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 251 126 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 251 126 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 251 126 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 251 126 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · change pairCheck 251 126 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · change pairCheck 251 126 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 251 126 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 251 126 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 251 126 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 251 126 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · change pairCheck 251 126 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · change pairCheck 251 126 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 51 inv Root51.pairs=true
      exact Root51.pairs_ok
    · change pairCheck 251 126 52 inv Root52.pairs=true
      exact Root52.pairs_ok
    · change pairCheck 251 126 53 inv Root53.pairs=true
      exact Root53.pairs_ok
    · change pairCheck 251 126 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · change pairCheck 251 126 55 inv Root55.pairs=true
      exact Root55.pairs_ok
    · change pairCheck 251 126 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 61 inv Root61.pairs=true
      exact Root61.pairs_ok
    · change pairCheck 251 126 62 inv Root62.pairs=true
      exact Root62.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 70 inv Root70.pairs=true
      exact Root70.pairs_ok
    · change pairCheck 251 126 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · change pairCheck 251 126 72 inv Root72.pairs=true
      exact Root72.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 74 inv Root74.pairs=true
      exact Root74.pairs_ok
    · change pairCheck 251 126 75 inv Root75.pairs=true
      exact Root75.pairs_ok
    · change pairCheck 251 126 76 inv Root76.pairs=true
      exact Root76.pairs_ok
    · change pairCheck 251 126 77 inv Root77.pairs=true
      exact Root77.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 80 inv Root80.pairs=true
      exact Root80.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 82 inv Root82.pairs=true
      exact Root82.pairs_ok
    · change pairCheck 251 126 83 inv Root83.pairs=true
      exact Root83.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 86 inv Root86.pairs=true
      exact Root86.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 89 inv Root89.pairs=true
      exact Root89.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 98 inv Root98.pairs=true
      exact Root98.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 100 inv Root100.pairs=true
      exact Root100.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 251 126 116 inv Root116.pairs=true
      exact Root116.pairs_ok
    · change pairCheck 251 126 117 inv Root117.pairs=true
      exact Root117.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 126 2 good Root2.pairs (triples 251 126) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 126 3 good Root3.pairs (triples 251 126) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 126 4 good Root4.pairs (triples 251 126) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 126 5 good Root5.pairs (triples 251 126) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 126 6 good Root6.pairs (triples 251 126) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 126 7 good Root7.pairs (triples 251 126) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 126 8 good Root8.pairs (triples 251 126) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 126 9 good Root9.pairs (triples 251 126) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 126 10 good Root10.pairs (triples 251 126) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 126 11 good Root11.pairs (triples 251 126) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 126 12 good Root12.pairs (triples 251 126) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 126 13 good Root13.pairs (triples 251 126) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 126 14 good Root14.pairs (triples 251 126) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 126 15 good Root15.pairs (triples 251 126) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 126 16 good Root16.pairs (triples 251 126) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 126 17 good Root17.pairs (triples 251 126) pivot=true
      exact Root17.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 19 good Root19.pairs (triples 251 126) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 126 20 good Root20.pairs (triples 251 126) pivot=true
      exact Root20.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 22 good Root22.pairs (triples 251 126) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 126 23 good Root23.pairs (triples 251 126) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 126 24 good Root24.pairs (triples 251 126) pivot=true
      exact Root24.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 26 good Root26.pairs (triples 251 126) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 126 27 good Root27.pairs (triples 251 126) pivot=true
      exact Root27.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 30 good Root30.pairs (triples 251 126) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 126 31 good Root31.pairs (triples 251 126) pivot=true
      exact Root31.search_ok
    · change ModularSearch.rootCheck 126 32 good Root32.pairs (triples 251 126) pivot=true
      exact Root32.search_ok
    · change ModularSearch.rootCheck 126 33 good Root33.pairs (triples 251 126) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 126 34 good Root34.pairs (triples 251 126) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 126 35 good Root35.pairs (triples 251 126) pivot=true
      exact Root35.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 37 good Root37.pairs (triples 251 126) pivot=true
      exact Root37.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 39 good Root39.pairs (triples 251 126) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 126 40 good Root40.pairs (triples 251 126) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 126 41 good Root41.pairs (triples 251 126) pivot=true
      exact Root41.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 44 good Root44.pairs (triples 251 126) pivot=true
      exact Root44.search_ok
    · change ModularSearch.rootCheck 126 45 good Root45.pairs (triples 251 126) pivot=true
      exact Root45.search_ok
    · change ModularSearch.rootCheck 126 46 good Root46.pairs (triples 251 126) pivot=true
      exact Root46.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 48 good Root48.pairs (triples 251 126) pivot=true
      exact Root48.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 51 good Root51.pairs (triples 251 126) pivot=true
      exact Root51.search_ok
    · change ModularSearch.rootCheck 126 52 good Root52.pairs (triples 251 126) pivot=true
      exact Root52.search_ok
    · change ModularSearch.rootCheck 126 53 good Root53.pairs (triples 251 126) pivot=true
      exact Root53.search_ok
    · change ModularSearch.rootCheck 126 54 good Root54.pairs (triples 251 126) pivot=true
      exact Root54.search_ok
    · change ModularSearch.rootCheck 126 55 good Root55.pairs (triples 251 126) pivot=true
      exact Root55.search_ok
    · change ModularSearch.rootCheck 126 56 good Root56.pairs (triples 251 126) pivot=true
      exact Root56.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 61 good Root61.pairs (triples 251 126) pivot=true
      exact Root61.search_ok
    · change ModularSearch.rootCheck 126 62 good Root62.pairs (triples 251 126) pivot=true
      exact Root62.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 65 good Root65.pairs (triples 251 126) pivot=true
      exact Root65.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 70 good Root70.pairs (triples 251 126) pivot=true
      exact Root70.search_ok
    · change ModularSearch.rootCheck 126 71 good Root71.pairs (triples 251 126) pivot=true
      exact Root71.search_ok
    · change ModularSearch.rootCheck 126 72 good Root72.pairs (triples 251 126) pivot=true
      exact Root72.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 74 good Root74.pairs (triples 251 126) pivot=true
      exact Root74.search_ok
    · change ModularSearch.rootCheck 126 75 good Root75.pairs (triples 251 126) pivot=true
      exact Root75.search_ok
    · change ModularSearch.rootCheck 126 76 good Root76.pairs (triples 251 126) pivot=true
      exact Root76.search_ok
    · change ModularSearch.rootCheck 126 77 good Root77.pairs (triples 251 126) pivot=true
      exact Root77.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 80 good Root80.pairs (triples 251 126) pivot=true
      exact Root80.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 82 good Root82.pairs (triples 251 126) pivot=true
      exact Root82.search_ok
    · change ModularSearch.rootCheck 126 83 good Root83.pairs (triples 251 126) pivot=true
      exact Root83.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 86 good Root86.pairs (triples 251 126) pivot=true
      exact Root86.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 89 good Root89.pairs (triples 251 126) pivot=true
      exact Root89.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 98 good Root98.pairs (triples 251 126) pivot=true
      exact Root98.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 100 good Root100.pairs (triples 251 126) pivot=true
      exact Root100.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 126 116 good Root116.pairs (triples 251 126) pivot=true
      exact Root116.search_ok
    · change ModularSearch.rootCheck 126 117 good Root117.pairs (triples 251 126) pivot=true
      exact Root117.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 251 :=
  sixModularCover_of_normalized 251 (by norm_num)
    (normalizedSixCover_of_sorted 251 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime251
