import LonelyRunner.SixModular227Root103

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime227

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 32 => Root32.pairs x
  | 33 => Root33.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 39 => Root39.pairs x
  | 41 => Root41.pairs x
  | 43 => Root43.pairs x
  | 44 => Root44.pairs x
  | 45 => Root45.pairs x
  | 46 => Root46.pairs x
  | 48 => Root48.pairs x
  | 49 => Root49.pairs x
  | 50 => Root50.pairs x
  | 51 => Root51.pairs x
  | 56 => Root56.pairs x
  | 58 => Root58.pairs x
  | 60 => Root60.pairs x
  | 61 => Root61.pairs x
  | 66 => Root66.pairs x
  | 69 => Root69.pairs x
  | 70 => Root70.pairs x
  | 75 => Root75.pairs x
  | 80 => Root80.pairs x
  | 83 => Root83.pairs x
  | 84 => Root84.pairs x
  | 94 => Root94.pairs x
  | 97 => Root97.pairs x
  | 103 => Root103.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 227 := by
  apply sorted_cover_of_checks 227 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 227 114 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 227 114 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 227 114 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 227 114 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 227 114 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 227 114 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 227 114 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 227 114 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 227 114 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 227 114 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 227 114 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 227 114 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 227 114 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 227 114 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 227 114 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 227 114 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 227 114 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 227 114 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 227 114 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 227 114 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 227 114 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 227 114 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 227 114 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 227 114 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · change pairCheck 227 114 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 227 114 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 227 114 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · change pairCheck 227 114 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 227 114 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · change pairCheck 227 114 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · change pairCheck 227 114 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · change pairCheck 227 114 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · change pairCheck 227 114 49 inv Root49.pairs=true
      exact Root49.pairs_ok
    · change pairCheck 227 114 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · change pairCheck 227 114 51 inv Root51.pairs=true
      exact Root51.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 58 inv Root58.pairs=true
      exact Root58.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 60 inv Root60.pairs=true
      exact Root60.pairs_ok
    · change pairCheck 227 114 61 inv Root61.pairs=true
      exact Root61.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 66 inv Root66.pairs=true
      exact Root66.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 69 inv Root69.pairs=true
      exact Root69.pairs_ok
    · change pairCheck 227 114 70 inv Root70.pairs=true
      exact Root70.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 75 inv Root75.pairs=true
      exact Root75.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 80 inv Root80.pairs=true
      exact Root80.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 83 inv Root83.pairs=true
      exact Root83.pairs_ok
    · change pairCheck 227 114 84 inv Root84.pairs=true
      exact Root84.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 94 inv Root94.pairs=true
      exact Root94.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 97 inv Root97.pairs=true
      exact Root97.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 227 114 103 inv Root103.pairs=true
      exact Root103.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 114 2 good Root2.pairs (triples 227 114) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 114 3 good Root3.pairs (triples 227 114) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 114 4 good Root4.pairs (triples 227 114) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 114 5 good Root5.pairs (triples 227 114) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 114 6 good Root6.pairs (triples 227 114) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 114 7 good Root7.pairs (triples 227 114) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 114 8 good Root8.pairs (triples 227 114) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 114 9 good Root9.pairs (triples 227 114) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 114 10 good Root10.pairs (triples 227 114) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 114 11 good Root11.pairs (triples 227 114) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 114 12 good Root12.pairs (triples 227 114) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 114 13 good Root13.pairs (triples 227 114) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 114 14 good Root14.pairs (triples 227 114) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 114 15 good Root15.pairs (triples 227 114) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 114 16 good Root16.pairs (triples 227 114) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 114 17 good Root17.pairs (triples 227 114) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 114 18 good Root18.pairs (triples 227 114) pivot=true
      exact Root18.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 20 good Root20.pairs (triples 227 114) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 114 21 good Root21.pairs (triples 227 114) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 114 22 good Root22.pairs (triples 227 114) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 114 23 good Root23.pairs (triples 227 114) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 114 24 good Root24.pairs (triples 227 114) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 114 25 good Root25.pairs (triples 227 114) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 114 26 good Root26.pairs (triples 227 114) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 114 27 good Root27.pairs (triples 227 114) pivot=true
      exact Root27.search_ok
    · change ModularSearch.rootCheck 114 28 good Root28.pairs (triples 227 114) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 114 29 good Root29.pairs (triples 227 114) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 114 30 good Root30.pairs (triples 227 114) pivot=true
      exact Root30.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 32 good Root32.pairs (triples 227 114) pivot=true
      exact Root32.search_ok
    · change ModularSearch.rootCheck 114 33 good Root33.pairs (triples 227 114) pivot=true
      exact Root33.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 36 good Root36.pairs (triples 227 114) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 114 37 good Root37.pairs (triples 227 114) pivot=true
      exact Root37.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 39 good Root39.pairs (triples 227 114) pivot=true
      exact Root39.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 41 good Root41.pairs (triples 227 114) pivot=true
      exact Root41.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 43 good Root43.pairs (triples 227 114) pivot=true
      exact Root43.search_ok
    · change ModularSearch.rootCheck 114 44 good Root44.pairs (triples 227 114) pivot=true
      exact Root44.search_ok
    · change ModularSearch.rootCheck 114 45 good Root45.pairs (triples 227 114) pivot=true
      exact Root45.search_ok
    · change ModularSearch.rootCheck 114 46 good Root46.pairs (triples 227 114) pivot=true
      exact Root46.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 48 good Root48.pairs (triples 227 114) pivot=true
      exact Root48.search_ok
    · change ModularSearch.rootCheck 114 49 good Root49.pairs (triples 227 114) pivot=true
      exact Root49.search_ok
    · change ModularSearch.rootCheck 114 50 good Root50.pairs (triples 227 114) pivot=true
      exact Root50.search_ok
    · change ModularSearch.rootCheck 114 51 good Root51.pairs (triples 227 114) pivot=true
      exact Root51.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 56 good Root56.pairs (triples 227 114) pivot=true
      exact Root56.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 58 good Root58.pairs (triples 227 114) pivot=true
      exact Root58.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 60 good Root60.pairs (triples 227 114) pivot=true
      exact Root60.search_ok
    · change ModularSearch.rootCheck 114 61 good Root61.pairs (triples 227 114) pivot=true
      exact Root61.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 66 good Root66.pairs (triples 227 114) pivot=true
      exact Root66.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 69 good Root69.pairs (triples 227 114) pivot=true
      exact Root69.search_ok
    · change ModularSearch.rootCheck 114 70 good Root70.pairs (triples 227 114) pivot=true
      exact Root70.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 75 good Root75.pairs (triples 227 114) pivot=true
      exact Root75.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 80 good Root80.pairs (triples 227 114) pivot=true
      exact Root80.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 83 good Root83.pairs (triples 227 114) pivot=true
      exact Root83.search_ok
    · change ModularSearch.rootCheck 114 84 good Root84.pairs (triples 227 114) pivot=true
      exact Root84.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 94 good Root94.pairs (triples 227 114) pivot=true
      exact Root94.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 97 good Root97.pairs (triples 227 114) pivot=true
      exact Root97.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 114 103 good Root103.pairs (triples 227 114) pivot=true
      exact Root103.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 227 :=
  sixModularCover_of_normalized 227 (by norm_num)
    (normalizedSixCover_of_sorted 227 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime227
