import LonelyRunner.SixModular311Roots9

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime311

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 25 => Root25.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 32 => Root32.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 38 => Root38.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 43 => Root43.pairs x
  | 44 => Root44.pairs x
  | 45 => Root45.pairs x
  | 46 => Root46.pairs x
  | 47 => Root47.pairs x
  | 48 => Root48.pairs x
  | 49 => Root49.pairs x
  | 50 => Root50.pairs x
  | 51 => Root51.pairs x
  | 53 => Root53.pairs x
  | 54 => Root54.pairs x
  | 55 => Root55.pairs x
  | 57 => Root57.pairs x
  | 58 => Root58.pairs x
  | 63 => Root63.pairs x
  | 65 => Root65.pairs x
  | 71 => Root71.pairs x
  | 72 => Root72.pairs x
  | 73 => Root73.pairs x
  | 75 => Root75.pairs x
  | 77 => Root77.pairs x
  | 81 => Root81.pairs x
  | 82 => Root82.pairs x
  | 84 => Root84.pairs x
  | 85 => Root85.pairs x
  | 87 => Root87.pairs x
  | 93 => Root93.pairs x
  | 97 => Root97.pairs x
  | 101 => Root101.pairs x
  | 102 => Root102.pairs x
  | 103 => Root103.pairs x
  | 115 => Root115.pairs x
  | 116 => Root116.pairs x
  | 120 => Root120.pairs x
  | 122 => Root122.pairs x
  | 123 => Root123.pairs x
  | 124 => Root124.pairs x
  | 129 => Root129.pairs x
  | 132 => Root132.pairs x
  | 133 => Root133.pairs x
  | 138 => Root138.pairs x
  | 145 => Root145.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 311 := by
  apply sorted_cover_of_checks 311 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 311 156 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 311 156 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 311 156 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 311 156 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 311 156 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 311 156 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 311 156 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 311 156 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 311 156 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 311 156 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 311 156 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 311 156 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 311 156 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 311 156 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 311 156 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 311 156 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 311 156 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · change pairCheck 311 156 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 311 156 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 311 156 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 311 156 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 311 156 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 311 156 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 311 156 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · change pairCheck 311 156 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 311 156 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 311 156 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · change pairCheck 311 156 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 311 156 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · change pairCheck 311 156 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 311 156 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · change pairCheck 311 156 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · change pairCheck 311 156 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · change pairCheck 311 156 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · change pairCheck 311 156 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · change pairCheck 311 156 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · change pairCheck 311 156 49 inv Root49.pairs=true
      exact Root49.pairs_ok
    · change pairCheck 311 156 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · change pairCheck 311 156 51 inv Root51.pairs=true
      exact Root51.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 53 inv Root53.pairs=true
      exact Root53.pairs_ok
    · change pairCheck 311 156 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · change pairCheck 311 156 55 inv Root55.pairs=true
      exact Root55.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 57 inv Root57.pairs=true
      exact Root57.pairs_ok
    · change pairCheck 311 156 58 inv Root58.pairs=true
      exact Root58.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 63 inv Root63.pairs=true
      exact Root63.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · change pairCheck 311 156 72 inv Root72.pairs=true
      exact Root72.pairs_ok
    · change pairCheck 311 156 73 inv Root73.pairs=true
      exact Root73.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 75 inv Root75.pairs=true
      exact Root75.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 77 inv Root77.pairs=true
      exact Root77.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · change pairCheck 311 156 82 inv Root82.pairs=true
      exact Root82.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 84 inv Root84.pairs=true
      exact Root84.pairs_ok
    · change pairCheck 311 156 85 inv Root85.pairs=true
      exact Root85.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 87 inv Root87.pairs=true
      exact Root87.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 93 inv Root93.pairs=true
      exact Root93.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 97 inv Root97.pairs=true
      exact Root97.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 101 inv Root101.pairs=true
      exact Root101.pairs_ok
    · change pairCheck 311 156 102 inv Root102.pairs=true
      exact Root102.pairs_ok
    · change pairCheck 311 156 103 inv Root103.pairs=true
      exact Root103.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 115 inv Root115.pairs=true
      exact Root115.pairs_ok
    · change pairCheck 311 156 116 inv Root116.pairs=true
      exact Root116.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 120 inv Root120.pairs=true
      exact Root120.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 122 inv Root122.pairs=true
      exact Root122.pairs_ok
    · change pairCheck 311 156 123 inv Root123.pairs=true
      exact Root123.pairs_ok
    · change pairCheck 311 156 124 inv Root124.pairs=true
      exact Root124.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 129 inv Root129.pairs=true
      exact Root129.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 132 inv Root132.pairs=true
      exact Root132.pairs_ok
    · change pairCheck 311 156 133 inv Root133.pairs=true
      exact Root133.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 138 inv Root138.pairs=true
      exact Root138.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 311 156 145 inv Root145.pairs=true
      exact Root145.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 156 2 good Root2.pairs (triples 311 156) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 156 3 good Root3.pairs (triples 311 156) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 156 4 good Root4.pairs (triples 311 156) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 156 5 good Root5.pairs (triples 311 156) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 156 6 good Root6.pairs (triples 311 156) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 156 7 good Root7.pairs (triples 311 156) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 156 8 good Root8.pairs (triples 311 156) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 156 9 good Root9.pairs (triples 311 156) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 156 10 good Root10.pairs (triples 311 156) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 156 11 good Root11.pairs (triples 311 156) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 156 12 good Root12.pairs (triples 311 156) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 156 13 good Root13.pairs (triples 311 156) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 156 14 good Root14.pairs (triples 311 156) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 156 15 good Root15.pairs (triples 311 156) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 156 16 good Root16.pairs (triples 311 156) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 156 17 good Root17.pairs (triples 311 156) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 156 18 good Root18.pairs (triples 311 156) pivot=true
      exact Root18.search_ok
    · change ModularSearch.rootCheck 156 19 good Root19.pairs (triples 311 156) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 156 20 good Root20.pairs (triples 311 156) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 156 21 good Root21.pairs (triples 311 156) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 156 22 good Root22.pairs (triples 311 156) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 156 23 good Root23.pairs (triples 311 156) pivot=true
      exact Root23.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 25 good Root25.pairs (triples 311 156) pivot=true
      exact Root25.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 28 good Root28.pairs (triples 311 156) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 156 29 good Root29.pairs (triples 311 156) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 156 30 good Root30.pairs (triples 311 156) pivot=true
      exact Root30.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 32 good Root32.pairs (triples 311 156) pivot=true
      exact Root32.search_ok
    · change ModularSearch.rootCheck 156 33 good Root33.pairs (triples 311 156) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 156 34 good Root34.pairs (triples 311 156) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 156 35 good Root35.pairs (triples 311 156) pivot=true
      exact Root35.search_ok
    · change ModularSearch.rootCheck 156 36 good Root36.pairs (triples 311 156) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 156 37 good Root37.pairs (triples 311 156) pivot=true
      exact Root37.search_ok
    · change ModularSearch.rootCheck 156 38 good Root38.pairs (triples 311 156) pivot=true
      exact Root38.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 40 good Root40.pairs (triples 311 156) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 156 41 good Root41.pairs (triples 311 156) pivot=true
      exact Root41.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 43 good Root43.pairs (triples 311 156) pivot=true
      exact Root43.search_ok
    · change ModularSearch.rootCheck 156 44 good Root44.pairs (triples 311 156) pivot=true
      exact Root44.search_ok
    · change ModularSearch.rootCheck 156 45 good Root45.pairs (triples 311 156) pivot=true
      exact Root45.search_ok
    · change ModularSearch.rootCheck 156 46 good Root46.pairs (triples 311 156) pivot=true
      exact Root46.search_ok
    · change ModularSearch.rootCheck 156 47 good Root47.pairs (triples 311 156) pivot=true
      exact Root47.search_ok
    · change ModularSearch.rootCheck 156 48 good Root48.pairs (triples 311 156) pivot=true
      exact Root48.search_ok
    · change ModularSearch.rootCheck 156 49 good Root49.pairs (triples 311 156) pivot=true
      exact Root49.search_ok
    · change ModularSearch.rootCheck 156 50 good Root50.pairs (triples 311 156) pivot=true
      exact Root50.search_ok
    · change ModularSearch.rootCheck 156 51 good Root51.pairs (triples 311 156) pivot=true
      exact Root51.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 53 good Root53.pairs (triples 311 156) pivot=true
      exact Root53.search_ok
    · change ModularSearch.rootCheck 156 54 good Root54.pairs (triples 311 156) pivot=true
      exact Root54.search_ok
    · change ModularSearch.rootCheck 156 55 good Root55.pairs (triples 311 156) pivot=true
      exact Root55.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 57 good Root57.pairs (triples 311 156) pivot=true
      exact Root57.search_ok
    · change ModularSearch.rootCheck 156 58 good Root58.pairs (triples 311 156) pivot=true
      exact Root58.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 63 good Root63.pairs (triples 311 156) pivot=true
      exact Root63.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 65 good Root65.pairs (triples 311 156) pivot=true
      exact Root65.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 71 good Root71.pairs (triples 311 156) pivot=true
      exact Root71.search_ok
    · change ModularSearch.rootCheck 156 72 good Root72.pairs (triples 311 156) pivot=true
      exact Root72.search_ok
    · change ModularSearch.rootCheck 156 73 good Root73.pairs (triples 311 156) pivot=true
      exact Root73.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 75 good Root75.pairs (triples 311 156) pivot=true
      exact Root75.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 77 good Root77.pairs (triples 311 156) pivot=true
      exact Root77.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 81 good Root81.pairs (triples 311 156) pivot=true
      exact Root81.search_ok
    · change ModularSearch.rootCheck 156 82 good Root82.pairs (triples 311 156) pivot=true
      exact Root82.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 84 good Root84.pairs (triples 311 156) pivot=true
      exact Root84.search_ok
    · change ModularSearch.rootCheck 156 85 good Root85.pairs (triples 311 156) pivot=true
      exact Root85.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 87 good Root87.pairs (triples 311 156) pivot=true
      exact Root87.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 93 good Root93.pairs (triples 311 156) pivot=true
      exact Root93.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 97 good Root97.pairs (triples 311 156) pivot=true
      exact Root97.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 101 good Root101.pairs (triples 311 156) pivot=true
      exact Root101.search_ok
    · change ModularSearch.rootCheck 156 102 good Root102.pairs (triples 311 156) pivot=true
      exact Root102.search_ok
    · change ModularSearch.rootCheck 156 103 good Root103.pairs (triples 311 156) pivot=true
      exact Root103.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 115 good Root115.pairs (triples 311 156) pivot=true
      exact Root115.search_ok
    · change ModularSearch.rootCheck 156 116 good Root116.pairs (triples 311 156) pivot=true
      exact Root116.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 120 good Root120.pairs (triples 311 156) pivot=true
      exact Root120.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 122 good Root122.pairs (triples 311 156) pivot=true
      exact Root122.search_ok
    · change ModularSearch.rootCheck 156 123 good Root123.pairs (triples 311 156) pivot=true
      exact Root123.search_ok
    · change ModularSearch.rootCheck 156 124 good Root124.pairs (triples 311 156) pivot=true
      exact Root124.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 129 good Root129.pairs (triples 311 156) pivot=true
      exact Root129.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 132 good Root132.pairs (triples 311 156) pivot=true
      exact Root132.search_ok
    · change ModularSearch.rootCheck 156 133 good Root133.pairs (triples 311 156) pivot=true
      exact Root133.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 138 good Root138.pairs (triples 311 156) pivot=true
      exact Root138.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 156 145 good Root145.pairs (triples 311 156) pivot=true
      exact Root145.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 311 :=
  sixModularCover_of_normalized 311 (by norm_num)
    (normalizedSixCover_of_sorted 311 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime311
