import LonelyRunner.SixModular179Root77

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime179

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 19 => Root19.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 31 => Root31.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 42 => Root42.pairs x
  | 44 => Root44.pairs x
  | 47 => Root47.pairs x
  | 49 => Root49.pairs x
  | 50 => Root50.pairs x
  | 54 => Root54.pairs x
  | 58 => Root58.pairs x
  | 59 => Root59.pairs x
  | 69 => Root69.pairs x
  | 72 => Root72.pairs x
  | 73 => Root73.pairs x
  | 74 => Root74.pairs x
  | 77 => Root77.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 179 := by
  apply sorted_cover_of_checks 179 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 179 90 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 179 90 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 179 90 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 179 90 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 179 90 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 179 90 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 179 90 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 179 90 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 179 90 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 179 90 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 179 90 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 179 90 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 179 90 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 179 90 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 179 90 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 179 90 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 179 90 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 179 90 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 179 90 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · change pairCheck 179 90 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 179 90 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 179 90 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 179 90 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 179 90 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 179 90 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · change pairCheck 179 90 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 49 inv Root49.pairs=true
      exact Root49.pairs_ok
    · change pairCheck 179 90 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 58 inv Root58.pairs=true
      exact Root58.pairs_ok
    · change pairCheck 179 90 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 69 inv Root69.pairs=true
      exact Root69.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 72 inv Root72.pairs=true
      exact Root72.pairs_ok
    · change pairCheck 179 90 73 inv Root73.pairs=true
      exact Root73.pairs_ok
    · change pairCheck 179 90 74 inv Root74.pairs=true
      exact Root74.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 179 90 77 inv Root77.pairs=true
      exact Root77.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 90 2 good Root2.pairs (triples 179 90) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 90 3 good Root3.pairs (triples 179 90) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 90 4 good Root4.pairs (triples 179 90) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 90 5 good Root5.pairs (triples 179 90) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 90 6 good Root6.pairs (triples 179 90) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 90 7 good Root7.pairs (triples 179 90) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 90 8 good Root8.pairs (triples 179 90) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 90 9 good Root9.pairs (triples 179 90) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 90 10 good Root10.pairs (triples 179 90) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 90 11 good Root11.pairs (triples 179 90) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 90 12 good Root12.pairs (triples 179 90) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 90 13 good Root13.pairs (triples 179 90) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 90 14 good Root14.pairs (triples 179 90) pivot=true
      exact Root14.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 16 good Root16.pairs (triples 179 90) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 90 17 good Root17.pairs (triples 179 90) pivot=true
      exact Root17.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 19 good Root19.pairs (triples 179 90) pivot=true
      exact Root19.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 22 good Root22.pairs (triples 179 90) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 90 23 good Root23.pairs (triples 179 90) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 90 24 good Root24.pairs (triples 179 90) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 90 25 good Root25.pairs (triples 179 90) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 90 26 good Root26.pairs (triples 179 90) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 90 27 good Root27.pairs (triples 179 90) pivot=true
      exact Root27.search_ok
    · change ModularSearch.rootCheck 90 28 good Root28.pairs (triples 179 90) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 90 29 good Root29.pairs (triples 179 90) pivot=true
      exact Root29.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 31 good Root31.pairs (triples 179 90) pivot=true
      exact Root31.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 33 good Root33.pairs (triples 179 90) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 90 34 good Root34.pairs (triples 179 90) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 90 35 good Root35.pairs (triples 179 90) pivot=true
      exact Root35.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 39 good Root39.pairs (triples 179 90) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 90 40 good Root40.pairs (triples 179 90) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 90 41 good Root41.pairs (triples 179 90) pivot=true
      exact Root41.search_ok
    · change ModularSearch.rootCheck 90 42 good Root42.pairs (triples 179 90) pivot=true
      exact Root42.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 44 good Root44.pairs (triples 179 90) pivot=true
      exact Root44.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 47 good Root47.pairs (triples 179 90) pivot=true
      exact Root47.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 49 good Root49.pairs (triples 179 90) pivot=true
      exact Root49.search_ok
    · change ModularSearch.rootCheck 90 50 good Root50.pairs (triples 179 90) pivot=true
      exact Root50.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 54 good Root54.pairs (triples 179 90) pivot=true
      exact Root54.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 58 good Root58.pairs (triples 179 90) pivot=true
      exact Root58.search_ok
    · change ModularSearch.rootCheck 90 59 good Root59.pairs (triples 179 90) pivot=true
      exact Root59.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 69 good Root69.pairs (triples 179 90) pivot=true
      exact Root69.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 72 good Root72.pairs (triples 179 90) pivot=true
      exact Root72.search_ok
    · change ModularSearch.rootCheck 90 73 good Root73.pairs (triples 179 90) pivot=true
      exact Root73.search_ok
    · change ModularSearch.rootCheck 90 74 good Root74.pairs (triples 179 90) pivot=true
      exact Root74.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 90 77 good Root77.pairs (triples 179 90) pivot=true
      exact Root77.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 179 :=
  sixModularCover_of_normalized 179 (by norm_num)
    (normalizedSixCover_of_sorted 179 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime179
