import LonelyRunner.SixModular197Root81

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime197

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 32 => Root32.pairs x
  | 35 => Root35.pairs x
  | 36 => Root36.pairs x
  | 38 => Root38.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 42 => Root42.pairs x
  | 43 => Root43.pairs x
  | 44 => Root44.pairs x
  | 47 => Root47.pairs x
  | 48 => Root48.pairs x
  | 50 => Root50.pairs x
  | 51 => Root51.pairs x
  | 52 => Root52.pairs x
  | 54 => Root54.pairs x
  | 56 => Root56.pairs x
  | 65 => Root65.pairs x
  | 68 => Root68.pairs x
  | 70 => Root70.pairs x
  | 71 => Root71.pairs x
  | 77 => Root77.pairs x
  | 81 => Root81.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 197 := by
  apply sorted_cover_of_checks 197 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 197 99 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 197 99 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 197 99 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 197 99 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 197 99 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 197 99 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 197 99 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 197 99 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 197 99 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 197 99 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 197 99 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 197 99 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 197 99 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 197 99 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 197 99 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 197 99 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 197 99 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 197 99 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 197 99 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 197 99 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 197 99 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 197 99 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 197 99 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 197 99 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · change pairCheck 197 99 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · change pairCheck 197 99 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · change pairCheck 197 99 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 197 99 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · change pairCheck 197 99 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · change pairCheck 197 99 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · change pairCheck 197 99 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · change pairCheck 197 99 51 inv Root51.pairs=true
      exact Root51.pairs_ok
    · change pairCheck 197 99 52 inv Root52.pairs=true
      exact Root52.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 68 inv Root68.pairs=true
      exact Root68.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 70 inv Root70.pairs=true
      exact Root70.pairs_ok
    · change pairCheck 197 99 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 77 inv Root77.pairs=true
      exact Root77.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 197 99 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 99 2 good Root2.pairs (triples 197 99) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 99 3 good Root3.pairs (triples 197 99) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 99 4 good Root4.pairs (triples 197 99) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 99 5 good Root5.pairs (triples 197 99) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 99 6 good Root6.pairs (triples 197 99) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 99 7 good Root7.pairs (triples 197 99) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 99 8 good Root8.pairs (triples 197 99) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 99 9 good Root9.pairs (triples 197 99) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 99 10 good Root10.pairs (triples 197 99) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 99 11 good Root11.pairs (triples 197 99) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 99 12 good Root12.pairs (triples 197 99) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 99 13 good Root13.pairs (triples 197 99) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 99 14 good Root14.pairs (triples 197 99) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 99 15 good Root15.pairs (triples 197 99) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 99 16 good Root16.pairs (triples 197 99) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 99 17 good Root17.pairs (triples 197 99) pivot=true
      exact Root17.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 19 good Root19.pairs (triples 197 99) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 99 20 good Root20.pairs (triples 197 99) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 99 21 good Root21.pairs (triples 197 99) pivot=true
      exact Root21.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 23 good Root23.pairs (triples 197 99) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 99 24 good Root24.pairs (triples 197 99) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 99 25 good Root25.pairs (triples 197 99) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 99 26 good Root26.pairs (triples 197 99) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 99 27 good Root27.pairs (triples 197 99) pivot=true
      exact Root27.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 29 good Root29.pairs (triples 197 99) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 99 30 good Root30.pairs (triples 197 99) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 99 31 good Root31.pairs (triples 197 99) pivot=true
      exact Root31.search_ok
    · change ModularSearch.rootCheck 99 32 good Root32.pairs (triples 197 99) pivot=true
      exact Root32.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 35 good Root35.pairs (triples 197 99) pivot=true
      exact Root35.search_ok
    · change ModularSearch.rootCheck 99 36 good Root36.pairs (triples 197 99) pivot=true
      exact Root36.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 38 good Root38.pairs (triples 197 99) pivot=true
      exact Root38.search_ok
    · change ModularSearch.rootCheck 99 39 good Root39.pairs (triples 197 99) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 99 40 good Root40.pairs (triples 197 99) pivot=true
      exact Root40.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 42 good Root42.pairs (triples 197 99) pivot=true
      exact Root42.search_ok
    · change ModularSearch.rootCheck 99 43 good Root43.pairs (triples 197 99) pivot=true
      exact Root43.search_ok
    · change ModularSearch.rootCheck 99 44 good Root44.pairs (triples 197 99) pivot=true
      exact Root44.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 47 good Root47.pairs (triples 197 99) pivot=true
      exact Root47.search_ok
    · change ModularSearch.rootCheck 99 48 good Root48.pairs (triples 197 99) pivot=true
      exact Root48.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 50 good Root50.pairs (triples 197 99) pivot=true
      exact Root50.search_ok
    · change ModularSearch.rootCheck 99 51 good Root51.pairs (triples 197 99) pivot=true
      exact Root51.search_ok
    · change ModularSearch.rootCheck 99 52 good Root52.pairs (triples 197 99) pivot=true
      exact Root52.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 54 good Root54.pairs (triples 197 99) pivot=true
      exact Root54.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 56 good Root56.pairs (triples 197 99) pivot=true
      exact Root56.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 65 good Root65.pairs (triples 197 99) pivot=true
      exact Root65.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 68 good Root68.pairs (triples 197 99) pivot=true
      exact Root68.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 70 good Root70.pairs (triples 197 99) pivot=true
      exact Root70.search_ok
    · change ModularSearch.rootCheck 99 71 good Root71.pairs (triples 197 99) pivot=true
      exact Root71.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 77 good Root77.pairs (triples 197 99) pivot=true
      exact Root77.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 99 81 good Root81.pairs (triples 197 99) pivot=true
      exact Root81.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 197 :=
  sixModularCover_of_normalized 197 (by norm_num)
    (normalizedSixCover_of_sorted 197 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime197
