import LonelyRunner.SixModular233Root98

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime233

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 27 => Root27.pairs x
  | 30 => Root30.pairs x
  | 32 => Root32.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 38 => Root38.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 42 => Root42.pairs x
  | 43 => Root43.pairs x
  | 44 => Root44.pairs x
  | 45 => Root45.pairs x
  | 46 => Root46.pairs x
  | 47 => Root47.pairs x
  | 52 => Root52.pairs x
  | 54 => Root54.pairs x
  | 55 => Root55.pairs x
  | 56 => Root56.pairs x
  | 57 => Root57.pairs x
  | 59 => Root59.pairs x
  | 60 => Root60.pairs x
  | 62 => Root62.pairs x
  | 64 => Root64.pairs x
  | 67 => Root67.pairs x
  | 71 => Root71.pairs x
  | 73 => Root73.pairs x
  | 74 => Root74.pairs x
  | 75 => Root75.pairs x
  | 77 => Root77.pairs x
  | 84 => Root84.pairs x
  | 89 => Root89.pairs x
  | 95 => Root95.pairs x
  | 98 => Root98.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 233 := by
  apply sorted_cover_of_checks 233 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 233 117 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 233 117 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 233 117 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 233 117 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 233 117 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 233 117 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 233 117 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 233 117 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 233 117 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 233 117 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 233 117 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 233 117 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 233 117 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 233 117 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 233 117 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 233 117 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 233 117 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 233 117 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 233 117 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 233 117 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 233 117 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 233 117 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · change pairCheck 233 117 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 233 117 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 233 117 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · change pairCheck 233 117 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 233 117 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · change pairCheck 233 117 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · change pairCheck 233 117 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · change pairCheck 233 117 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · change pairCheck 233 117 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · change pairCheck 233 117 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · change pairCheck 233 117 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 52 inv Root52.pairs=true
      exact Root52.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · change pairCheck 233 117 55 inv Root55.pairs=true
      exact Root55.pairs_ok
    · change pairCheck 233 117 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · change pairCheck 233 117 57 inv Root57.pairs=true
      exact Root57.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · change pairCheck 233 117 60 inv Root60.pairs=true
      exact Root60.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 62 inv Root62.pairs=true
      exact Root62.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 64 inv Root64.pairs=true
      exact Root64.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 67 inv Root67.pairs=true
      exact Root67.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 73 inv Root73.pairs=true
      exact Root73.pairs_ok
    · change pairCheck 233 117 74 inv Root74.pairs=true
      exact Root74.pairs_ok
    · change pairCheck 233 117 75 inv Root75.pairs=true
      exact Root75.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 77 inv Root77.pairs=true
      exact Root77.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 84 inv Root84.pairs=true
      exact Root84.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 89 inv Root89.pairs=true
      exact Root89.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 95 inv Root95.pairs=true
      exact Root95.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 233 117 98 inv Root98.pairs=true
      exact Root98.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 117 2 good Root2.pairs (triples 233 117) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 117 3 good Root3.pairs (triples 233 117) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 117 4 good Root4.pairs (triples 233 117) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 117 5 good Root5.pairs (triples 233 117) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 117 6 good Root6.pairs (triples 233 117) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 117 7 good Root7.pairs (triples 233 117) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 117 8 good Root8.pairs (triples 233 117) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 117 9 good Root9.pairs (triples 233 117) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 117 10 good Root10.pairs (triples 233 117) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 117 11 good Root11.pairs (triples 233 117) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 117 12 good Root12.pairs (triples 233 117) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 117 13 good Root13.pairs (triples 233 117) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 117 14 good Root14.pairs (triples 233 117) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 117 15 good Root15.pairs (triples 233 117) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 117 16 good Root16.pairs (triples 233 117) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 117 17 good Root17.pairs (triples 233 117) pivot=true
      exact Root17.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 19 good Root19.pairs (triples 233 117) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 117 20 good Root20.pairs (triples 233 117) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 117 21 good Root21.pairs (triples 233 117) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 117 22 good Root22.pairs (triples 233 117) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 117 23 good Root23.pairs (triples 233 117) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 117 24 good Root24.pairs (triples 233 117) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 117 25 good Root25.pairs (triples 233 117) pivot=true
      exact Root25.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 27 good Root27.pairs (triples 233 117) pivot=true
      exact Root27.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 30 good Root30.pairs (triples 233 117) pivot=true
      exact Root30.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 32 good Root32.pairs (triples 233 117) pivot=true
      exact Root32.search_ok
    · change ModularSearch.rootCheck 117 33 good Root33.pairs (triples 233 117) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 117 34 good Root34.pairs (triples 233 117) pivot=true
      exact Root34.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 36 good Root36.pairs (triples 233 117) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 117 37 good Root37.pairs (triples 233 117) pivot=true
      exact Root37.search_ok
    · change ModularSearch.rootCheck 117 38 good Root38.pairs (triples 233 117) pivot=true
      exact Root38.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 40 good Root40.pairs (triples 233 117) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 117 41 good Root41.pairs (triples 233 117) pivot=true
      exact Root41.search_ok
    · change ModularSearch.rootCheck 117 42 good Root42.pairs (triples 233 117) pivot=true
      exact Root42.search_ok
    · change ModularSearch.rootCheck 117 43 good Root43.pairs (triples 233 117) pivot=true
      exact Root43.search_ok
    · change ModularSearch.rootCheck 117 44 good Root44.pairs (triples 233 117) pivot=true
      exact Root44.search_ok
    · change ModularSearch.rootCheck 117 45 good Root45.pairs (triples 233 117) pivot=true
      exact Root45.search_ok
    · change ModularSearch.rootCheck 117 46 good Root46.pairs (triples 233 117) pivot=true
      exact Root46.search_ok
    · change ModularSearch.rootCheck 117 47 good Root47.pairs (triples 233 117) pivot=true
      exact Root47.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 52 good Root52.pairs (triples 233 117) pivot=true
      exact Root52.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 54 good Root54.pairs (triples 233 117) pivot=true
      exact Root54.search_ok
    · change ModularSearch.rootCheck 117 55 good Root55.pairs (triples 233 117) pivot=true
      exact Root55.search_ok
    · change ModularSearch.rootCheck 117 56 good Root56.pairs (triples 233 117) pivot=true
      exact Root56.search_ok
    · change ModularSearch.rootCheck 117 57 good Root57.pairs (triples 233 117) pivot=true
      exact Root57.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 59 good Root59.pairs (triples 233 117) pivot=true
      exact Root59.search_ok
    · change ModularSearch.rootCheck 117 60 good Root60.pairs (triples 233 117) pivot=true
      exact Root60.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 62 good Root62.pairs (triples 233 117) pivot=true
      exact Root62.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 64 good Root64.pairs (triples 233 117) pivot=true
      exact Root64.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 67 good Root67.pairs (triples 233 117) pivot=true
      exact Root67.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 71 good Root71.pairs (triples 233 117) pivot=true
      exact Root71.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 73 good Root73.pairs (triples 233 117) pivot=true
      exact Root73.search_ok
    · change ModularSearch.rootCheck 117 74 good Root74.pairs (triples 233 117) pivot=true
      exact Root74.search_ok
    · change ModularSearch.rootCheck 117 75 good Root75.pairs (triples 233 117) pivot=true
      exact Root75.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 77 good Root77.pairs (triples 233 117) pivot=true
      exact Root77.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 84 good Root84.pairs (triples 233 117) pivot=true
      exact Root84.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 89 good Root89.pairs (triples 233 117) pivot=true
      exact Root89.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 95 good Root95.pairs (triples 233 117) pivot=true
      exact Root95.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 117 98 good Root98.pairs (triples 233 117) pivot=true
      exact Root98.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 233 :=
  sixModularCover_of_normalized 233 (by norm_num)
    (normalizedSixCover_of_sorted 233 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime233
