import LonelyRunner.SixModular331Roots10

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime331

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 31 => Root31.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 38 => Root38.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 42 => Root42.pairs x
  | 43 => Root43.pairs x
  | 44 => Root44.pairs x
  | 45 => Root45.pairs x
  | 47 => Root47.pairs x
  | 48 => Root48.pairs x
  | 50 => Root50.pairs x
  | 52 => Root52.pairs x
  | 54 => Root54.pairs x
  | 56 => Root56.pairs x
  | 57 => Root57.pairs x
  | 58 => Root58.pairs x
  | 59 => Root59.pairs x
  | 60 => Root60.pairs x
  | 64 => Root64.pairs x
  | 67 => Root67.pairs x
  | 68 => Root68.pairs x
  | 74 => Root74.pairs x
  | 75 => Root75.pairs x
  | 76 => Root76.pairs x
  | 78 => Root78.pairs x
  | 79 => Root79.pairs x
  | 80 => Root80.pairs x
  | 81 => Root81.pairs x
  | 82 => Root82.pairs x
  | 86 => Root86.pairs x
  | 87 => Root87.pairs x
  | 89 => Root89.pairs x
  | 90 => Root90.pairs x
  | 93 => Root93.pairs x
  | 95 => Root95.pairs x
  | 96 => Root96.pairs x
  | 98 => Root98.pairs x
  | 99 => Root99.pairs x
  | 102 => Root102.pairs x
  | 105 => Root105.pairs x
  | 106 => Root106.pairs x
  | 111 => Root111.pairs x
  | 112 => Root112.pairs x
  | 115 => Root115.pairs x
  | 116 => Root116.pairs x
  | 123 => Root123.pairs x
  | 125 => Root125.pairs x
  | 126 => Root126.pairs x
  | 129 => Root129.pairs x
  | 132 => Root132.pairs x
  | 144 => Root144.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 331 := by
  apply sorted_cover_of_checks 331 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 331 166 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 331 166 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 331 166 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 331 166 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 331 166 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 331 166 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 331 166 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 331 166 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 331 166 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 331 166 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 331 166 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 331 166 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 331 166 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 331 166 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 331 166 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 331 166 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 331 166 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · change pairCheck 331 166 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 331 166 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 331 166 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 331 166 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 331 166 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 331 166 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 331 166 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · change pairCheck 331 166 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 331 166 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 331 166 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · change pairCheck 331 166 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 331 166 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · change pairCheck 331 166 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 331 166 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · change pairCheck 331 166 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · change pairCheck 331 166 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · change pairCheck 331 166 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · change pairCheck 331 166 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · change pairCheck 331 166 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 52 inv Root52.pairs=true
      exact Root52.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · change pairCheck 331 166 57 inv Root57.pairs=true
      exact Root57.pairs_ok
    · change pairCheck 331 166 58 inv Root58.pairs=true
      exact Root58.pairs_ok
    · change pairCheck 331 166 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · change pairCheck 331 166 60 inv Root60.pairs=true
      exact Root60.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 64 inv Root64.pairs=true
      exact Root64.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 67 inv Root67.pairs=true
      exact Root67.pairs_ok
    · change pairCheck 331 166 68 inv Root68.pairs=true
      exact Root68.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 74 inv Root74.pairs=true
      exact Root74.pairs_ok
    · change pairCheck 331 166 75 inv Root75.pairs=true
      exact Root75.pairs_ok
    · change pairCheck 331 166 76 inv Root76.pairs=true
      exact Root76.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 78 inv Root78.pairs=true
      exact Root78.pairs_ok
    · change pairCheck 331 166 79 inv Root79.pairs=true
      exact Root79.pairs_ok
    · change pairCheck 331 166 80 inv Root80.pairs=true
      exact Root80.pairs_ok
    · change pairCheck 331 166 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · change pairCheck 331 166 82 inv Root82.pairs=true
      exact Root82.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 86 inv Root86.pairs=true
      exact Root86.pairs_ok
    · change pairCheck 331 166 87 inv Root87.pairs=true
      exact Root87.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 89 inv Root89.pairs=true
      exact Root89.pairs_ok
    · change pairCheck 331 166 90 inv Root90.pairs=true
      exact Root90.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 93 inv Root93.pairs=true
      exact Root93.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 95 inv Root95.pairs=true
      exact Root95.pairs_ok
    · change pairCheck 331 166 96 inv Root96.pairs=true
      exact Root96.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 98 inv Root98.pairs=true
      exact Root98.pairs_ok
    · change pairCheck 331 166 99 inv Root99.pairs=true
      exact Root99.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 102 inv Root102.pairs=true
      exact Root102.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 105 inv Root105.pairs=true
      exact Root105.pairs_ok
    · change pairCheck 331 166 106 inv Root106.pairs=true
      exact Root106.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 111 inv Root111.pairs=true
      exact Root111.pairs_ok
    · change pairCheck 331 166 112 inv Root112.pairs=true
      exact Root112.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 115 inv Root115.pairs=true
      exact Root115.pairs_ok
    · change pairCheck 331 166 116 inv Root116.pairs=true
      exact Root116.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 123 inv Root123.pairs=true
      exact Root123.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 125 inv Root125.pairs=true
      exact Root125.pairs_ok
    · change pairCheck 331 166 126 inv Root126.pairs=true
      exact Root126.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 129 inv Root129.pairs=true
      exact Root129.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 132 inv Root132.pairs=true
      exact Root132.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 331 166 144 inv Root144.pairs=true
      exact Root144.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 166 2 good Root2.pairs (triples 331 166) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 166 3 good Root3.pairs (triples 331 166) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 166 4 good Root4.pairs (triples 331 166) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 166 5 good Root5.pairs (triples 331 166) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 166 6 good Root6.pairs (triples 331 166) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 166 7 good Root7.pairs (triples 331 166) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 166 8 good Root8.pairs (triples 331 166) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 166 9 good Root9.pairs (triples 331 166) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 166 10 good Root10.pairs (triples 331 166) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 166 11 good Root11.pairs (triples 331 166) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 166 12 good Root12.pairs (triples 331 166) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 166 13 good Root13.pairs (triples 331 166) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 166 14 good Root14.pairs (triples 331 166) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 166 15 good Root15.pairs (triples 331 166) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 166 16 good Root16.pairs (triples 331 166) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 166 17 good Root17.pairs (triples 331 166) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 166 18 good Root18.pairs (triples 331 166) pivot=true
      exact Root18.search_ok
    · change ModularSearch.rootCheck 166 19 good Root19.pairs (triples 331 166) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 166 20 good Root20.pairs (triples 331 166) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 166 21 good Root21.pairs (triples 331 166) pivot=true
      exact Root21.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 23 good Root23.pairs (triples 331 166) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 166 24 good Root24.pairs (triples 331 166) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 166 25 good Root25.pairs (triples 331 166) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 166 26 good Root26.pairs (triples 331 166) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 166 27 good Root27.pairs (triples 331 166) pivot=true
      exact Root27.search_ok
    · change ModularSearch.rootCheck 166 28 good Root28.pairs (triples 331 166) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 166 29 good Root29.pairs (triples 331 166) pivot=true
      exact Root29.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 31 good Root31.pairs (triples 331 166) pivot=true
      exact Root31.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 34 good Root34.pairs (triples 331 166) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 166 35 good Root35.pairs (triples 331 166) pivot=true
      exact Root35.search_ok
    · change ModularSearch.rootCheck 166 36 good Root36.pairs (triples 331 166) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 166 37 good Root37.pairs (triples 331 166) pivot=true
      exact Root37.search_ok
    · change ModularSearch.rootCheck 166 38 good Root38.pairs (triples 331 166) pivot=true
      exact Root38.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 40 good Root40.pairs (triples 331 166) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 166 41 good Root41.pairs (triples 331 166) pivot=true
      exact Root41.search_ok
    · change ModularSearch.rootCheck 166 42 good Root42.pairs (triples 331 166) pivot=true
      exact Root42.search_ok
    · change ModularSearch.rootCheck 166 43 good Root43.pairs (triples 331 166) pivot=true
      exact Root43.search_ok
    · change ModularSearch.rootCheck 166 44 good Root44.pairs (triples 331 166) pivot=true
      exact Root44.search_ok
    · change ModularSearch.rootCheck 166 45 good Root45.pairs (triples 331 166) pivot=true
      exact Root45.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 47 good Root47.pairs (triples 331 166) pivot=true
      exact Root47.search_ok
    · change ModularSearch.rootCheck 166 48 good Root48.pairs (triples 331 166) pivot=true
      exact Root48.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 50 good Root50.pairs (triples 331 166) pivot=true
      exact Root50.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 52 good Root52.pairs (triples 331 166) pivot=true
      exact Root52.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 54 good Root54.pairs (triples 331 166) pivot=true
      exact Root54.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 56 good Root56.pairs (triples 331 166) pivot=true
      exact Root56.search_ok
    · change ModularSearch.rootCheck 166 57 good Root57.pairs (triples 331 166) pivot=true
      exact Root57.search_ok
    · change ModularSearch.rootCheck 166 58 good Root58.pairs (triples 331 166) pivot=true
      exact Root58.search_ok
    · change ModularSearch.rootCheck 166 59 good Root59.pairs (triples 331 166) pivot=true
      exact Root59.search_ok
    · change ModularSearch.rootCheck 166 60 good Root60.pairs (triples 331 166) pivot=true
      exact Root60.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 64 good Root64.pairs (triples 331 166) pivot=true
      exact Root64.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 67 good Root67.pairs (triples 331 166) pivot=true
      exact Root67.search_ok
    · change ModularSearch.rootCheck 166 68 good Root68.pairs (triples 331 166) pivot=true
      exact Root68.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 74 good Root74.pairs (triples 331 166) pivot=true
      exact Root74.search_ok
    · change ModularSearch.rootCheck 166 75 good Root75.pairs (triples 331 166) pivot=true
      exact Root75.search_ok
    · change ModularSearch.rootCheck 166 76 good Root76.pairs (triples 331 166) pivot=true
      exact Root76.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 78 good Root78.pairs (triples 331 166) pivot=true
      exact Root78.search_ok
    · change ModularSearch.rootCheck 166 79 good Root79.pairs (triples 331 166) pivot=true
      exact Root79.search_ok
    · change ModularSearch.rootCheck 166 80 good Root80.pairs (triples 331 166) pivot=true
      exact Root80.search_ok
    · change ModularSearch.rootCheck 166 81 good Root81.pairs (triples 331 166) pivot=true
      exact Root81.search_ok
    · change ModularSearch.rootCheck 166 82 good Root82.pairs (triples 331 166) pivot=true
      exact Root82.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 86 good Root86.pairs (triples 331 166) pivot=true
      exact Root86.search_ok
    · change ModularSearch.rootCheck 166 87 good Root87.pairs (triples 331 166) pivot=true
      exact Root87.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 89 good Root89.pairs (triples 331 166) pivot=true
      exact Root89.search_ok
    · change ModularSearch.rootCheck 166 90 good Root90.pairs (triples 331 166) pivot=true
      exact Root90.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 93 good Root93.pairs (triples 331 166) pivot=true
      exact Root93.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 95 good Root95.pairs (triples 331 166) pivot=true
      exact Root95.search_ok
    · change ModularSearch.rootCheck 166 96 good Root96.pairs (triples 331 166) pivot=true
      exact Root96.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 98 good Root98.pairs (triples 331 166) pivot=true
      exact Root98.search_ok
    · change ModularSearch.rootCheck 166 99 good Root99.pairs (triples 331 166) pivot=true
      exact Root99.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 102 good Root102.pairs (triples 331 166) pivot=true
      exact Root102.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 105 good Root105.pairs (triples 331 166) pivot=true
      exact Root105.search_ok
    · change ModularSearch.rootCheck 166 106 good Root106.pairs (triples 331 166) pivot=true
      exact Root106.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 111 good Root111.pairs (triples 331 166) pivot=true
      exact Root111.search_ok
    · change ModularSearch.rootCheck 166 112 good Root112.pairs (triples 331 166) pivot=true
      exact Root112.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 115 good Root115.pairs (triples 331 166) pivot=true
      exact Root115.search_ok
    · change ModularSearch.rootCheck 166 116 good Root116.pairs (triples 331 166) pivot=true
      exact Root116.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 123 good Root123.pairs (triples 331 166) pivot=true
      exact Root123.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 125 good Root125.pairs (triples 331 166) pivot=true
      exact Root125.search_ok
    · change ModularSearch.rootCheck 166 126 good Root126.pairs (triples 331 166) pivot=true
      exact Root126.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 129 good Root129.pairs (triples 331 166) pivot=true
      exact Root129.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 132 good Root132.pairs (triples 331 166) pivot=true
      exact Root132.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 166 144 good Root144.pairs (triples 331 166) pivot=true
      exact Root144.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 331 :=
  sixModularCover_of_normalized 331 (by norm_num)
    (normalizedSixCover_of_sorted 331 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime331
