import LonelyRunner.SixModular269Root124

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime269

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 32 => Root32.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 38 => Root38.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 44 => Root44.pairs x
  | 46 => Root46.pairs x
  | 47 => Root47.pairs x
  | 50 => Root50.pairs x
  | 51 => Root51.pairs x
  | 52 => Root52.pairs x
  | 53 => Root53.pairs x
  | 57 => Root57.pairs x
  | 59 => Root59.pairs x
  | 60 => Root60.pairs x
  | 61 => Root61.pairs x
  | 63 => Root63.pairs x
  | 65 => Root65.pairs x
  | 68 => Root68.pairs x
  | 70 => Root70.pairs x
  | 71 => Root71.pairs x
  | 75 => Root75.pairs x
  | 78 => Root78.pairs x
  | 79 => Root79.pairs x
  | 81 => Root81.pairs x
  | 82 => Root82.pairs x
  | 83 => Root83.pairs x
  | 86 => Root86.pairs x
  | 88 => Root88.pairs x
  | 89 => Root89.pairs x
  | 98 => Root98.pairs x
  | 99 => Root99.pairs x
  | 108 => Root108.pairs x
  | 109 => Root109.pairs x
  | 115 => Root115.pairs x
  | 124 => Root124.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 269 := by
  apply sorted_cover_of_checks 269 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 269 135 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 269 135 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 269 135 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 269 135 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 269 135 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 269 135 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 269 135 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 269 135 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 269 135 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 269 135 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 269 135 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 269 135 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 269 135 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 269 135 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 269 135 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 269 135 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 269 135 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 269 135 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 269 135 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 269 135 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 269 135 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 269 135 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 269 135 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 269 135 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · change pairCheck 269 135 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 269 135 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 269 135 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · change pairCheck 269 135 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 269 135 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · change pairCheck 269 135 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · change pairCheck 269 135 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 269 135 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 269 135 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · change pairCheck 269 135 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · change pairCheck 269 135 51 inv Root51.pairs=true
      exact Root51.pairs_ok
    · change pairCheck 269 135 52 inv Root52.pairs=true
      exact Root52.pairs_ok
    · change pairCheck 269 135 53 inv Root53.pairs=true
      exact Root53.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 57 inv Root57.pairs=true
      exact Root57.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · change pairCheck 269 135 60 inv Root60.pairs=true
      exact Root60.pairs_ok
    · change pairCheck 269 135 61 inv Root61.pairs=true
      exact Root61.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 63 inv Root63.pairs=true
      exact Root63.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 68 inv Root68.pairs=true
      exact Root68.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 70 inv Root70.pairs=true
      exact Root70.pairs_ok
    · change pairCheck 269 135 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 75 inv Root75.pairs=true
      exact Root75.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 78 inv Root78.pairs=true
      exact Root78.pairs_ok
    · change pairCheck 269 135 79 inv Root79.pairs=true
      exact Root79.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · change pairCheck 269 135 82 inv Root82.pairs=true
      exact Root82.pairs_ok
    · change pairCheck 269 135 83 inv Root83.pairs=true
      exact Root83.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 86 inv Root86.pairs=true
      exact Root86.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 88 inv Root88.pairs=true
      exact Root88.pairs_ok
    · change pairCheck 269 135 89 inv Root89.pairs=true
      exact Root89.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 98 inv Root98.pairs=true
      exact Root98.pairs_ok
    · change pairCheck 269 135 99 inv Root99.pairs=true
      exact Root99.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 108 inv Root108.pairs=true
      exact Root108.pairs_ok
    · change pairCheck 269 135 109 inv Root109.pairs=true
      exact Root109.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 115 inv Root115.pairs=true
      exact Root115.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 269 135 124 inv Root124.pairs=true
      exact Root124.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 135 2 good Root2.pairs (triples 269 135) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 135 3 good Root3.pairs (triples 269 135) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 135 4 good Root4.pairs (triples 269 135) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 135 5 good Root5.pairs (triples 269 135) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 135 6 good Root6.pairs (triples 269 135) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 135 7 good Root7.pairs (triples 269 135) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 135 8 good Root8.pairs (triples 269 135) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 135 9 good Root9.pairs (triples 269 135) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 135 10 good Root10.pairs (triples 269 135) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 135 11 good Root11.pairs (triples 269 135) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 135 12 good Root12.pairs (triples 269 135) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 135 13 good Root13.pairs (triples 269 135) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 135 14 good Root14.pairs (triples 269 135) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 135 15 good Root15.pairs (triples 269 135) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 135 16 good Root16.pairs (triples 269 135) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 135 17 good Root17.pairs (triples 269 135) pivot=true
      exact Root17.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 19 good Root19.pairs (triples 269 135) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 135 20 good Root20.pairs (triples 269 135) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 135 21 good Root21.pairs (triples 269 135) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 135 22 good Root22.pairs (triples 269 135) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 135 23 good Root23.pairs (triples 269 135) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 135 24 good Root24.pairs (triples 269 135) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 135 25 good Root25.pairs (triples 269 135) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 135 26 good Root26.pairs (triples 269 135) pivot=true
      exact Root26.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 28 good Root28.pairs (triples 269 135) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 135 29 good Root29.pairs (triples 269 135) pivot=true
      exact Root29.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 32 good Root32.pairs (triples 269 135) pivot=true
      exact Root32.search_ok
    · change ModularSearch.rootCheck 135 33 good Root33.pairs (triples 269 135) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 135 34 good Root34.pairs (triples 269 135) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 135 35 good Root35.pairs (triples 269 135) pivot=true
      exact Root35.search_ok
    · change ModularSearch.rootCheck 135 36 good Root36.pairs (triples 269 135) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 135 37 good Root37.pairs (triples 269 135) pivot=true
      exact Root37.search_ok
    · change ModularSearch.rootCheck 135 38 good Root38.pairs (triples 269 135) pivot=true
      exact Root38.search_ok
    · change ModularSearch.rootCheck 135 39 good Root39.pairs (triples 269 135) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 135 40 good Root40.pairs (triples 269 135) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 135 41 good Root41.pairs (triples 269 135) pivot=true
      exact Root41.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 44 good Root44.pairs (triples 269 135) pivot=true
      exact Root44.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 46 good Root46.pairs (triples 269 135) pivot=true
      exact Root46.search_ok
    · change ModularSearch.rootCheck 135 47 good Root47.pairs (triples 269 135) pivot=true
      exact Root47.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 50 good Root50.pairs (triples 269 135) pivot=true
      exact Root50.search_ok
    · change ModularSearch.rootCheck 135 51 good Root51.pairs (triples 269 135) pivot=true
      exact Root51.search_ok
    · change ModularSearch.rootCheck 135 52 good Root52.pairs (triples 269 135) pivot=true
      exact Root52.search_ok
    · change ModularSearch.rootCheck 135 53 good Root53.pairs (triples 269 135) pivot=true
      exact Root53.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 57 good Root57.pairs (triples 269 135) pivot=true
      exact Root57.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 59 good Root59.pairs (triples 269 135) pivot=true
      exact Root59.search_ok
    · change ModularSearch.rootCheck 135 60 good Root60.pairs (triples 269 135) pivot=true
      exact Root60.search_ok
    · change ModularSearch.rootCheck 135 61 good Root61.pairs (triples 269 135) pivot=true
      exact Root61.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 63 good Root63.pairs (triples 269 135) pivot=true
      exact Root63.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 65 good Root65.pairs (triples 269 135) pivot=true
      exact Root65.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 68 good Root68.pairs (triples 269 135) pivot=true
      exact Root68.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 70 good Root70.pairs (triples 269 135) pivot=true
      exact Root70.search_ok
    · change ModularSearch.rootCheck 135 71 good Root71.pairs (triples 269 135) pivot=true
      exact Root71.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 75 good Root75.pairs (triples 269 135) pivot=true
      exact Root75.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 78 good Root78.pairs (triples 269 135) pivot=true
      exact Root78.search_ok
    · change ModularSearch.rootCheck 135 79 good Root79.pairs (triples 269 135) pivot=true
      exact Root79.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 81 good Root81.pairs (triples 269 135) pivot=true
      exact Root81.search_ok
    · change ModularSearch.rootCheck 135 82 good Root82.pairs (triples 269 135) pivot=true
      exact Root82.search_ok
    · change ModularSearch.rootCheck 135 83 good Root83.pairs (triples 269 135) pivot=true
      exact Root83.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 86 good Root86.pairs (triples 269 135) pivot=true
      exact Root86.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 88 good Root88.pairs (triples 269 135) pivot=true
      exact Root88.search_ok
    · change ModularSearch.rootCheck 135 89 good Root89.pairs (triples 269 135) pivot=true
      exact Root89.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 98 good Root98.pairs (triples 269 135) pivot=true
      exact Root98.search_ok
    · change ModularSearch.rootCheck 135 99 good Root99.pairs (triples 269 135) pivot=true
      exact Root99.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 108 good Root108.pairs (triples 269 135) pivot=true
      exact Root108.search_ok
    · change ModularSearch.rootCheck 135 109 good Root109.pairs (triples 269 135) pivot=true
      exact Root109.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 115 good Root115.pairs (triples 269 135) pivot=true
      exact Root115.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 135 124 good Root124.pairs (triples 269 135) pivot=true
      exact Root124.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 269 :=
  sixModularCover_of_normalized 269 (by norm_num)
    (normalizedSixCover_of_sorted 269 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime269
