import LonelyRunner.SixModular229Root107

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime229

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 32 => Root32.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 42 => Root42.pairs x
  | 45 => Root45.pairs x
  | 48 => Root48.pairs x
  | 50 => Root50.pairs x
  | 53 => Root53.pairs x
  | 54 => Root54.pairs x
  | 58 => Root58.pairs x
  | 59 => Root59.pairs x
  | 64 => Root64.pairs x
  | 65 => Root65.pairs x
  | 69 => Root69.pairs x
  | 71 => Root71.pairs x
  | 77 => Root77.pairs x
  | 78 => Root78.pairs x
  | 80 => Root80.pairs x
  | 81 => Root81.pairs x
  | 85 => Root85.pairs x
  | 92 => Root92.pairs x
  | 94 => Root94.pairs x
  | 102 => Root102.pairs x
  | 107 => Root107.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 229 := by
  apply sorted_cover_of_checks 229 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 229 115 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 229 115 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 229 115 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 229 115 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 229 115 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 229 115 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 229 115 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 229 115 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 229 115 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 229 115 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 229 115 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 229 115 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 229 115 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 229 115 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 229 115 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 229 115 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 229 115 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 229 115 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 229 115 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 229 115 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 229 115 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 229 115 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 229 115 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 229 115 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · change pairCheck 229 115 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · change pairCheck 229 115 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 229 115 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 229 115 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · change pairCheck 229 115 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 229 115 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 229 115 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 229 115 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · change pairCheck 229 115 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 53 inv Root53.pairs=true
      exact Root53.pairs_ok
    · change pairCheck 229 115 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 58 inv Root58.pairs=true
      exact Root58.pairs_ok
    · change pairCheck 229 115 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 64 inv Root64.pairs=true
      exact Root64.pairs_ok
    · change pairCheck 229 115 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 69 inv Root69.pairs=true
      exact Root69.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 77 inv Root77.pairs=true
      exact Root77.pairs_ok
    · change pairCheck 229 115 78 inv Root78.pairs=true
      exact Root78.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 80 inv Root80.pairs=true
      exact Root80.pairs_ok
    · change pairCheck 229 115 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 85 inv Root85.pairs=true
      exact Root85.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 92 inv Root92.pairs=true
      exact Root92.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 94 inv Root94.pairs=true
      exact Root94.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 102 inv Root102.pairs=true
      exact Root102.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 229 115 107 inv Root107.pairs=true
      exact Root107.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 115 2 good Root2.pairs (triples 229 115) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 115 3 good Root3.pairs (triples 229 115) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 115 4 good Root4.pairs (triples 229 115) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 115 5 good Root5.pairs (triples 229 115) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 115 6 good Root6.pairs (triples 229 115) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 115 7 good Root7.pairs (triples 229 115) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 115 8 good Root8.pairs (triples 229 115) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 115 9 good Root9.pairs (triples 229 115) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 115 10 good Root10.pairs (triples 229 115) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 115 11 good Root11.pairs (triples 229 115) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 115 12 good Root12.pairs (triples 229 115) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 115 13 good Root13.pairs (triples 229 115) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 115 14 good Root14.pairs (triples 229 115) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 115 15 good Root15.pairs (triples 229 115) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 115 16 good Root16.pairs (triples 229 115) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 115 17 good Root17.pairs (triples 229 115) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 115 18 good Root18.pairs (triples 229 115) pivot=true
      exact Root18.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 20 good Root20.pairs (triples 229 115) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 115 21 good Root21.pairs (triples 229 115) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 115 22 good Root22.pairs (triples 229 115) pivot=true
      exact Root22.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 24 good Root24.pairs (triples 229 115) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 115 25 good Root25.pairs (triples 229 115) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 115 26 good Root26.pairs (triples 229 115) pivot=true
      exact Root26.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 28 good Root28.pairs (triples 229 115) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 115 29 good Root29.pairs (triples 229 115) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 115 30 good Root30.pairs (triples 229 115) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 115 31 good Root31.pairs (triples 229 115) pivot=true
      exact Root31.search_ok
    · change ModularSearch.rootCheck 115 32 good Root32.pairs (triples 229 115) pivot=true
      exact Root32.search_ok
    · change ModularSearch.rootCheck 115 33 good Root33.pairs (triples 229 115) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 115 34 good Root34.pairs (triples 229 115) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 115 35 good Root35.pairs (triples 229 115) pivot=true
      exact Root35.search_ok
    · change ModularSearch.rootCheck 115 36 good Root36.pairs (triples 229 115) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 115 37 good Root37.pairs (triples 229 115) pivot=true
      exact Root37.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 39 good Root39.pairs (triples 229 115) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 115 40 good Root40.pairs (triples 229 115) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 115 41 good Root41.pairs (triples 229 115) pivot=true
      exact Root41.search_ok
    · change ModularSearch.rootCheck 115 42 good Root42.pairs (triples 229 115) pivot=true
      exact Root42.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 45 good Root45.pairs (triples 229 115) pivot=true
      exact Root45.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 48 good Root48.pairs (triples 229 115) pivot=true
      exact Root48.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 50 good Root50.pairs (triples 229 115) pivot=true
      exact Root50.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 53 good Root53.pairs (triples 229 115) pivot=true
      exact Root53.search_ok
    · change ModularSearch.rootCheck 115 54 good Root54.pairs (triples 229 115) pivot=true
      exact Root54.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 58 good Root58.pairs (triples 229 115) pivot=true
      exact Root58.search_ok
    · change ModularSearch.rootCheck 115 59 good Root59.pairs (triples 229 115) pivot=true
      exact Root59.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 64 good Root64.pairs (triples 229 115) pivot=true
      exact Root64.search_ok
    · change ModularSearch.rootCheck 115 65 good Root65.pairs (triples 229 115) pivot=true
      exact Root65.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 69 good Root69.pairs (triples 229 115) pivot=true
      exact Root69.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 71 good Root71.pairs (triples 229 115) pivot=true
      exact Root71.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 77 good Root77.pairs (triples 229 115) pivot=true
      exact Root77.search_ok
    · change ModularSearch.rootCheck 115 78 good Root78.pairs (triples 229 115) pivot=true
      exact Root78.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 80 good Root80.pairs (triples 229 115) pivot=true
      exact Root80.search_ok
    · change ModularSearch.rootCheck 115 81 good Root81.pairs (triples 229 115) pivot=true
      exact Root81.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 85 good Root85.pairs (triples 229 115) pivot=true
      exact Root85.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 92 good Root92.pairs (triples 229 115) pivot=true
      exact Root92.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 94 good Root94.pairs (triples 229 115) pivot=true
      exact Root94.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 102 good Root102.pairs (triples 229 115) pivot=true
      exact Root102.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 115 107 good Root107.pairs (triples 229 115) pivot=true
      exact Root107.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 229 :=
  sixModularCover_of_normalized 229 (by norm_num)
    (normalizedSixCover_of_sorted 229 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime229
