import LonelyRunner.SixModular281Root131

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime281

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 19 => Root19.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 32 => Root32.pairs x
  | 34 => Root34.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 41 => Root41.pairs x
  | 42 => Root42.pairs x
  | 43 => Root43.pairs x
  | 44 => Root44.pairs x
  | 46 => Root46.pairs x
  | 49 => Root49.pairs x
  | 50 => Root50.pairs x
  | 53 => Root53.pairs x
  | 57 => Root57.pairs x
  | 58 => Root58.pairs x
  | 59 => Root59.pairs x
  | 60 => Root60.pairs x
  | 61 => Root61.pairs x
  | 62 => Root62.pairs x
  | 64 => Root64.pairs x
  | 65 => Root65.pairs x
  | 66 => Root66.pairs x
  | 67 => Root67.pairs x
  | 71 => Root71.pairs x
  | 72 => Root72.pairs x
  | 73 => Root73.pairs x
  | 76 => Root76.pairs x
  | 80 => Root80.pairs x
  | 81 => Root81.pairs x
  | 84 => Root84.pairs x
  | 85 => Root85.pairs x
  | 88 => Root88.pairs x
  | 90 => Root90.pairs x
  | 91 => Root91.pairs x
  | 92 => Root92.pairs x
  | 93 => Root93.pairs x
  | 96 => Root96.pairs x
  | 102 => Root102.pairs x
  | 104 => Root104.pairs x
  | 106 => Root106.pairs x
  | 109 => Root109.pairs x
  | 112 => Root112.pairs x
  | 131 => Root131.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 281 := by
  apply sorted_cover_of_checks 281 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 281 141 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 281 141 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 281 141 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 281 141 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 281 141 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 281 141 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 281 141 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 281 141 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 281 141 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 281 141 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 281 141 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 281 141 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 281 141 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 281 141 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 281 141 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 281 141 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 281 141 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · change pairCheck 281 141 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 281 141 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 281 141 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 281 141 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 281 141 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 281 141 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 281 141 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 281 141 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 281 141 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · change pairCheck 281 141 32 inv Root32.pairs=true
      exact Root32.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 281 141 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · change pairCheck 281 141 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · change pairCheck 281 141 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · change pairCheck 281 141 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 49 inv Root49.pairs=true
      exact Root49.pairs_ok
    · change pairCheck 281 141 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 53 inv Root53.pairs=true
      exact Root53.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 57 inv Root57.pairs=true
      exact Root57.pairs_ok
    · change pairCheck 281 141 58 inv Root58.pairs=true
      exact Root58.pairs_ok
    · change pairCheck 281 141 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · change pairCheck 281 141 60 inv Root60.pairs=true
      exact Root60.pairs_ok
    · change pairCheck 281 141 61 inv Root61.pairs=true
      exact Root61.pairs_ok
    · change pairCheck 281 141 62 inv Root62.pairs=true
      exact Root62.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 64 inv Root64.pairs=true
      exact Root64.pairs_ok
    · change pairCheck 281 141 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · change pairCheck 281 141 66 inv Root66.pairs=true
      exact Root66.pairs_ok
    · change pairCheck 281 141 67 inv Root67.pairs=true
      exact Root67.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · change pairCheck 281 141 72 inv Root72.pairs=true
      exact Root72.pairs_ok
    · change pairCheck 281 141 73 inv Root73.pairs=true
      exact Root73.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 76 inv Root76.pairs=true
      exact Root76.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 80 inv Root80.pairs=true
      exact Root80.pairs_ok
    · change pairCheck 281 141 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 84 inv Root84.pairs=true
      exact Root84.pairs_ok
    · change pairCheck 281 141 85 inv Root85.pairs=true
      exact Root85.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 88 inv Root88.pairs=true
      exact Root88.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 90 inv Root90.pairs=true
      exact Root90.pairs_ok
    · change pairCheck 281 141 91 inv Root91.pairs=true
      exact Root91.pairs_ok
    · change pairCheck 281 141 92 inv Root92.pairs=true
      exact Root92.pairs_ok
    · change pairCheck 281 141 93 inv Root93.pairs=true
      exact Root93.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 96 inv Root96.pairs=true
      exact Root96.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 102 inv Root102.pairs=true
      exact Root102.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 104 inv Root104.pairs=true
      exact Root104.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 106 inv Root106.pairs=true
      exact Root106.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 109 inv Root109.pairs=true
      exact Root109.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 112 inv Root112.pairs=true
      exact Root112.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 281 141 131 inv Root131.pairs=true
      exact Root131.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 141 2 good Root2.pairs (triples 281 141) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 141 3 good Root3.pairs (triples 281 141) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 141 4 good Root4.pairs (triples 281 141) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 141 5 good Root5.pairs (triples 281 141) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 141 6 good Root6.pairs (triples 281 141) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 141 7 good Root7.pairs (triples 281 141) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 141 8 good Root8.pairs (triples 281 141) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 141 9 good Root9.pairs (triples 281 141) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 141 10 good Root10.pairs (triples 281 141) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 141 11 good Root11.pairs (triples 281 141) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 141 12 good Root12.pairs (triples 281 141) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 141 13 good Root13.pairs (triples 281 141) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 141 14 good Root14.pairs (triples 281 141) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 141 15 good Root15.pairs (triples 281 141) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 141 16 good Root16.pairs (triples 281 141) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 141 17 good Root17.pairs (triples 281 141) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 141 18 good Root18.pairs (triples 281 141) pivot=true
      exact Root18.search_ok
    · change ModularSearch.rootCheck 141 19 good Root19.pairs (triples 281 141) pivot=true
      exact Root19.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 21 good Root21.pairs (triples 281 141) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 141 22 good Root22.pairs (triples 281 141) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 141 23 good Root23.pairs (triples 281 141) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 141 24 good Root24.pairs (triples 281 141) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 141 25 good Root25.pairs (triples 281 141) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 141 26 good Root26.pairs (triples 281 141) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 141 27 good Root27.pairs (triples 281 141) pivot=true
      exact Root27.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 29 good Root29.pairs (triples 281 141) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 141 30 good Root30.pairs (triples 281 141) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 141 31 good Root31.pairs (triples 281 141) pivot=true
      exact Root31.search_ok
    · change ModularSearch.rootCheck 141 32 good Root32.pairs (triples 281 141) pivot=true
      exact Root32.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 34 good Root34.pairs (triples 281 141) pivot=true
      exact Root34.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 36 good Root36.pairs (triples 281 141) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 141 37 good Root37.pairs (triples 281 141) pivot=true
      exact Root37.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 41 good Root41.pairs (triples 281 141) pivot=true
      exact Root41.search_ok
    · change ModularSearch.rootCheck 141 42 good Root42.pairs (triples 281 141) pivot=true
      exact Root42.search_ok
    · change ModularSearch.rootCheck 141 43 good Root43.pairs (triples 281 141) pivot=true
      exact Root43.search_ok
    · change ModularSearch.rootCheck 141 44 good Root44.pairs (triples 281 141) pivot=true
      exact Root44.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 46 good Root46.pairs (triples 281 141) pivot=true
      exact Root46.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 49 good Root49.pairs (triples 281 141) pivot=true
      exact Root49.search_ok
    · change ModularSearch.rootCheck 141 50 good Root50.pairs (triples 281 141) pivot=true
      exact Root50.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 53 good Root53.pairs (triples 281 141) pivot=true
      exact Root53.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 57 good Root57.pairs (triples 281 141) pivot=true
      exact Root57.search_ok
    · change ModularSearch.rootCheck 141 58 good Root58.pairs (triples 281 141) pivot=true
      exact Root58.search_ok
    · change ModularSearch.rootCheck 141 59 good Root59.pairs (triples 281 141) pivot=true
      exact Root59.search_ok
    · change ModularSearch.rootCheck 141 60 good Root60.pairs (triples 281 141) pivot=true
      exact Root60.search_ok
    · change ModularSearch.rootCheck 141 61 good Root61.pairs (triples 281 141) pivot=true
      exact Root61.search_ok
    · change ModularSearch.rootCheck 141 62 good Root62.pairs (triples 281 141) pivot=true
      exact Root62.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 64 good Root64.pairs (triples 281 141) pivot=true
      exact Root64.search_ok
    · change ModularSearch.rootCheck 141 65 good Root65.pairs (triples 281 141) pivot=true
      exact Root65.search_ok
    · change ModularSearch.rootCheck 141 66 good Root66.pairs (triples 281 141) pivot=true
      exact Root66.search_ok
    · change ModularSearch.rootCheck 141 67 good Root67.pairs (triples 281 141) pivot=true
      exact Root67.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 71 good Root71.pairs (triples 281 141) pivot=true
      exact Root71.search_ok
    · change ModularSearch.rootCheck 141 72 good Root72.pairs (triples 281 141) pivot=true
      exact Root72.search_ok
    · change ModularSearch.rootCheck 141 73 good Root73.pairs (triples 281 141) pivot=true
      exact Root73.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 76 good Root76.pairs (triples 281 141) pivot=true
      exact Root76.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 80 good Root80.pairs (triples 281 141) pivot=true
      exact Root80.search_ok
    · change ModularSearch.rootCheck 141 81 good Root81.pairs (triples 281 141) pivot=true
      exact Root81.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 84 good Root84.pairs (triples 281 141) pivot=true
      exact Root84.search_ok
    · change ModularSearch.rootCheck 141 85 good Root85.pairs (triples 281 141) pivot=true
      exact Root85.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 88 good Root88.pairs (triples 281 141) pivot=true
      exact Root88.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 90 good Root90.pairs (triples 281 141) pivot=true
      exact Root90.search_ok
    · change ModularSearch.rootCheck 141 91 good Root91.pairs (triples 281 141) pivot=true
      exact Root91.search_ok
    · change ModularSearch.rootCheck 141 92 good Root92.pairs (triples 281 141) pivot=true
      exact Root92.search_ok
    · change ModularSearch.rootCheck 141 93 good Root93.pairs (triples 281 141) pivot=true
      exact Root93.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 96 good Root96.pairs (triples 281 141) pivot=true
      exact Root96.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 102 good Root102.pairs (triples 281 141) pivot=true
      exact Root102.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 104 good Root104.pairs (triples 281 141) pivot=true
      exact Root104.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 106 good Root106.pairs (triples 281 141) pivot=true
      exact Root106.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 109 good Root109.pairs (triples 281 141) pivot=true
      exact Root109.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 112 good Root112.pairs (triples 281 141) pivot=true
      exact Root112.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 141 131 good Root131.pairs (triples 281 141) pivot=true
      exact Root131.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 281 :=
  sixModularCover_of_normalized 281 (by norm_num)
    (normalizedSixCover_of_sorted 281 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime281
