import LonelyRunner.SixModular277Root128

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime277

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 27 => Root27.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 35 => Root35.pairs x
  | 36 => Root36.pairs x
  | 38 => Root38.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 43 => Root43.pairs x
  | 44 => Root44.pairs x
  | 45 => Root45.pairs x
  | 47 => Root47.pairs x
  | 48 => Root48.pairs x
  | 49 => Root49.pairs x
  | 50 => Root50.pairs x
  | 53 => Root53.pairs x
  | 54 => Root54.pairs x
  | 55 => Root55.pairs x
  | 56 => Root56.pairs x
  | 59 => Root59.pairs x
  | 60 => Root60.pairs x
  | 61 => Root61.pairs x
  | 62 => Root62.pairs x
  | 65 => Root65.pairs x
  | 68 => Root68.pairs x
  | 70 => Root70.pairs x
  | 73 => Root73.pairs x
  | 74 => Root74.pairs x
  | 76 => Root76.pairs x
  | 78 => Root78.pairs x
  | 81 => Root81.pairs x
  | 82 => Root82.pairs x
  | 84 => Root84.pairs x
  | 85 => Root85.pairs x
  | 87 => Root87.pairs x
  | 93 => Root93.pairs x
  | 96 => Root96.pairs x
  | 105 => Root105.pairs x
  | 116 => Root116.pairs x
  | 119 => Root119.pairs x
  | 128 => Root128.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 277 := by
  apply sorted_cover_of_checks 277 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 277 139 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 277 139 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 277 139 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 277 139 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 277 139 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 277 139 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 277 139 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 277 139 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 277 139 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 277 139 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 277 139 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 277 139 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 277 139 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 277 139 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 277 139 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 277 139 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 277 139 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · change pairCheck 277 139 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 277 139 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 277 139 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 277 139 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 277 139 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 277 139 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · change pairCheck 277 139 27 inv Root27.pairs=true
      exact Root27.pairs_ok
    · change pairCheck 277 139 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 277 139 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 277 139 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 277 139 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 277 139 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · change pairCheck 277 139 35 inv Root35.pairs=true
      exact Root35.pairs_ok
    · change pairCheck 277 139 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · change pairCheck 277 139 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 277 139 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 43 inv Root43.pairs=true
      exact Root43.pairs_ok
    · change pairCheck 277 139 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · change pairCheck 277 139 45 inv Root45.pairs=true
      exact Root45.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · change pairCheck 277 139 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · change pairCheck 277 139 49 inv Root49.pairs=true
      exact Root49.pairs_ok
    · change pairCheck 277 139 50 inv Root50.pairs=true
      exact Root50.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 53 inv Root53.pairs=true
      exact Root53.pairs_ok
    · change pairCheck 277 139 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · change pairCheck 277 139 55 inv Root55.pairs=true
      exact Root55.pairs_ok
    · change pairCheck 277 139 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · change pairCheck 277 139 60 inv Root60.pairs=true
      exact Root60.pairs_ok
    · change pairCheck 277 139 61 inv Root61.pairs=true
      exact Root61.pairs_ok
    · change pairCheck 277 139 62 inv Root62.pairs=true
      exact Root62.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 68 inv Root68.pairs=true
      exact Root68.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 70 inv Root70.pairs=true
      exact Root70.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 73 inv Root73.pairs=true
      exact Root73.pairs_ok
    · change pairCheck 277 139 74 inv Root74.pairs=true
      exact Root74.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 76 inv Root76.pairs=true
      exact Root76.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 78 inv Root78.pairs=true
      exact Root78.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · change pairCheck 277 139 82 inv Root82.pairs=true
      exact Root82.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 84 inv Root84.pairs=true
      exact Root84.pairs_ok
    · change pairCheck 277 139 85 inv Root85.pairs=true
      exact Root85.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 87 inv Root87.pairs=true
      exact Root87.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 93 inv Root93.pairs=true
      exact Root93.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 96 inv Root96.pairs=true
      exact Root96.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 105 inv Root105.pairs=true
      exact Root105.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 116 inv Root116.pairs=true
      exact Root116.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 119 inv Root119.pairs=true
      exact Root119.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 277 139 128 inv Root128.pairs=true
      exact Root128.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 139 2 good Root2.pairs (triples 277 139) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 139 3 good Root3.pairs (triples 277 139) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 139 4 good Root4.pairs (triples 277 139) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 139 5 good Root5.pairs (triples 277 139) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 139 6 good Root6.pairs (triples 277 139) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 139 7 good Root7.pairs (triples 277 139) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 139 8 good Root8.pairs (triples 277 139) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 139 9 good Root9.pairs (triples 277 139) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 139 10 good Root10.pairs (triples 277 139) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 139 11 good Root11.pairs (triples 277 139) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 139 12 good Root12.pairs (triples 277 139) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 139 13 good Root13.pairs (triples 277 139) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 139 14 good Root14.pairs (triples 277 139) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 139 15 good Root15.pairs (triples 277 139) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 139 16 good Root16.pairs (triples 277 139) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 139 17 good Root17.pairs (triples 277 139) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 139 18 good Root18.pairs (triples 277 139) pivot=true
      exact Root18.search_ok
    · change ModularSearch.rootCheck 139 19 good Root19.pairs (triples 277 139) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 139 20 good Root20.pairs (triples 277 139) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 139 21 good Root21.pairs (triples 277 139) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 139 22 good Root22.pairs (triples 277 139) pivot=true
      exact Root22.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 24 good Root24.pairs (triples 277 139) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 139 25 good Root25.pairs (triples 277 139) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 139 26 good Root26.pairs (triples 277 139) pivot=true
      exact Root26.search_ok
    · change ModularSearch.rootCheck 139 27 good Root27.pairs (triples 277 139) pivot=true
      exact Root27.search_ok
    · change ModularSearch.rootCheck 139 28 good Root28.pairs (triples 277 139) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 139 29 good Root29.pairs (triples 277 139) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 139 30 good Root30.pairs (triples 277 139) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 139 31 good Root31.pairs (triples 277 139) pivot=true
      exact Root31.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 33 good Root33.pairs (triples 277 139) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 139 34 good Root34.pairs (triples 277 139) pivot=true
      exact Root34.search_ok
    · change ModularSearch.rootCheck 139 35 good Root35.pairs (triples 277 139) pivot=true
      exact Root35.search_ok
    · change ModularSearch.rootCheck 139 36 good Root36.pairs (triples 277 139) pivot=true
      exact Root36.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 38 good Root38.pairs (triples 277 139) pivot=true
      exact Root38.search_ok
    · change ModularSearch.rootCheck 139 39 good Root39.pairs (triples 277 139) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 139 40 good Root40.pairs (triples 277 139) pivot=true
      exact Root40.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 43 good Root43.pairs (triples 277 139) pivot=true
      exact Root43.search_ok
    · change ModularSearch.rootCheck 139 44 good Root44.pairs (triples 277 139) pivot=true
      exact Root44.search_ok
    · change ModularSearch.rootCheck 139 45 good Root45.pairs (triples 277 139) pivot=true
      exact Root45.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 47 good Root47.pairs (triples 277 139) pivot=true
      exact Root47.search_ok
    · change ModularSearch.rootCheck 139 48 good Root48.pairs (triples 277 139) pivot=true
      exact Root48.search_ok
    · change ModularSearch.rootCheck 139 49 good Root49.pairs (triples 277 139) pivot=true
      exact Root49.search_ok
    · change ModularSearch.rootCheck 139 50 good Root50.pairs (triples 277 139) pivot=true
      exact Root50.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 53 good Root53.pairs (triples 277 139) pivot=true
      exact Root53.search_ok
    · change ModularSearch.rootCheck 139 54 good Root54.pairs (triples 277 139) pivot=true
      exact Root54.search_ok
    · change ModularSearch.rootCheck 139 55 good Root55.pairs (triples 277 139) pivot=true
      exact Root55.search_ok
    · change ModularSearch.rootCheck 139 56 good Root56.pairs (triples 277 139) pivot=true
      exact Root56.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 59 good Root59.pairs (triples 277 139) pivot=true
      exact Root59.search_ok
    · change ModularSearch.rootCheck 139 60 good Root60.pairs (triples 277 139) pivot=true
      exact Root60.search_ok
    · change ModularSearch.rootCheck 139 61 good Root61.pairs (triples 277 139) pivot=true
      exact Root61.search_ok
    · change ModularSearch.rootCheck 139 62 good Root62.pairs (triples 277 139) pivot=true
      exact Root62.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 65 good Root65.pairs (triples 277 139) pivot=true
      exact Root65.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 68 good Root68.pairs (triples 277 139) pivot=true
      exact Root68.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 70 good Root70.pairs (triples 277 139) pivot=true
      exact Root70.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 73 good Root73.pairs (triples 277 139) pivot=true
      exact Root73.search_ok
    · change ModularSearch.rootCheck 139 74 good Root74.pairs (triples 277 139) pivot=true
      exact Root74.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 76 good Root76.pairs (triples 277 139) pivot=true
      exact Root76.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 78 good Root78.pairs (triples 277 139) pivot=true
      exact Root78.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 81 good Root81.pairs (triples 277 139) pivot=true
      exact Root81.search_ok
    · change ModularSearch.rootCheck 139 82 good Root82.pairs (triples 277 139) pivot=true
      exact Root82.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 84 good Root84.pairs (triples 277 139) pivot=true
      exact Root84.search_ok
    · change ModularSearch.rootCheck 139 85 good Root85.pairs (triples 277 139) pivot=true
      exact Root85.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 87 good Root87.pairs (triples 277 139) pivot=true
      exact Root87.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 93 good Root93.pairs (triples 277 139) pivot=true
      exact Root93.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 96 good Root96.pairs (triples 277 139) pivot=true
      exact Root96.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 105 good Root105.pairs (triples 277 139) pivot=true
      exact Root105.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 116 good Root116.pairs (triples 277 139) pivot=true
      exact Root116.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 119 good Root119.pairs (triples 277 139) pivot=true
      exact Root119.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 139 128 good Root128.pairs (triples 277 139) pivot=true
      exact Root128.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 277 :=
  sixModularCover_of_normalized 277 (by norm_num)
    (normalizedSixCover_of_sorted 277 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime277
