import LonelyRunner.SixModular257Root117

-- Generated by scripts/generate_six_modular_lean.py.
namespace LonelyRunner.SixModularSearch.Prime257

def pairs (r x : ℕ) : ℕ :=
  match r with
  | 2 => Root2.pairs x
  | 3 => Root3.pairs x
  | 4 => Root4.pairs x
  | 5 => Root5.pairs x
  | 6 => Root6.pairs x
  | 7 => Root7.pairs x
  | 8 => Root8.pairs x
  | 9 => Root9.pairs x
  | 10 => Root10.pairs x
  | 11 => Root11.pairs x
  | 12 => Root12.pairs x
  | 13 => Root13.pairs x
  | 14 => Root14.pairs x
  | 15 => Root15.pairs x
  | 16 => Root16.pairs x
  | 17 => Root17.pairs x
  | 18 => Root18.pairs x
  | 19 => Root19.pairs x
  | 20 => Root20.pairs x
  | 21 => Root21.pairs x
  | 22 => Root22.pairs x
  | 23 => Root23.pairs x
  | 24 => Root24.pairs x
  | 25 => Root25.pairs x
  | 26 => Root26.pairs x
  | 28 => Root28.pairs x
  | 29 => Root29.pairs x
  | 30 => Root30.pairs x
  | 31 => Root31.pairs x
  | 33 => Root33.pairs x
  | 34 => Root34.pairs x
  | 36 => Root36.pairs x
  | 37 => Root37.pairs x
  | 38 => Root38.pairs x
  | 39 => Root39.pairs x
  | 40 => Root40.pairs x
  | 41 => Root41.pairs x
  | 42 => Root42.pairs x
  | 44 => Root44.pairs x
  | 46 => Root46.pairs x
  | 47 => Root47.pairs x
  | 48 => Root48.pairs x
  | 51 => Root51.pairs x
  | 52 => Root52.pairs x
  | 53 => Root53.pairs x
  | 54 => Root54.pairs x
  | 56 => Root56.pairs x
  | 59 => Root59.pairs x
  | 63 => Root63.pairs x
  | 65 => Root65.pairs x
  | 66 => Root66.pairs x
  | 69 => Root69.pairs x
  | 71 => Root71.pairs x
  | 73 => Root73.pairs x
  | 80 => Root80.pairs x
  | 81 => Root81.pairs x
  | 83 => Root83.pairs x
  | 85 => Root85.pairs x
  | 93 => Root93.pairs x
  | 98 => Root98.pairs x
  | 99 => Root99.pairs x
  | 113 => Root113.pairs x
  | 114 => Root114.pairs x
  | 117 => Root117.pairs x
  | _ => 0

theorem sorted_cover : SortedSixCover 257 := by
  apply sorted_cover_of_checks 257 (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
  · intro r hr2 hrw hrmin
    interval_cases r
    · change pairCheck 257 129 2 inv Root2.pairs=true
      exact Root2.pairs_ok
    · change pairCheck 257 129 3 inv Root3.pairs=true
      exact Root3.pairs_ok
    · change pairCheck 257 129 4 inv Root4.pairs=true
      exact Root4.pairs_ok
    · change pairCheck 257 129 5 inv Root5.pairs=true
      exact Root5.pairs_ok
    · change pairCheck 257 129 6 inv Root6.pairs=true
      exact Root6.pairs_ok
    · change pairCheck 257 129 7 inv Root7.pairs=true
      exact Root7.pairs_ok
    · change pairCheck 257 129 8 inv Root8.pairs=true
      exact Root8.pairs_ok
    · change pairCheck 257 129 9 inv Root9.pairs=true
      exact Root9.pairs_ok
    · change pairCheck 257 129 10 inv Root10.pairs=true
      exact Root10.pairs_ok
    · change pairCheck 257 129 11 inv Root11.pairs=true
      exact Root11.pairs_ok
    · change pairCheck 257 129 12 inv Root12.pairs=true
      exact Root12.pairs_ok
    · change pairCheck 257 129 13 inv Root13.pairs=true
      exact Root13.pairs_ok
    · change pairCheck 257 129 14 inv Root14.pairs=true
      exact Root14.pairs_ok
    · change pairCheck 257 129 15 inv Root15.pairs=true
      exact Root15.pairs_ok
    · change pairCheck 257 129 16 inv Root16.pairs=true
      exact Root16.pairs_ok
    · change pairCheck 257 129 17 inv Root17.pairs=true
      exact Root17.pairs_ok
    · change pairCheck 257 129 18 inv Root18.pairs=true
      exact Root18.pairs_ok
    · change pairCheck 257 129 19 inv Root19.pairs=true
      exact Root19.pairs_ok
    · change pairCheck 257 129 20 inv Root20.pairs=true
      exact Root20.pairs_ok
    · change pairCheck 257 129 21 inv Root21.pairs=true
      exact Root21.pairs_ok
    · change pairCheck 257 129 22 inv Root22.pairs=true
      exact Root22.pairs_ok
    · change pairCheck 257 129 23 inv Root23.pairs=true
      exact Root23.pairs_ok
    · change pairCheck 257 129 24 inv Root24.pairs=true
      exact Root24.pairs_ok
    · change pairCheck 257 129 25 inv Root25.pairs=true
      exact Root25.pairs_ok
    · change pairCheck 257 129 26 inv Root26.pairs=true
      exact Root26.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 28 inv Root28.pairs=true
      exact Root28.pairs_ok
    · change pairCheck 257 129 29 inv Root29.pairs=true
      exact Root29.pairs_ok
    · change pairCheck 257 129 30 inv Root30.pairs=true
      exact Root30.pairs_ok
    · change pairCheck 257 129 31 inv Root31.pairs=true
      exact Root31.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 33 inv Root33.pairs=true
      exact Root33.pairs_ok
    · change pairCheck 257 129 34 inv Root34.pairs=true
      exact Root34.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 36 inv Root36.pairs=true
      exact Root36.pairs_ok
    · change pairCheck 257 129 37 inv Root37.pairs=true
      exact Root37.pairs_ok
    · change pairCheck 257 129 38 inv Root38.pairs=true
      exact Root38.pairs_ok
    · change pairCheck 257 129 39 inv Root39.pairs=true
      exact Root39.pairs_ok
    · change pairCheck 257 129 40 inv Root40.pairs=true
      exact Root40.pairs_ok
    · change pairCheck 257 129 41 inv Root41.pairs=true
      exact Root41.pairs_ok
    · change pairCheck 257 129 42 inv Root42.pairs=true
      exact Root42.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 44 inv Root44.pairs=true
      exact Root44.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 46 inv Root46.pairs=true
      exact Root46.pairs_ok
    · change pairCheck 257 129 47 inv Root47.pairs=true
      exact Root47.pairs_ok
    · change pairCheck 257 129 48 inv Root48.pairs=true
      exact Root48.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 51 inv Root51.pairs=true
      exact Root51.pairs_ok
    · change pairCheck 257 129 52 inv Root52.pairs=true
      exact Root52.pairs_ok
    · change pairCheck 257 129 53 inv Root53.pairs=true
      exact Root53.pairs_ok
    · change pairCheck 257 129 54 inv Root54.pairs=true
      exact Root54.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 56 inv Root56.pairs=true
      exact Root56.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 59 inv Root59.pairs=true
      exact Root59.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 63 inv Root63.pairs=true
      exact Root63.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 65 inv Root65.pairs=true
      exact Root65.pairs_ok
    · change pairCheck 257 129 66 inv Root66.pairs=true
      exact Root66.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 69 inv Root69.pairs=true
      exact Root69.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 71 inv Root71.pairs=true
      exact Root71.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 73 inv Root73.pairs=true
      exact Root73.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 80 inv Root80.pairs=true
      exact Root80.pairs_ok
    · change pairCheck 257 129 81 inv Root81.pairs=true
      exact Root81.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 83 inv Root83.pairs=true
      exact Root83.pairs_ok
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 85 inv Root85.pairs=true
      exact Root85.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 93 inv Root93.pairs=true
      exact Root93.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 98 inv Root98.pairs=true
      exact Root98.pairs_ok
    · change pairCheck 257 129 99 inv Root99.pairs=true
      exact Root99.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 113 inv Root113.pairs=true
      exact Root113.pairs_ok
    · change pairCheck 257 129 114 inv Root114.pairs=true
      exact Root114.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change pairCheck 257 129 117 inv Root117.pairs=true
      exact Root117.pairs_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
  · intro r hr2 hrw hrmin
    interval_cases r
    · change ModularSearch.rootCheck 129 2 good Root2.pairs (triples 257 129) pivot=true
      exact Root2.search_ok
    · change ModularSearch.rootCheck 129 3 good Root3.pairs (triples 257 129) pivot=true
      exact Root3.search_ok
    · change ModularSearch.rootCheck 129 4 good Root4.pairs (triples 257 129) pivot=true
      exact Root4.search_ok
    · change ModularSearch.rootCheck 129 5 good Root5.pairs (triples 257 129) pivot=true
      exact Root5.search_ok
    · change ModularSearch.rootCheck 129 6 good Root6.pairs (triples 257 129) pivot=true
      exact Root6.search_ok
    · change ModularSearch.rootCheck 129 7 good Root7.pairs (triples 257 129) pivot=true
      exact Root7.search_ok
    · change ModularSearch.rootCheck 129 8 good Root8.pairs (triples 257 129) pivot=true
      exact Root8.search_ok
    · change ModularSearch.rootCheck 129 9 good Root9.pairs (triples 257 129) pivot=true
      exact Root9.search_ok
    · change ModularSearch.rootCheck 129 10 good Root10.pairs (triples 257 129) pivot=true
      exact Root10.search_ok
    · change ModularSearch.rootCheck 129 11 good Root11.pairs (triples 257 129) pivot=true
      exact Root11.search_ok
    · change ModularSearch.rootCheck 129 12 good Root12.pairs (triples 257 129) pivot=true
      exact Root12.search_ok
    · change ModularSearch.rootCheck 129 13 good Root13.pairs (triples 257 129) pivot=true
      exact Root13.search_ok
    · change ModularSearch.rootCheck 129 14 good Root14.pairs (triples 257 129) pivot=true
      exact Root14.search_ok
    · change ModularSearch.rootCheck 129 15 good Root15.pairs (triples 257 129) pivot=true
      exact Root15.search_ok
    · change ModularSearch.rootCheck 129 16 good Root16.pairs (triples 257 129) pivot=true
      exact Root16.search_ok
    · change ModularSearch.rootCheck 129 17 good Root17.pairs (triples 257 129) pivot=true
      exact Root17.search_ok
    · change ModularSearch.rootCheck 129 18 good Root18.pairs (triples 257 129) pivot=true
      exact Root18.search_ok
    · change ModularSearch.rootCheck 129 19 good Root19.pairs (triples 257 129) pivot=true
      exact Root19.search_ok
    · change ModularSearch.rootCheck 129 20 good Root20.pairs (triples 257 129) pivot=true
      exact Root20.search_ok
    · change ModularSearch.rootCheck 129 21 good Root21.pairs (triples 257 129) pivot=true
      exact Root21.search_ok
    · change ModularSearch.rootCheck 129 22 good Root22.pairs (triples 257 129) pivot=true
      exact Root22.search_ok
    · change ModularSearch.rootCheck 129 23 good Root23.pairs (triples 257 129) pivot=true
      exact Root23.search_ok
    · change ModularSearch.rootCheck 129 24 good Root24.pairs (triples 257 129) pivot=true
      exact Root24.search_ok
    · change ModularSearch.rootCheck 129 25 good Root25.pairs (triples 257 129) pivot=true
      exact Root25.search_ok
    · change ModularSearch.rootCheck 129 26 good Root26.pairs (triples 257 129) pivot=true
      exact Root26.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 28 good Root28.pairs (triples 257 129) pivot=true
      exact Root28.search_ok
    · change ModularSearch.rootCheck 129 29 good Root29.pairs (triples 257 129) pivot=true
      exact Root29.search_ok
    · change ModularSearch.rootCheck 129 30 good Root30.pairs (triples 257 129) pivot=true
      exact Root30.search_ok
    · change ModularSearch.rootCheck 129 31 good Root31.pairs (triples 257 129) pivot=true
      exact Root31.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 33 good Root33.pairs (triples 257 129) pivot=true
      exact Root33.search_ok
    · change ModularSearch.rootCheck 129 34 good Root34.pairs (triples 257 129) pivot=true
      exact Root34.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 36 good Root36.pairs (triples 257 129) pivot=true
      exact Root36.search_ok
    · change ModularSearch.rootCheck 129 37 good Root37.pairs (triples 257 129) pivot=true
      exact Root37.search_ok
    · change ModularSearch.rootCheck 129 38 good Root38.pairs (triples 257 129) pivot=true
      exact Root38.search_ok
    · change ModularSearch.rootCheck 129 39 good Root39.pairs (triples 257 129) pivot=true
      exact Root39.search_ok
    · change ModularSearch.rootCheck 129 40 good Root40.pairs (triples 257 129) pivot=true
      exact Root40.search_ok
    · change ModularSearch.rootCheck 129 41 good Root41.pairs (triples 257 129) pivot=true
      exact Root41.search_ok
    · change ModularSearch.rootCheck 129 42 good Root42.pairs (triples 257 129) pivot=true
      exact Root42.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 44 good Root44.pairs (triples 257 129) pivot=true
      exact Root44.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 46 good Root46.pairs (triples 257 129) pivot=true
      exact Root46.search_ok
    · change ModularSearch.rootCheck 129 47 good Root47.pairs (triples 257 129) pivot=true
      exact Root47.search_ok
    · change ModularSearch.rootCheck 129 48 good Root48.pairs (triples 257 129) pivot=true
      exact Root48.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 51 good Root51.pairs (triples 257 129) pivot=true
      exact Root51.search_ok
    · change ModularSearch.rootCheck 129 52 good Root52.pairs (triples 257 129) pivot=true
      exact Root52.search_ok
    · change ModularSearch.rootCheck 129 53 good Root53.pairs (triples 257 129) pivot=true
      exact Root53.search_ok
    · change ModularSearch.rootCheck 129 54 good Root54.pairs (triples 257 129) pivot=true
      exact Root54.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 56 good Root56.pairs (triples 257 129) pivot=true
      exact Root56.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 59 good Root59.pairs (triples 257 129) pivot=true
      exact Root59.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 63 good Root63.pairs (triples 257 129) pivot=true
      exact Root63.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 65 good Root65.pairs (triples 257 129) pivot=true
      exact Root65.search_ok
    · change ModularSearch.rootCheck 129 66 good Root66.pairs (triples 257 129) pivot=true
      exact Root66.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 69 good Root69.pairs (triples 257 129) pivot=true
      exact Root69.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 71 good Root71.pairs (triples 257 129) pivot=true
      exact Root71.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 73 good Root73.pairs (triples 257 129) pivot=true
      exact Root73.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 80 good Root80.pairs (triples 257 129) pivot=true
      exact Root80.search_ok
    · change ModularSearch.rootCheck 129 81 good Root81.pairs (triples 257 129) pivot=true
      exact Root81.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 83 good Root83.pairs (triples 257 129) pivot=true
      exact Root83.search_ok
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 85 good Root85.pairs (triples 257 129) pivot=true
      exact Root85.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 93 good Root93.pairs (triples 257 129) pivot=true
      exact Root93.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 98 good Root98.pairs (triples 257 129) pivot=true
      exact Root98.search_ok
    · change ModularSearch.rootCheck 129 99 good Root99.pairs (triples 257 129) pivot=true
      exact Root99.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 113 good Root113.pairs (triples 257 129) pivot=true
      exact Root113.search_ok
    · change ModularSearch.rootCheck 129 114 good Root114.pairs (triples 257 129) pivot=true
      exact Root114.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · change ModularSearch.rootCheck 129 117 good Root117.pairs (triples 257 129) pivot=true
      exact Root117.search_ok
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin
    · norm_num [folded,inv] at hrmin

theorem cover : SixModularCover 257 :=
  sixModularCover_of_normalized 257 (by norm_num)
    (normalizedSixCover_of_sorted 257 (by norm_num) sorted_cover)

end LonelyRunner.SixModularSearch.Prime257
