import LonelyRunner.ModularPairCover
import LonelyRunner.TightFiveModular151

-- Generated by scripts/generate_tight_five_lean.py.
-- All arithmetic certificates use ordinary kernel reduction.
set_option maxHeartbeats 0
set_option maxRecDepth 1000000

namespace LonelyRunner.ModularPairCover.Prime167

def masks (a : ℕ) : ℕ :=
  if a<42 then
    if a<21 then
      if a<10 then
        if a<5 then
          if a<2 then
            if a<1 then
              0x0
            else
              0xffffffffffffff0000000
          else
            if a<3 then
              0x3fffffffffffffc000
            else
              if a<4 then
                0xffffe00007ffffffffc00
              else
                0x1ffffffe0007ffffff80
        else
          if a<7 then
            if a<6 then
              0xffe003fffff800fffffc0
            else
              0x7fffe00ffffe00ffffe0
          else
            if a<8 then
              0xff00ffff00ffff00ffff0
            else
              if a<9 then
                0x1fff80fffc07ffe03fff0
              else
                0xfc0fff81ffe07ffc0fff0
      else
        if a<15 then
          if a<12 then
            if a<11 then
              0x1ffc1ffe0ffe07ff03ff8
            else
              0xf83ff07fe0ffe0ffc1ff8
          else
            if a<13 then
              0x3ff0ffc3fe0ff83fe0ff8
            else
              if a<14 then
                0xf07f87fc3fe1ff0ff87f8
              else
                0x3fc3fc3fc3fc3fc3fc3fc
        else
          if a<18 then
            if a<16 then
              0xf1fe1fc3f87f0fe1fe3fc
            else
              if a<17 then
                0x3f8fe1fc7f1fc3f8fe1fc
              else
                0xe1f8fe3f8fe3f0fc7f1fc
          else
            if a<19 then
              0x3f1f8fc7f1f8fc7e3f8fc
            else
              if a<20 then
                0xe3f1f9f8fc7e3f1f1f8fc
              else
                0x7e3e3f3f1f1f9f8f8fc7c
    else
      if a<31 then
        if a<26 then
          if a<23 then
            if a<22 then
              0xe7e7e7e7c7c7c7c7c7c7c
            else
              0x7c7cfcf8f9f1f3e3e3e7c
          else
            if a<24 then
              0xc7cf9f1e3e7cf8f9f3e7c
            else
              if a<25 then
                0x7cf9f3e7cf9f3e78f1e3c
              else
                0xcf9f3cf9f3c79f3c79f3c
        else
          if a<28 then
            if a<27 then
              0x79f3cf9e78f3cf9e7cf3c
            else
              0xcf3cf9e79e79f3cf3cf3c
          else
            if a<29 then
              0x79e79e79e79e79e79e79e
            else
              if a<30 then
                0xcf39e79e73cf3cf79e79e
              else
                0x7bcf39e73cf79e73ce79e
      else
        if a<36 then
          if a<33 then
            if a<32 then
              0xce7bce79cf79cf79cf39e
            else
              0x73de739cf79ce7bde739e
          else
            if a<34 then
              0xdef79ce739ce739ce7bde
            else
              if a<35 then
                0x739cef7bdce739ce73bde
              else
                0xdce77b9ce77b9cef739ce
        else
          if a<39 then
            if a<37 then
              0x77b9dce7739dcef73b9ce
            else
              if a<38 then
                0xdcee773b9dcee773b9dce
              else
                0x7733b9ddcee7773b9ddce
          else
            if a<40 then
              0x9ddceee67773bb99ddcee
            else
              if a<41 then
                0x6777733bbbb99ddddccee
              else
                0x99dddddddddccccceeeee
  else
    if a<63 then
      if a<52 then
        if a<47 then
          if a<44 then
            if a<43 then
              0x6666666eeeeeeeeeeeeee
            else
              0x9bbbbbb33377777666eee
          else
            if a<45 then
              0x6eeecdddd9bbbb377666e
            else
              if a<46 then
                0xbbb3776eecdd9bbb3766e
              else
                0x6edddbb3766edd9bb376e
        else
          if a<49 then
            if a<48 then
              0xbb766eddbb766cddbb766
            else
              0x6cdbb76eddbb76eddb366
          else
            if a<50 then
              0xbb6eddb36ed9b76cdbb76
            else
              if a<51 then
                0x6d9b66ddb76ddb76ddb76
              else
                0xb76d9b6edb76d9b6edb76
      else
        if a<57 then
          if a<54 then
            if a<53 then
              0x6db76db76db76db36dbb6
            else
              0xb6edb6dbb6db66db6ddb6
          else
            if a<55 then
              0x6db6db6ddb6db6db76db6
            else
              if a<56 then
                0xb6db6db6db76db6db6db6
              else
                0xdb6db6db6db6db6db6db6
        else
          if a<60 then
            if a<58 then
              0xb6db6b6db6db6db7b6db6
            else
              if a<59 then
                0xdb6db6b6db6d6db6dbdb6
              else
                0xb6b6db5b6dadb6f6db7b6
          else
            if a<61 then
              0xdb6b6dadb7b6d6dbdb6b6
            else
              if a<62 then
                0xb5b6b6f6dedadb5b6b6f6
              else
                0xdb5b5b5b7b6b6b6f6f6d6
    else
      if a<73 then
        if a<68 then
          if a<65 then
            if a<64 then
              0xbdadadadadadededed6d6
            else
              0xdaded6d6b6b7b5bdaded6
          else
            if a<66 then
              0xaded6b7b5aded6b7b5ade
            else
              if a<67 then
                0xded6b5ad6f7bdad6b5ade
              else
                0xad6b5ad6b5ad6bdef7bde
        else
          if a<70 then
            if a<69 then
              0xdeb5ad7bd6b5af7ad6b5e
            else
              0xaf5ad7ad7bd6bd6b5eb5e
          else
            if a<71 then
              0xd6bd7ad7ad7af5af5af5a
            else
              if a<72 then
                0xab5ebd7af5ab5ebd7af5a
              else
                0xd7af56ad5ebd7af5ebd5a
      else
        if a<78 then
          if a<75 then
            if a<74 then
              0xabd5abd7abd7abd7abd7a
            else
              0xd5eaf57abd7abd5eaf57a
          else
            if a<76 then
              0xeaf57aaf57abf57abd57a
            else
              if a<77 then
                0xd57aaf55eabd57eafd5fa
              else
                0xeabf55faafd57eabd55ea
        else
          if a<81 then
            if a<79 then
              0xf557eaafd55faabf557ea
            else
              if a<80 then
                0xeaabfd557faaaff555faa
              else
                0xf5555ffaaaaff5555ffaa
          else
            if a<82 then
              0xfeaaaaafff555557ffaaa
            else
              if a<83 then
                0xffd555555557ffffaaaaa
              else
                0xfffffffaaaaaaaaaaaaaa

def spread (m : ℕ) : ℕ :=
  let x0 := (m ||| (m <<< 5312)) &&& 0xffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffff
  let x1 := (x0 ||| (x0 <<< 2656)) &&& 0xffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff
  let x2 := (x1 ||| (x1 <<< 1328)) &&& 0xffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff
  let x3 := (x2 ||| (x2 <<< 664)) &&& 0xff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff
  let x4 := (x3 ||| (x3 <<< 332)) &&& 0xf00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000000000000000000000f
  let x5 := (x4 ||| (x4 <<< 166)) &&& 0x3000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003000000000000000000000000000000000000000003
  let x6 := (x5 ||| (x5 <<< 83)) &&& 0x1000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001000000000000000000001
  x6

def pairs (a : ℕ) : ℕ := masks a * spread (masks a)

def targets (c : ℕ) : ℕ :=
  (2^84-2^c)*2^(84*c)*((2^(84*(84-c))-1)/(2^84-1))

def exceptions : List Exception := [
  ⟨2, 3, 4, 5⟩,
  ⟨2, 3, 5, 4⟩,
  ⟨2, 81, 82, 83⟩,
  ⟨2, 81, 83, 82⟩,
  ⟨3, 4, 5, 9⟩,
  ⟨3, 4, 9, 5⟩,
  ⟨3, 54, 56, 57⟩,
  ⟨3, 54, 57, 56⟩,
  ⟨18, 19, 37, 56⟩,
  ⟨18, 19, 56, 37⟩,
  ⟨33, 34, 66, 67⟩,
  ⟨33, 34, 67, 66⟩,
  ⟨34, 65, 66, 67⟩,
  ⟨34, 65, 67, 66⟩,
  ⟨41, 42, 43, 44⟩,
  ⟨41, 42, 44, 43⟩,
  ⟨41, 42, 43, 83⟩,
  ⟨41, 42, 83, 43⟩,
  ⟨54, 55, 56, 57⟩,
  ⟨54, 55, 57, 56⟩]

theorem masks_ok : masksCheck 167 84 masks=true := by decide +kernel

theorem pairs_ok : pairsCheck 84 masks pairs=true := by decide +kernel

theorem targets_ok : targetsCheck 84 targets=true := by decide +kernel

theorem exceptions_ok : exceptionsCheck 167 84 exceptions=true := by decide +kernel

theorem block_0 : blockCheck 84 masks pairs targets exceptions 1 1=true := by decide +kernel

theorem block_1 : blockCheck 84 masks pairs targets exceptions 2 1=true := by decide +kernel

theorem block_2 : blockCheck 84 masks pairs targets exceptions 3 1=true := by decide +kernel

theorem block_3 : blockCheck 84 masks pairs targets exceptions 4 1=true := by decide +kernel

theorem block_4 : blockCheck 84 masks pairs targets exceptions 5 1=true := by decide +kernel

theorem block_5 : blockCheck 84 masks pairs targets exceptions 6 1=true := by decide +kernel

theorem block_6 : blockCheck 84 masks pairs targets exceptions 7 1=true := by decide +kernel

theorem block_7 : blockCheck 84 masks pairs targets exceptions 8 1=true := by decide +kernel

theorem block_8 : blockCheck 84 masks pairs targets exceptions 9 1=true := by decide +kernel

theorem block_9 : blockCheck 84 masks pairs targets exceptions 10 1=true := by decide +kernel

theorem block_10 : blockCheck 84 masks pairs targets exceptions 11 1=true := by decide +kernel

theorem block_11 : blockCheck 84 masks pairs targets exceptions 12 1=true := by decide +kernel

theorem block_12 : blockCheck 84 masks pairs targets exceptions 13 1=true := by decide +kernel

theorem block_13 : blockCheck 84 masks pairs targets exceptions 14 1=true := by decide +kernel

theorem block_14 : blockCheck 84 masks pairs targets exceptions 15 1=true := by decide +kernel

theorem block_15 : blockCheck 84 masks pairs targets exceptions 16 1=true := by decide +kernel

theorem block_16 : blockCheck 84 masks pairs targets exceptions 17 1=true := by decide +kernel

theorem block_17 : blockCheck 84 masks pairs targets exceptions 18 1=true := by decide +kernel

theorem block_18 : blockCheck 84 masks pairs targets exceptions 19 1=true := by decide +kernel

theorem block_19 : blockCheck 84 masks pairs targets exceptions 20 1=true := by decide +kernel

theorem block_20 : blockCheck 84 masks pairs targets exceptions 21 1=true := by decide +kernel

theorem block_21 : blockCheck 84 masks pairs targets exceptions 22 1=true := by decide +kernel

theorem block_22 : blockCheck 84 masks pairs targets exceptions 23 1=true := by decide +kernel

theorem block_23 : blockCheck 84 masks pairs targets exceptions 24 1=true := by decide +kernel

theorem block_24 : blockCheck 84 masks pairs targets exceptions 25 1=true := by decide +kernel

theorem block_25 : blockCheck 84 masks pairs targets exceptions 26 1=true := by decide +kernel

theorem block_26 : blockCheck 84 masks pairs targets exceptions 27 1=true := by decide +kernel

theorem block_27 : blockCheck 84 masks pairs targets exceptions 28 1=true := by decide +kernel

theorem block_28 : blockCheck 84 masks pairs targets exceptions 29 1=true := by decide +kernel

theorem block_29 : blockCheck 84 masks pairs targets exceptions 30 1=true := by decide +kernel

theorem block_30 : blockCheck 84 masks pairs targets exceptions 31 1=true := by decide +kernel

theorem block_31 : blockCheck 84 masks pairs targets exceptions 32 1=true := by decide +kernel

theorem block_32 : blockCheck 84 masks pairs targets exceptions 33 1=true := by decide +kernel

theorem block_33 : blockCheck 84 masks pairs targets exceptions 34 1=true := by decide +kernel

theorem block_34 : blockCheck 84 masks pairs targets exceptions 35 1=true := by decide +kernel

theorem block_35 : blockCheck 84 masks pairs targets exceptions 36 1=true := by decide +kernel

theorem block_36 : blockCheck 84 masks pairs targets exceptions 37 1=true := by decide +kernel

theorem block_37 : blockCheck 84 masks pairs targets exceptions 38 1=true := by decide +kernel

theorem block_38 : blockCheck 84 masks pairs targets exceptions 39 1=true := by decide +kernel

theorem block_39 : blockCheck 84 masks pairs targets exceptions 40 1=true := by decide +kernel

theorem block_40 : blockCheck 84 masks pairs targets exceptions 41 1=true := by decide +kernel

theorem block_41 : blockCheck 84 masks pairs targets exceptions 42 1=true := by decide +kernel

theorem block_42 : blockCheck 84 masks pairs targets exceptions 43 1=true := by decide +kernel

theorem block_43 : blockCheck 84 masks pairs targets exceptions 44 1=true := by decide +kernel

theorem block_44 : blockCheck 84 masks pairs targets exceptions 45 1=true := by decide +kernel

theorem block_45 : blockCheck 84 masks pairs targets exceptions 46 1=true := by decide +kernel

theorem block_46 : blockCheck 84 masks pairs targets exceptions 47 1=true := by decide +kernel

theorem block_47 : blockCheck 84 masks pairs targets exceptions 48 1=true := by decide +kernel

theorem block_48 : blockCheck 84 masks pairs targets exceptions 49 1=true := by decide +kernel

theorem block_49 : blockCheck 84 masks pairs targets exceptions 50 1=true := by decide +kernel

theorem block_50 : blockCheck 84 masks pairs targets exceptions 51 1=true := by decide +kernel

theorem block_51 : blockCheck 84 masks pairs targets exceptions 52 1=true := by decide +kernel

theorem block_52 : blockCheck 84 masks pairs targets exceptions 53 1=true := by decide +kernel

theorem block_53 : blockCheck 84 masks pairs targets exceptions 54 1=true := by decide +kernel

theorem block_54 : blockCheck 84 masks pairs targets exceptions 55 1=true := by decide +kernel

theorem block_55 : blockCheck 84 masks pairs targets exceptions 56 1=true := by decide +kernel

theorem block_56 : blockCheck 84 masks pairs targets exceptions 57 1=true := by decide +kernel

theorem block_57 : blockCheck 84 masks pairs targets exceptions 58 1=true := by decide +kernel

theorem block_58 : blockCheck 84 masks pairs targets exceptions 59 1=true := by decide +kernel

theorem block_59 : blockCheck 84 masks pairs targets exceptions 60 1=true := by decide +kernel

theorem block_60 : blockCheck 84 masks pairs targets exceptions 61 1=true := by decide +kernel

theorem block_61 : blockCheck 84 masks pairs targets exceptions 62 1=true := by decide +kernel

theorem block_62 : blockCheck 84 masks pairs targets exceptions 63 1=true := by decide +kernel

theorem block_63 : blockCheck 84 masks pairs targets exceptions 64 1=true := by decide +kernel

theorem block_64 : blockCheck 84 masks pairs targets exceptions 65 1=true := by decide +kernel

theorem block_65 : blockCheck 84 masks pairs targets exceptions 66 1=true := by decide +kernel

theorem block_66 : blockCheck 84 masks pairs targets exceptions 67 1=true := by decide +kernel

theorem block_67 : blockCheck 84 masks pairs targets exceptions 68 1=true := by decide +kernel

theorem block_68 : blockCheck 84 masks pairs targets exceptions 69 1=true := by decide +kernel

theorem block_69 : blockCheck 84 masks pairs targets exceptions 70 1=true := by decide +kernel

theorem block_70 : blockCheck 84 masks pairs targets exceptions 71 1=true := by decide +kernel

theorem block_71 : blockCheck 84 masks pairs targets exceptions 72 1=true := by decide +kernel

theorem block_72 : blockCheck 84 masks pairs targets exceptions 73 1=true := by decide +kernel

theorem block_73 : blockCheck 84 masks pairs targets exceptions 74 1=true := by decide +kernel

theorem block_74 : blockCheck 84 masks pairs targets exceptions 75 1=true := by decide +kernel

theorem block_75 : blockCheck 84 masks pairs targets exceptions 76 1=true := by decide +kernel

theorem block_76 : blockCheck 84 masks pairs targets exceptions 77 1=true := by decide +kernel

theorem block_77 : blockCheck 84 masks pairs targets exceptions 78 1=true := by decide +kernel

theorem block_78 : blockCheck 84 masks pairs targets exceptions 79 1=true := by decide +kernel

theorem block_79 : blockCheck 84 masks pairs targets exceptions 80 1=true := by decide +kernel

theorem block_80 : blockCheck 84 masks pairs targets exceptions 81 1=true := by decide +kernel

theorem block_81 : blockCheck 84 masks pairs targets exceptions 82 1=true := by decide +kernel

theorem block_82 : blockCheck 84 masks pairs targets exceptions 83 1=true := by decide +kernel

theorem rows_ok : rowsCheck 84 masks pairs targets exceptions=true := by
  apply rowsCheck_of_blocks 84 masks pairs targets exceptions 1 83 (by decide) (by decide)
  intro q hq
  interval_cases q
  · exact block_0
  · exact block_1
  · exact block_2
  · exact block_3
  · exact block_4
  · exact block_5
  · exact block_6
  · exact block_7
  · exact block_8
  · exact block_9
  · exact block_10
  · exact block_11
  · exact block_12
  · exact block_13
  · exact block_14
  · exact block_15
  · exact block_16
  · exact block_17
  · exact block_18
  · exact block_19
  · exact block_20
  · exact block_21
  · exact block_22
  · exact block_23
  · exact block_24
  · exact block_25
  · exact block_26
  · exact block_27
  · exact block_28
  · exact block_29
  · exact block_30
  · exact block_31
  · exact block_32
  · exact block_33
  · exact block_34
  · exact block_35
  · exact block_36
  · exact block_37
  · exact block_38
  · exact block_39
  · exact block_40
  · exact block_41
  · exact block_42
  · exact block_43
  · exact block_44
  · exact block_45
  · exact block_46
  · exact block_47
  · exact block_48
  · exact block_49
  · exact block_50
  · exact block_51
  · exact block_52
  · exact block_53
  · exact block_54
  · exact block_55
  · exact block_56
  · exact block_57
  · exact block_58
  · exact block_59
  · exact block_60
  · exact block_61
  · exact block_62
  · exact block_63
  · exact block_64
  · exact block_65
  · exact block_66
  · exact block_67
  · exact block_68
  · exact block_69
  · exact block_70
  · exact block_71
  · exact block_72
  · exact block_73
  · exact block_74
  · exact block_75
  · exact block_76
  · exact block_77
  · exact block_78
  · exact block_79
  · exact block_80
  · exact block_81
  · exact block_82

theorem normalized_cover : NormalizedFiveCover 167 :=
  normalized_of_checks 167 (by decide) masks pairs targets exceptions
    masks_ok pairs_ok targets_ok exceptions_ok rows_ok

/-- The finite certificate applies to every tight integer tuple. -/
theorem tight_cover (v : Fin 5 → ℤ) (hl : loneliness v=(1:ℝ)/6) :
    (∃ i, (167:ℤ) ∣ v i) ∨ ∀ j, (167:ℤ) ∣ tightFiveMoment v j := by
  by_cases hv : ∃ i, (167:ℤ) ∣ v i
  · exact Or.inl hv
  · exact Or.inr (moment_cover_of_normalized 167 (by decide) normalized_cover
      v hl (by simpa using hv))

end LonelyRunner.ModularPairCover.Prime167
