import LonelyRunner.ModularPairCover
import LonelyRunner.TightFiveModular103

-- Generated by scripts/generate_tight_five_lean.py.
-- All arithmetic certificates use ordinary kernel reduction.
set_option maxHeartbeats 0
set_option maxRecDepth 1000000

namespace LonelyRunner.ModularPairCover.Prime131

def masks (a : ℕ) : ℕ :=
  if a<33 then
    if a<16 then
      if a<8 then
        if a<4 then
          if a<2 then
            if a<1 then
              0x0
            else
              0x3ffffffffffc00000
          else
            if a<3 then
              0x7ffffffffff800
            else
              0x3fff8001fffffff00
        else
          if a<6 then
            if a<5 then
              0x1fffff800fffffc0
            else
              0x3fe01ffff803fffe0
          else
            if a<7 then
              0x3fff01fffc07fff0
            else
              0x3f03ffe07ffc0fff0
      else
        if a<12 then
          if a<10 then
            if a<9 then
              0x7ff07ff07ff03ff8
            else
              0x3e0ff83ff07fe1ff8
          else
            if a<11 then
              0xff87fc3fe1ff07f8
            else
              0x3c3fc3fc3fc3fc3fc
        else
          if a<14 then
            if a<13 then
              0xfe1fc3f87f1fe3fc
            else
              0x387e1fc7f1fc7f1fc
          else
            if a<15 then
              0xfc7e3f8fc7e3f8fc
            else
              0x38fc7c7e3f1f9f8fc
    else
      if a<24 then
        if a<20 then
          if a<18 then
            if a<17 then
              0x1f8f8f8f8fcfcfc7c
            else
              0x39f1f1f3e3e3e7e7c
          else
            if a<19 then
              0x1f3e3e7cf8f1f3e7c
            else
              0x31e7cf9f3e7cf9e3c
        else
          if a<22 then
            if a<21 then
              0x1e3cf9e7cf3e79f3c
            else
              0x33cf9e79e7cf3cf3c
          else
            if a<23 then
              0x1e79e79e79e79e79e
            else
              0x33de79e73cf39e79e
      else
        if a<28 then
          if a<26 then
            if a<25 then
              0x1ef39e73ce79cf79e
            else
              0x379ce7bce73de739e
          else
            if a<27 then
              0x1ce739ce739ef7bde
            else
              0x3739ce77bdce739de
        else
          if a<30 then
            if a<29 then
              0x1dee77b9cee73b9ce
            else
              0x373b9dcee773b9dce
          else
            if a<31 then
              0x1ddcee6773bb9ddce
            else
              if a<32 then
                0x277773bbb99ddccee
              else
                0x19dddddddcccceeee
  else
    if a<49 then
      if a<41 then
        if a<37 then
          if a<35 then
            if a<34 then
              0x266666eeeeeeeeeee
            else
              0x1bbbbb337777666ee
          else
            if a<36 then
              0x2eecddd9bbb37766e
            else
              0x1bb376eedd9bb376e
        else
          if a<39 then
            if a<38 then
              0x2edd9b376eddbb766
            else
              0x1b76eddb36eddbb66
          else
            if a<40 then
              0x2cdbb6edbb66ddb76
            else
              0x1b6edb76d9b6edb76
      else
        if a<45 then
          if a<43 then
            if a<42 then
              0x2d9b6dbb6dbb6dbb6
            else
              0x1b6db6ddb6db6edb6
          else
            if a<44 then
              0x2db6db6dbb6db6db6
            else
              0x36db6db6db6db6db6
        else
          if a<47 then
            if a<46 then
              0x2db6f6db6db6d6db6
            else
              0x36db6b6db7b6db5b6
          else
            if a<48 then
              0x2dedb5b6d6dbdb6b6
            else
              0x36d6dadbdb5b6b6f6
    else
      if a<57 then
        if a<53 then
          if a<51 then
            if a<50 then
              0x2f6f6f6d6d6d6d6d6
            else
              0x36b6b7b5bdadaded6
          else
            if a<52 then
              0x2b7b5aded6b7b5ade
            else
              0x37bdad6b5ad6b5bde
        else
          if a<55 then
            if a<54 then
              0x2b5af7bd6b5ad6bde
            else
              0x35ad7ad6bd6bdeb5e
          else
            if a<56 then
              0x2bd7ad7ad7af5af5a
            else
              0x35ebd7af5ebd6ad5a
      else
        if a<61 then
          if a<59 then
            if a<58 then
              0x2af5ead5ebd5ebd7a
            else
              0x357abd5ebd5eaf57a
          else
            if a<60 then
              0x3abd5fabd57abd57a
            else
              0x355faaf55faaf55fa
        else
          if a<63 then
            if a<62 then
              0x3aabf557eabf557ea
            else
              0x3d557faaaff555faa
          else
            if a<64 then
              0x3eaaaaffd5557feaa
            else
              if a<65 then
                0x3fd5555557fffaaaa
              else
                0x3fffffaaaaaaaaaaa

def spread (m : ℕ) : ℕ :=
  let x0 := (m ||| (m <<< 4160)) &&& 0xffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffff
  let x1 := (x0 ||| (x0 <<< 2080)) &&& 0xffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff
  let x2 := (x1 ||| (x1 <<< 1040)) &&& 0xffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff
  let x3 := (x2 ||| (x2 <<< 520)) &&& 0xff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff
  let x4 := (x3 ||| (x3 <<< 260)) &&& 0xf00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000000000000000f
  let x5 := (x4 ||| (x4 <<< 130)) &&& 0x3000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003000000000000000000000000000000003
  let x6 := (x5 ||| (x5 <<< 65)) &&& 0x40000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001000000000000000040000000000000001
  x6

def pairs (a : ℕ) : ℕ := masks a * spread (masks a)

def targets (c : ℕ) : ℕ :=
  (2^66-2^c)*2^(66*c)*((2^(66*(66-c))-1)/(2^66-1))

def exceptions : List Exception := [
  ⟨2, 3, 4, 5⟩,
  ⟨2, 3, 5, 4⟩,
  ⟨2, 63, 64, 65⟩,
  ⟨2, 63, 65, 64⟩,
  ⟨3, 4, 5, 9⟩,
  ⟨3, 4, 9, 5⟩,
  ⟨3, 42, 44, 45⟩,
  ⟨3, 42, 45, 44⟩,
  ⟨14, 15, 29, 44⟩,
  ⟨14, 15, 44, 29⟩,
  ⟨26, 27, 28, 53⟩,
  ⟨26, 27, 53, 28⟩,
  ⟨26, 27, 52, 53⟩,
  ⟨26, 27, 53, 52⟩,
  ⟨32, 33, 34, 35⟩,
  ⟨32, 33, 35, 34⟩,
  ⟨32, 33, 34, 65⟩,
  ⟨32, 33, 65, 34⟩,
  ⟨42, 43, 44, 45⟩,
  ⟨42, 43, 45, 44⟩]

theorem masks_ok : masksCheck 131 66 masks=true := by decide +kernel

theorem pairs_ok : pairsCheck 66 masks pairs=true := by decide +kernel

theorem targets_ok : targetsCheck 66 targets=true := by decide +kernel

theorem exceptions_ok : exceptionsCheck 131 66 exceptions=true := by decide +kernel

theorem block_0 : blockCheck 66 masks pairs targets exceptions 1 1=true := by decide +kernel

theorem block_1 : blockCheck 66 masks pairs targets exceptions 2 1=true := by decide +kernel

theorem block_2 : blockCheck 66 masks pairs targets exceptions 3 1=true := by decide +kernel

theorem block_3 : blockCheck 66 masks pairs targets exceptions 4 1=true := by decide +kernel

theorem block_4 : blockCheck 66 masks pairs targets exceptions 5 1=true := by decide +kernel

theorem block_5 : blockCheck 66 masks pairs targets exceptions 6 1=true := by decide +kernel

theorem block_6 : blockCheck 66 masks pairs targets exceptions 7 1=true := by decide +kernel

theorem block_7 : blockCheck 66 masks pairs targets exceptions 8 1=true := by decide +kernel

theorem block_8 : blockCheck 66 masks pairs targets exceptions 9 1=true := by decide +kernel

theorem block_9 : blockCheck 66 masks pairs targets exceptions 10 1=true := by decide +kernel

theorem block_10 : blockCheck 66 masks pairs targets exceptions 11 1=true := by decide +kernel

theorem block_11 : blockCheck 66 masks pairs targets exceptions 12 1=true := by decide +kernel

theorem block_12 : blockCheck 66 masks pairs targets exceptions 13 1=true := by decide +kernel

theorem block_13 : blockCheck 66 masks pairs targets exceptions 14 1=true := by decide +kernel

theorem block_14 : blockCheck 66 masks pairs targets exceptions 15 1=true := by decide +kernel

theorem block_15 : blockCheck 66 masks pairs targets exceptions 16 1=true := by decide +kernel

theorem block_16 : blockCheck 66 masks pairs targets exceptions 17 1=true := by decide +kernel

theorem block_17 : blockCheck 66 masks pairs targets exceptions 18 1=true := by decide +kernel

theorem block_18 : blockCheck 66 masks pairs targets exceptions 19 1=true := by decide +kernel

theorem block_19 : blockCheck 66 masks pairs targets exceptions 20 1=true := by decide +kernel

theorem block_20 : blockCheck 66 masks pairs targets exceptions 21 1=true := by decide +kernel

theorem block_21 : blockCheck 66 masks pairs targets exceptions 22 1=true := by decide +kernel

theorem block_22 : blockCheck 66 masks pairs targets exceptions 23 1=true := by decide +kernel

theorem block_23 : blockCheck 66 masks pairs targets exceptions 24 1=true := by decide +kernel

theorem block_24 : blockCheck 66 masks pairs targets exceptions 25 1=true := by decide +kernel

theorem block_25 : blockCheck 66 masks pairs targets exceptions 26 1=true := by decide +kernel

theorem block_26 : blockCheck 66 masks pairs targets exceptions 27 1=true := by decide +kernel

theorem block_27 : blockCheck 66 masks pairs targets exceptions 28 1=true := by decide +kernel

theorem block_28 : blockCheck 66 masks pairs targets exceptions 29 1=true := by decide +kernel

theorem block_29 : blockCheck 66 masks pairs targets exceptions 30 1=true := by decide +kernel

theorem block_30 : blockCheck 66 masks pairs targets exceptions 31 1=true := by decide +kernel

theorem block_31 : blockCheck 66 masks pairs targets exceptions 32 1=true := by decide +kernel

theorem block_32 : blockCheck 66 masks pairs targets exceptions 33 1=true := by decide +kernel

theorem block_33 : blockCheck 66 masks pairs targets exceptions 34 1=true := by decide +kernel

theorem block_34 : blockCheck 66 masks pairs targets exceptions 35 1=true := by decide +kernel

theorem block_35 : blockCheck 66 masks pairs targets exceptions 36 1=true := by decide +kernel

theorem block_36 : blockCheck 66 masks pairs targets exceptions 37 1=true := by decide +kernel

theorem block_37 : blockCheck 66 masks pairs targets exceptions 38 1=true := by decide +kernel

theorem block_38 : blockCheck 66 masks pairs targets exceptions 39 1=true := by decide +kernel

theorem block_39 : blockCheck 66 masks pairs targets exceptions 40 1=true := by decide +kernel

theorem block_40 : blockCheck 66 masks pairs targets exceptions 41 1=true := by decide +kernel

theorem block_41 : blockCheck 66 masks pairs targets exceptions 42 1=true := by decide +kernel

theorem block_42 : blockCheck 66 masks pairs targets exceptions 43 1=true := by decide +kernel

theorem block_43 : blockCheck 66 masks pairs targets exceptions 44 1=true := by decide +kernel

theorem block_44 : blockCheck 66 masks pairs targets exceptions 45 1=true := by decide +kernel

theorem block_45 : blockCheck 66 masks pairs targets exceptions 46 1=true := by decide +kernel

theorem block_46 : blockCheck 66 masks pairs targets exceptions 47 1=true := by decide +kernel

theorem block_47 : blockCheck 66 masks pairs targets exceptions 48 1=true := by decide +kernel

theorem block_48 : blockCheck 66 masks pairs targets exceptions 49 1=true := by decide +kernel

theorem block_49 : blockCheck 66 masks pairs targets exceptions 50 1=true := by decide +kernel

theorem block_50 : blockCheck 66 masks pairs targets exceptions 51 1=true := by decide +kernel

theorem block_51 : blockCheck 66 masks pairs targets exceptions 52 1=true := by decide +kernel

theorem block_52 : blockCheck 66 masks pairs targets exceptions 53 1=true := by decide +kernel

theorem block_53 : blockCheck 66 masks pairs targets exceptions 54 1=true := by decide +kernel

theorem block_54 : blockCheck 66 masks pairs targets exceptions 55 1=true := by decide +kernel

theorem block_55 : blockCheck 66 masks pairs targets exceptions 56 1=true := by decide +kernel

theorem block_56 : blockCheck 66 masks pairs targets exceptions 57 1=true := by decide +kernel

theorem block_57 : blockCheck 66 masks pairs targets exceptions 58 1=true := by decide +kernel

theorem block_58 : blockCheck 66 masks pairs targets exceptions 59 1=true := by decide +kernel

theorem block_59 : blockCheck 66 masks pairs targets exceptions 60 1=true := by decide +kernel

theorem block_60 : blockCheck 66 masks pairs targets exceptions 61 1=true := by decide +kernel

theorem block_61 : blockCheck 66 masks pairs targets exceptions 62 1=true := by decide +kernel

theorem block_62 : blockCheck 66 masks pairs targets exceptions 63 1=true := by decide +kernel

theorem block_63 : blockCheck 66 masks pairs targets exceptions 64 1=true := by decide +kernel

theorem block_64 : blockCheck 66 masks pairs targets exceptions 65 1=true := by decide +kernel

theorem rows_ok : rowsCheck 66 masks pairs targets exceptions=true := by
  apply rowsCheck_of_blocks 66 masks pairs targets exceptions 1 65 (by decide) (by decide)
  intro q hq
  interval_cases q
  · exact block_0
  · exact block_1
  · exact block_2
  · exact block_3
  · exact block_4
  · exact block_5
  · exact block_6
  · exact block_7
  · exact block_8
  · exact block_9
  · exact block_10
  · exact block_11
  · exact block_12
  · exact block_13
  · exact block_14
  · exact block_15
  · exact block_16
  · exact block_17
  · exact block_18
  · exact block_19
  · exact block_20
  · exact block_21
  · exact block_22
  · exact block_23
  · exact block_24
  · exact block_25
  · exact block_26
  · exact block_27
  · exact block_28
  · exact block_29
  · exact block_30
  · exact block_31
  · exact block_32
  · exact block_33
  · exact block_34
  · exact block_35
  · exact block_36
  · exact block_37
  · exact block_38
  · exact block_39
  · exact block_40
  · exact block_41
  · exact block_42
  · exact block_43
  · exact block_44
  · exact block_45
  · exact block_46
  · exact block_47
  · exact block_48
  · exact block_49
  · exact block_50
  · exact block_51
  · exact block_52
  · exact block_53
  · exact block_54
  · exact block_55
  · exact block_56
  · exact block_57
  · exact block_58
  · exact block_59
  · exact block_60
  · exact block_61
  · exact block_62
  · exact block_63
  · exact block_64

theorem normalized_cover : NormalizedFiveCover 131 :=
  normalized_of_checks 131 (by decide) masks pairs targets exceptions
    masks_ok pairs_ok targets_ok exceptions_ok rows_ok

/-- The finite certificate applies to every tight integer tuple. -/
theorem tight_cover (v : Fin 5 → ℤ) (hl : loneliness v=(1:ℝ)/6) :
    (∃ i, (131:ℤ) ∣ v i) ∨ ∀ j, (131:ℤ) ∣ tightFiveMoment v j := by
  by_cases hv : ∃ i, (131:ℤ) ∣ v i
  · exact Or.inl hv
  · exact Or.inr (moment_cover_of_normalized 131 (by decide) normalized_cover
      v hl (by simpa using hv))

end LonelyRunner.ModularPairCover.Prime131
