import LonelyRunner.ModularPairCover
import LonelyRunner.TightFiveModular101

-- Generated by scripts/generate_tight_five_lean.py.
-- All arithmetic certificates use ordinary kernel reduction.
set_option maxHeartbeats 0
set_option maxRecDepth 1000000

namespace LonelyRunner.ModularPairCover.Prime107

def masks (a : ℕ) : ℕ :=
  if a<27 then
    if a<13 then
      if a<6 then
        if a<3 then
          if a<1 then
            0x0
          else
            if a<2 then
              0x3ffffffffc0000
            else
              0x1ffffffffe00
        else
          if a<4 then
            0x3ffc003fffffc0
          else
            if a<5 then
              0x3ffff007fffe0
            else
              0x3f80fffe03fff0
      else
        if a<9 then
          if a<7 then
            0x7ff81ffe07ff8
          else
            if a<8 then
              0x3e0ffc1ffc1ff8
            else
              0xff83fe1ff0ff8
        else
          if a<11 then
            if a<10 then
              0x3c3fc3fc3fc3fc
            else
              0xfe3fc7f0fe1fc
          else
            if a<12 then
              0x38fe3f8fc3f1fc
            else
              0x1f8fc7e3f1f8fc
    else
      if a<20 then
        if a<16 then
          if a<14 then
            0x39f8f8f8fcfc7c
          else
            if a<15 then
              0x1f1f1f3e3e7e7c
            else
              0x31f3e7cf9f3e3c
        else
          if a<18 then
            if a<17 then
              0x1f3cf9f3c79f3c
            else
              0x33cf9e79f3cf3c
          else
            if a<19 then
              0x1e79e79e79e79e
            else
              0x33de79cf3ce79e
      else
        if a<23 then
          if a<21 then
            0x1cf39ef39ef39e
          else
            if a<22 then
              0x37bce739ce73de
            else
              0x1ce77bdce739de
        else
          if a<25 then
            if a<24 then
              0x373bdcee73b9ce
            else
              0x1dcee7773b9dce
          else
            if a<26 then
              0x27773bb99ddcee
            else
              0x19ddddddccceee
  else
    if a<40 then
      if a<33 then
        if a<30 then
          if a<28 then
            0x26666eeeeeeeee
          else
            if a<29 then
              0x1bbbb3377766ee
            else
              0x2eecdd9bb3776e
        else
          if a<31 then
            0x1bb76ecddbb766
          else
            if a<32 then
              0x2eddb36eddbb66
            else
              0x1b66ddb76ddb76
      else
        if a<36 then
          if a<34 then
            0x2ddb6edb76db36
          else
            if a<35 then
              0x1b6db76db6ddb6
            else
              0x2db6db6edb6db6
        else
          if a<38 then
            if a<37 then
              0x36db6db6db6db6
            else
              0x2db7b6db6dadb6
          else
            if a<39 then
              0x36db5b6dedb6b6
            else
              0x2d6dadb5b7b6f6
    else
      if a<47 then
        if a<43 then
          if a<41 then
            0x36f6f6d6d6d6d6
          else
            if a<42 then
              0x2b6b7b5bdaded6
            else
              0x36b5adef6b5ade
        else
          if a<45 then
            if a<44 then
              0x2b5ad6b5af7bde
            else
              0x35ad7ad6bdeb5e
          else
            if a<46 then
              0x2bd7ad7af5af5a
            else
              0x35ebd7af5ead5a
      else
        if a<50 then
          if a<48 then
            0x2af57af57abd7a
          else
            if a<49 then
              0x357aaf57abf57a
            else
              0x3aaf55faaf55fa
        else
          if a<52 then
            if a<51 then
              0x3d55faabf557ea
            else
              0x3eaaaff5557faa
          else
            if a<53 then
              0x3f555555fffaaa
            else
              0x3ffffaaaaaaaaa

def spread (m : ℕ) : ℕ :=
  let x0 := (m ||| (m <<< 1696)) &&& 0xffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff
  let x1 := (x0 ||| (x0 <<< 848)) &&& 0xffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff
  let x2 := (x1 ||| (x1 <<< 424)) &&& 0xff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff
  let x3 := (x2 ||| (x2 <<< 212)) &&& 0xf00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000000f
  let x4 := (x3 ||| (x3 <<< 106)) &&& 0x3000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003000000000000000000000000003
  let x5 := (x4 ||| (x4 <<< 53)) &&& 0x40000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001000000000000040000000000001
  x5

def pairs (a : ℕ) : ℕ := masks a * spread (masks a)

def targets (c : ℕ) : ℕ :=
  (2^54-2^c)*2^(54*c)*((2^(54*(54-c))-1)/(2^54-1))

def exceptions : List Exception := [
  ⟨2, 3, 4, 5⟩,
  ⟨2, 3, 5, 4⟩,
  ⟨2, 51, 52, 53⟩,
  ⟨2, 51, 53, 52⟩,
  ⟨3, 4, 5, 9⟩,
  ⟨3, 4, 9, 5⟩,
  ⟨3, 34, 36, 37⟩,
  ⟨3, 34, 37, 36⟩,
  ⟨12, 36, 47, 48⟩,
  ⟨12, 36, 48, 47⟩,
  ⟨21, 22, 42, 43⟩,
  ⟨21, 22, 43, 42⟩,
  ⟨22, 41, 42, 43⟩,
  ⟨22, 41, 43, 42⟩,
  ⟨26, 27, 28, 29⟩,
  ⟨26, 27, 29, 28⟩,
  ⟨26, 27, 28, 53⟩,
  ⟨26, 27, 53, 28⟩,
  ⟨34, 35, 36, 37⟩,
  ⟨34, 35, 37, 36⟩]

theorem masks_ok : masksCheck 107 54 masks=true := by decide +kernel

theorem pairs_ok : pairsCheck 54 masks pairs=true := by decide +kernel

theorem targets_ok : targetsCheck 54 targets=true := by decide +kernel

theorem exceptions_ok : exceptionsCheck 107 54 exceptions=true := by decide +kernel

theorem block_0 : blockCheck 54 masks pairs targets exceptions 1 1=true := by decide +kernel

theorem block_1 : blockCheck 54 masks pairs targets exceptions 2 1=true := by decide +kernel

theorem block_2 : blockCheck 54 masks pairs targets exceptions 3 1=true := by decide +kernel

theorem block_3 : blockCheck 54 masks pairs targets exceptions 4 1=true := by decide +kernel

theorem block_4 : blockCheck 54 masks pairs targets exceptions 5 1=true := by decide +kernel

theorem block_5 : blockCheck 54 masks pairs targets exceptions 6 1=true := by decide +kernel

theorem block_6 : blockCheck 54 masks pairs targets exceptions 7 1=true := by decide +kernel

theorem block_7 : blockCheck 54 masks pairs targets exceptions 8 1=true := by decide +kernel

theorem block_8 : blockCheck 54 masks pairs targets exceptions 9 1=true := by decide +kernel

theorem block_9 : blockCheck 54 masks pairs targets exceptions 10 1=true := by decide +kernel

theorem block_10 : blockCheck 54 masks pairs targets exceptions 11 1=true := by decide +kernel

theorem block_11 : blockCheck 54 masks pairs targets exceptions 12 1=true := by decide +kernel

theorem block_12 : blockCheck 54 masks pairs targets exceptions 13 1=true := by decide +kernel

theorem block_13 : blockCheck 54 masks pairs targets exceptions 14 1=true := by decide +kernel

theorem block_14 : blockCheck 54 masks pairs targets exceptions 15 1=true := by decide +kernel

theorem block_15 : blockCheck 54 masks pairs targets exceptions 16 1=true := by decide +kernel

theorem block_16 : blockCheck 54 masks pairs targets exceptions 17 1=true := by decide +kernel

theorem block_17 : blockCheck 54 masks pairs targets exceptions 18 1=true := by decide +kernel

theorem block_18 : blockCheck 54 masks pairs targets exceptions 19 1=true := by decide +kernel

theorem block_19 : blockCheck 54 masks pairs targets exceptions 20 1=true := by decide +kernel

theorem block_20 : blockCheck 54 masks pairs targets exceptions 21 1=true := by decide +kernel

theorem block_21 : blockCheck 54 masks pairs targets exceptions 22 1=true := by decide +kernel

theorem block_22 : blockCheck 54 masks pairs targets exceptions 23 1=true := by decide +kernel

theorem block_23 : blockCheck 54 masks pairs targets exceptions 24 1=true := by decide +kernel

theorem block_24 : blockCheck 54 masks pairs targets exceptions 25 1=true := by decide +kernel

theorem block_25 : blockCheck 54 masks pairs targets exceptions 26 1=true := by decide +kernel

theorem block_26 : blockCheck 54 masks pairs targets exceptions 27 1=true := by decide +kernel

theorem block_27 : blockCheck 54 masks pairs targets exceptions 28 1=true := by decide +kernel

theorem block_28 : blockCheck 54 masks pairs targets exceptions 29 1=true := by decide +kernel

theorem block_29 : blockCheck 54 masks pairs targets exceptions 30 1=true := by decide +kernel

theorem block_30 : blockCheck 54 masks pairs targets exceptions 31 1=true := by decide +kernel

theorem block_31 : blockCheck 54 masks pairs targets exceptions 32 1=true := by decide +kernel

theorem block_32 : blockCheck 54 masks pairs targets exceptions 33 1=true := by decide +kernel

theorem block_33 : blockCheck 54 masks pairs targets exceptions 34 1=true := by decide +kernel

theorem block_34 : blockCheck 54 masks pairs targets exceptions 35 1=true := by decide +kernel

theorem block_35 : blockCheck 54 masks pairs targets exceptions 36 1=true := by decide +kernel

theorem block_36 : blockCheck 54 masks pairs targets exceptions 37 1=true := by decide +kernel

theorem block_37 : blockCheck 54 masks pairs targets exceptions 38 1=true := by decide +kernel

theorem block_38 : blockCheck 54 masks pairs targets exceptions 39 1=true := by decide +kernel

theorem block_39 : blockCheck 54 masks pairs targets exceptions 40 1=true := by decide +kernel

theorem block_40 : blockCheck 54 masks pairs targets exceptions 41 1=true := by decide +kernel

theorem block_41 : blockCheck 54 masks pairs targets exceptions 42 1=true := by decide +kernel

theorem block_42 : blockCheck 54 masks pairs targets exceptions 43 1=true := by decide +kernel

theorem block_43 : blockCheck 54 masks pairs targets exceptions 44 1=true := by decide +kernel

theorem block_44 : blockCheck 54 masks pairs targets exceptions 45 1=true := by decide +kernel

theorem block_45 : blockCheck 54 masks pairs targets exceptions 46 1=true := by decide +kernel

theorem block_46 : blockCheck 54 masks pairs targets exceptions 47 1=true := by decide +kernel

theorem block_47 : blockCheck 54 masks pairs targets exceptions 48 1=true := by decide +kernel

theorem block_48 : blockCheck 54 masks pairs targets exceptions 49 1=true := by decide +kernel

theorem block_49 : blockCheck 54 masks pairs targets exceptions 50 1=true := by decide +kernel

theorem block_50 : blockCheck 54 masks pairs targets exceptions 51 1=true := by decide +kernel

theorem block_51 : blockCheck 54 masks pairs targets exceptions 52 1=true := by decide +kernel

theorem block_52 : blockCheck 54 masks pairs targets exceptions 53 1=true := by decide +kernel

theorem rows_ok : rowsCheck 54 masks pairs targets exceptions=true := by
  apply rowsCheck_of_blocks 54 masks pairs targets exceptions 1 53 (by decide) (by decide)
  intro q hq
  interval_cases q
  · exact block_0
  · exact block_1
  · exact block_2
  · exact block_3
  · exact block_4
  · exact block_5
  · exact block_6
  · exact block_7
  · exact block_8
  · exact block_9
  · exact block_10
  · exact block_11
  · exact block_12
  · exact block_13
  · exact block_14
  · exact block_15
  · exact block_16
  · exact block_17
  · exact block_18
  · exact block_19
  · exact block_20
  · exact block_21
  · exact block_22
  · exact block_23
  · exact block_24
  · exact block_25
  · exact block_26
  · exact block_27
  · exact block_28
  · exact block_29
  · exact block_30
  · exact block_31
  · exact block_32
  · exact block_33
  · exact block_34
  · exact block_35
  · exact block_36
  · exact block_37
  · exact block_38
  · exact block_39
  · exact block_40
  · exact block_41
  · exact block_42
  · exact block_43
  · exact block_44
  · exact block_45
  · exact block_46
  · exact block_47
  · exact block_48
  · exact block_49
  · exact block_50
  · exact block_51
  · exact block_52

theorem normalized_cover : NormalizedFiveCover 107 :=
  normalized_of_checks 107 (by decide) masks pairs targets exceptions
    masks_ok pairs_ok targets_ok exceptions_ok rows_ok

/-- The finite certificate applies to every tight integer tuple. -/
theorem tight_cover (v : Fin 5 → ℤ) (hl : loneliness v=(1:ℝ)/6) :
    (∃ i, (107:ℤ) ∣ v i) ∨ ∀ j, (107:ℤ) ∣ tightFiveMoment v j := by
  by_cases hv : ∃ i, (107:ℤ) ∣ v i
  · exact Or.inl hv
  · exact Or.inr (moment_cover_of_normalized 107 (by decide) normalized_cover
      v hl (by simpa using hv))

end LonelyRunner.ModularPairCover.Prime107
