import LonelyRunner.TightFiveModular83
import LonelyRunner.TightFiveModular101
import LonelyRunner.TightFiveModular103
import LonelyRunner.TightFiveModular107
import LonelyRunner.TightFiveModular131
import LonelyRunner.TightFiveModular149
import LonelyRunner.TightFiveModular151
import LonelyRunner.TightFiveModular163
import LonelyRunner.TightFiveModular167
import LonelyRunner.TightFiveModular173
import LonelyRunner.TightFiveModular179
import LonelyRunner.TightFiveModular191
import LonelyRunner.TightFiveModular193
import LonelyRunner.TightFiveModular197
import LonelyRunner.TightFiveModular199
import LonelyRunner.TightFiveModular211
import LonelyRunner.TightFiveModular223
import LonelyRunner.TightFiveModular227
import LonelyRunner.TightFiveModular229
import LonelyRunner.TightFiveModular233
import LonelyRunner.TightFiveModular239
import LonelyRunner.TightFiveModular241
import LonelyRunner.TightFiveModular251
import LonelyRunner.TightFiveModular257
import LonelyRunner.TightFiveModular263
import LonelyRunner.TightFiveModular269
import LonelyRunner.TightFiveModular271
import LonelyRunner.TightFiveModular277
import LonelyRunner.TightFiveModular281
import LonelyRunner.TightFiveModular283
import LonelyRunner.TightFiveModular293
import LonelyRunner.TightFiveModular307
import LonelyRunner.TightFiveModular311
import LonelyRunner.TightFiveModular313
import LonelyRunner.TightFiveModular317
import LonelyRunner.TightFiveModular331
import LonelyRunner.TightFiveModular337
import LonelyRunner.TightFiveModular347
import LonelyRunner.TightFiveModular349
import LonelyRunner.TightFiveModular353

-- Generated by scripts/generate_tight_five_lean.py.

namespace LonelyRunner

/-- The complete finite modular input, checked in the Lean kernel. -/
theorem tightFivePrimes_normalized_cover :
    ∀ p ∈ tightFivePrimes, NormalizedFiveCover p := by
  intro p hp
  simp only [tightFivePrimes, Finset.mem_insert, Finset.mem_singleton] at hp
  rcases hp with rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl|rfl
  · exact ModularPairCover.Prime83.normalized_cover
  · exact ModularPairCover.Prime101.normalized_cover
  · exact ModularPairCover.Prime103.normalized_cover
  · exact ModularPairCover.Prime107.normalized_cover
  · exact ModularPairCover.Prime131.normalized_cover
  · exact ModularPairCover.Prime149.normalized_cover
  · exact ModularPairCover.Prime151.normalized_cover
  · exact ModularPairCover.Prime163.normalized_cover
  · exact ModularPairCover.Prime167.normalized_cover
  · exact ModularPairCover.Prime173.normalized_cover
  · exact ModularPairCover.Prime179.normalized_cover
  · exact ModularPairCover.Prime191.normalized_cover
  · exact ModularPairCover.Prime193.normalized_cover
  · exact ModularPairCover.Prime197.normalized_cover
  · exact ModularPairCover.Prime199.normalized_cover
  · exact ModularPairCover.Prime211.normalized_cover
  · exact ModularPairCover.Prime223.normalized_cover
  · exact ModularPairCover.Prime227.normalized_cover
  · exact ModularPairCover.Prime229.normalized_cover
  · exact ModularPairCover.Prime233.normalized_cover
  · exact ModularPairCover.Prime239.normalized_cover
  · exact ModularPairCover.Prime241.normalized_cover
  · exact ModularPairCover.Prime251.normalized_cover
  · exact ModularPairCover.Prime257.normalized_cover
  · exact ModularPairCover.Prime263.normalized_cover
  · exact ModularPairCover.Prime269.normalized_cover
  · exact ModularPairCover.Prime271.normalized_cover
  · exact ModularPairCover.Prime277.normalized_cover
  · exact ModularPairCover.Prime281.normalized_cover
  · exact ModularPairCover.Prime283.normalized_cover
  · exact ModularPairCover.Prime293.normalized_cover
  · exact ModularPairCover.Prime307.normalized_cover
  · exact ModularPairCover.Prime311.normalized_cover
  · exact ModularPairCover.Prime313.normalized_cover
  · exact ModularPairCover.Prime317.normalized_cover
  · exact ModularPairCover.Prime331.normalized_cover
  · exact ModularPairCover.Prime337.normalized_cover
  · exact ModularPairCover.Prime347.normalized_cover
  · exact ModularPairCover.Prime349.normalized_cover
  · exact ModularPairCover.Prime353.normalized_cover

/-- The known tight-five classification, with no unproved classification
or modular-cover hypothesis. Signs and coordinate orders are unrestricted. -/
theorem tight_five_classification : TightFiveClassification :=
  tight_five_classification_of_normalized_covers tightFivePrimes_normalized_cover

end LonelyRunner
