import LonelyRunner.ModularPairCover

-- Generated by scripts/generate_tight_five_lean.py.
-- All arithmetic certificates use ordinary kernel reduction.
set_option maxHeartbeats 0
set_option maxRecDepth 1000000

namespace LonelyRunner.ModularPairCover.Prime101

def masks (a : ℕ) : ℕ :=
  if a<25 then
    if a<12 then
      if a<6 then
        if a<3 then
          if a<1 then
            0x0
          else
            if a<2 then
              0x7fffffffe0000
            else
              0x7fffffffe00
        else
          if a<4 then
            0x7ff001fffffc0
          else
            if a<5 then
              0x7fffc03fffe0
            else
              0x7f03fff01fff0
      else
        if a<9 then
          if a<7 then
            0xffe07ff07ff8
          else
            if a<8 then
              0x7c1ff07fe1ff8
            else
              0x1ff0ff0ff87f8
        else
          if a<10 then
            0x78ff0fe1fc3fc
          else
            if a<11 then
              0x1f87f1fc7f1fc
            else
              0x71f8fc7f1f8fc
    else
      if a<18 then
        if a<15 then
          if a<13 then
            0x3f1f1f8f8fcfc
          else
            if a<14 then
              0x73e3e3e7e7c7c
            else
              0x3e7c78f9f3e7c
        else
          if a<16 then
            0x67cf9e3cf9f3c
          else
            if a<17 then
              0x3cf9e79f3cf3c
            else
              0x679e79e79e79e
      else
        if a<21 then
          if a<19 then
            0x3ce79ef3ce79e
          else
            if a<20 then
              0x6739ef39ef39e
            else
              0x39ce739cf7bde
        else
          if a<23 then
            if a<22 then
              0x6e739dee739de
            else
              0x3b9cee773bdce
          else
            if a<24 then
              0x4ee7773b9ddce
            else
              0x3bbb99dddccee
  else
    if a<38 then
      if a<31 then
        if a<28 then
          if a<26 then
            0x4ccceeeeeeeee
          else
            if a<27 then
              0x3377777666eee
            else
              0x5dd9bbb37766e
        else
          if a<29 then
            0x376ecddbb376e
          else
            if a<30 then
              0x5dbb76eddb366
            else
              0x36edbb6ed9b76
      else
        if a<34 then
          if a<32 then
            0x5bb6ddb6edb36
          else
            if a<33 then
              0x36db6edb6ddb6
            else
              0x5b6db6edb6db6
        else
          if a<36 then
            if a<35 then
              0x6db6db6db6db6
            else
              0x5b6f6db6dadb6
          else
            if a<37 then
              0x6db7b6dadb6b6
            else
              0x5adbdb5b6b6f6
    else
      if a<44 then
        if a<41 then
          if a<39 then
            0x6deded6d6d6d6
          else
            if a<40 then
              0x56f6b7b5bdad6
            else
              0x6f6b5ad6b5bde
        else
          if a<42 then
            0x56bdef5ad6b5e
          else
            if a<43 then
              0x6b5eb5eb5eb5e
            else
              0x55af5ebd7af5a
      else
        if a<47 then
          if a<45 then
            0x6bd5ebd5abd7a
          else
            if a<46 then
              0x757abd5eaf57a
            else
              0x6abd57aafd5fa
        else
          if a<49 then
            if a<48 then
              0x7557eabf557ea
            else
              0x7aaabfd557faa
          else
            if a<50 then
              0x7f555557ffaaa
            else
              0x7fffeaaaaaaaa

def spread (m : ℕ) : ℕ :=
  let x0 := (m ||| (m <<< 1600)) &&& 0xffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffffffff
  let x1 := (x0 ||| (x0 <<< 800)) &&& 0xffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ffff
  let x2 := (x1 ||| (x1 <<< 400)) &&& 0xff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ff
  let x3 := (x2 ||| (x2 <<< 200)) &&& 0xf00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f00000000000000000000000000000000000000000000000000f
  let x4 := (x3 ||| (x3 <<< 100)) &&& 0xc00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c00000000000000000000000030000000000000000000000000c0000000000000000000000003
  let x5 := (x4 ||| (x4 <<< 50)) &&& 0x40000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001000000000000200000000000040000000000008000000000001
  x5

def pairs (a : ℕ) : ℕ := masks a * spread (masks a)

def targets (c : ℕ) : ℕ :=
  (2^51-2^c)*2^(51*c)*((2^(51*(51-c))-1)/(2^51-1))

def exceptions : List Exception := [
  ⟨2, 3, 4, 5⟩,
  ⟨2, 3, 5, 4⟩,
  ⟨2, 48, 49, 50⟩,
  ⟨2, 48, 50, 49⟩,
  ⟨3, 4, 5, 9⟩,
  ⟨3, 4, 9, 5⟩,
  ⟨3, 32, 34, 35⟩,
  ⟨3, 32, 35, 34⟩,
  ⟨20, 21, 22, 41⟩,
  ⟨20, 21, 41, 22⟩,
  ⟨20, 21, 40, 41⟩,
  ⟨20, 21, 41, 40⟩,
  ⟨22, 23, 34, 45⟩,
  ⟨22, 23, 45, 34⟩,
  ⟨23, 24, 25, 26⟩,
  ⟨23, 24, 26, 25⟩,
  ⟨24, 25, 26, 50⟩,
  ⟨24, 25, 50, 26⟩,
  ⟨32, 33, 34, 35⟩,
  ⟨32, 33, 35, 34⟩]

theorem masks_ok : masksCheck 101 51 masks=true := by decide +kernel

theorem pairs_ok : pairsCheck 51 masks pairs=true := by decide +kernel

theorem targets_ok : targetsCheck 51 targets=true := by decide +kernel

theorem exceptions_ok : exceptionsCheck 101 51 exceptions=true := by decide +kernel

theorem block_0 : blockCheck 51 masks pairs targets exceptions 1 1=true := by decide +kernel

theorem block_1 : blockCheck 51 masks pairs targets exceptions 2 1=true := by decide +kernel

theorem block_2 : blockCheck 51 masks pairs targets exceptions 3 1=true := by decide +kernel

theorem block_3 : blockCheck 51 masks pairs targets exceptions 4 1=true := by decide +kernel

theorem block_4 : blockCheck 51 masks pairs targets exceptions 5 1=true := by decide +kernel

theorem block_5 : blockCheck 51 masks pairs targets exceptions 6 1=true := by decide +kernel

theorem block_6 : blockCheck 51 masks pairs targets exceptions 7 1=true := by decide +kernel

theorem block_7 : blockCheck 51 masks pairs targets exceptions 8 1=true := by decide +kernel

theorem block_8 : blockCheck 51 masks pairs targets exceptions 9 1=true := by decide +kernel

theorem block_9 : blockCheck 51 masks pairs targets exceptions 10 1=true := by decide +kernel

theorem block_10 : blockCheck 51 masks pairs targets exceptions 11 1=true := by decide +kernel

theorem block_11 : blockCheck 51 masks pairs targets exceptions 12 1=true := by decide +kernel

theorem block_12 : blockCheck 51 masks pairs targets exceptions 13 1=true := by decide +kernel

theorem block_13 : blockCheck 51 masks pairs targets exceptions 14 1=true := by decide +kernel

theorem block_14 : blockCheck 51 masks pairs targets exceptions 15 1=true := by decide +kernel

theorem block_15 : blockCheck 51 masks pairs targets exceptions 16 1=true := by decide +kernel

theorem block_16 : blockCheck 51 masks pairs targets exceptions 17 1=true := by decide +kernel

theorem block_17 : blockCheck 51 masks pairs targets exceptions 18 1=true := by decide +kernel

theorem block_18 : blockCheck 51 masks pairs targets exceptions 19 1=true := by decide +kernel

theorem block_19 : blockCheck 51 masks pairs targets exceptions 20 1=true := by decide +kernel

theorem block_20 : blockCheck 51 masks pairs targets exceptions 21 1=true := by decide +kernel

theorem block_21 : blockCheck 51 masks pairs targets exceptions 22 1=true := by decide +kernel

theorem block_22 : blockCheck 51 masks pairs targets exceptions 23 1=true := by decide +kernel

theorem block_23 : blockCheck 51 masks pairs targets exceptions 24 1=true := by decide +kernel

theorem block_24 : blockCheck 51 masks pairs targets exceptions 25 1=true := by decide +kernel

theorem block_25 : blockCheck 51 masks pairs targets exceptions 26 1=true := by decide +kernel

theorem block_26 : blockCheck 51 masks pairs targets exceptions 27 1=true := by decide +kernel

theorem block_27 : blockCheck 51 masks pairs targets exceptions 28 1=true := by decide +kernel

theorem block_28 : blockCheck 51 masks pairs targets exceptions 29 1=true := by decide +kernel

theorem block_29 : blockCheck 51 masks pairs targets exceptions 30 1=true := by decide +kernel

theorem block_30 : blockCheck 51 masks pairs targets exceptions 31 1=true := by decide +kernel

theorem block_31 : blockCheck 51 masks pairs targets exceptions 32 1=true := by decide +kernel

theorem block_32 : blockCheck 51 masks pairs targets exceptions 33 1=true := by decide +kernel

theorem block_33 : blockCheck 51 masks pairs targets exceptions 34 1=true := by decide +kernel

theorem block_34 : blockCheck 51 masks pairs targets exceptions 35 1=true := by decide +kernel

theorem block_35 : blockCheck 51 masks pairs targets exceptions 36 1=true := by decide +kernel

theorem block_36 : blockCheck 51 masks pairs targets exceptions 37 1=true := by decide +kernel

theorem block_37 : blockCheck 51 masks pairs targets exceptions 38 1=true := by decide +kernel

theorem block_38 : blockCheck 51 masks pairs targets exceptions 39 1=true := by decide +kernel

theorem block_39 : blockCheck 51 masks pairs targets exceptions 40 1=true := by decide +kernel

theorem block_40 : blockCheck 51 masks pairs targets exceptions 41 1=true := by decide +kernel

theorem block_41 : blockCheck 51 masks pairs targets exceptions 42 1=true := by decide +kernel

theorem block_42 : blockCheck 51 masks pairs targets exceptions 43 1=true := by decide +kernel

theorem block_43 : blockCheck 51 masks pairs targets exceptions 44 1=true := by decide +kernel

theorem block_44 : blockCheck 51 masks pairs targets exceptions 45 1=true := by decide +kernel

theorem block_45 : blockCheck 51 masks pairs targets exceptions 46 1=true := by decide +kernel

theorem block_46 : blockCheck 51 masks pairs targets exceptions 47 1=true := by decide +kernel

theorem block_47 : blockCheck 51 masks pairs targets exceptions 48 1=true := by decide +kernel

theorem block_48 : blockCheck 51 masks pairs targets exceptions 49 1=true := by decide +kernel

theorem block_49 : blockCheck 51 masks pairs targets exceptions 50 1=true := by decide +kernel

theorem rows_ok : rowsCheck 51 masks pairs targets exceptions=true := by
  apply rowsCheck_of_blocks 51 masks pairs targets exceptions 1 50 (by decide) (by decide)
  intro q hq
  interval_cases q
  · exact block_0
  · exact block_1
  · exact block_2
  · exact block_3
  · exact block_4
  · exact block_5
  · exact block_6
  · exact block_7
  · exact block_8
  · exact block_9
  · exact block_10
  · exact block_11
  · exact block_12
  · exact block_13
  · exact block_14
  · exact block_15
  · exact block_16
  · exact block_17
  · exact block_18
  · exact block_19
  · exact block_20
  · exact block_21
  · exact block_22
  · exact block_23
  · exact block_24
  · exact block_25
  · exact block_26
  · exact block_27
  · exact block_28
  · exact block_29
  · exact block_30
  · exact block_31
  · exact block_32
  · exact block_33
  · exact block_34
  · exact block_35
  · exact block_36
  · exact block_37
  · exact block_38
  · exact block_39
  · exact block_40
  · exact block_41
  · exact block_42
  · exact block_43
  · exact block_44
  · exact block_45
  · exact block_46
  · exact block_47
  · exact block_48
  · exact block_49

theorem normalized_cover : NormalizedFiveCover 101 :=
  normalized_of_checks 101 (by decide) masks pairs targets exceptions
    masks_ok pairs_ok targets_ok exceptions_ok rows_ok

/-- The finite certificate applies to every tight integer tuple. -/
theorem tight_cover (v : Fin 5 → ℤ) (hl : loneliness v=(1:ℝ)/6) :
    (∃ i, (101:ℤ) ∣ v i) ∨ ∀ j, (101:ℤ) ∣ tightFiveMoment v j := by
  by_cases hv : ∃ i, (101:ℤ) ∣ v i
  · exact Or.inl hv
  · exact Or.inr (moment_cover_of_normalized 101 (by decide) normalized_cover
      v hl (by simpa using hv))

end LonelyRunner.ModularPairCover.Prime101
