import LonelyRunner.Torus

namespace LonelyRunner

/-- Loneliness on the entire real plane generated by two integer columns,
viewed modulo the integer lattice. No chosen one-dimensional direction is built in. -/
noncomputable def planeLoneliness {n : ℕ} [NeZero n] (v z : Fin n → ℤ) : ℝ :=
  sSup (Set.range fun p : ℝ × ℝ => Finset.univ.inf' Finset.univ_nonempty
    (fun i => intDist (p.1*v i+p.2*z i)))

noncomputable def speedNorm {n : ℕ} (v : Fin n → ℤ) : ℝ :=
  Real.sqrt (∑ i, (v i : ℝ)^2)

/-- The area of the displayed integer parallelogram. This definition does not
assert that the two columns generate the saturated integer lattice of their plane. -/
noncomputable def planeHeight {n : ℕ} (v z : Fin n → ℤ) : ℝ :=
  Real.sqrt ((∑ i, (v i : ℝ)^2)*(∑ i, (z i : ℝ)^2)-
    (∑ i, (v i : ℝ)*(z i : ℝ))^2)

noncomputable def projectionCoefficient {n : ℕ} (v z : Fin n → ℤ) : ℝ :=
  (∑ i, (v i : ℝ)*(z i : ℝ))/(∑ i, (v i : ℝ)^2)

noncomputable def perpendicularCoordinate {n : ℕ} (v z : Fin n → ℤ) (i : Fin n) : ℝ :=
  z i-projectionCoefficient v z*v i

noncomputable def projectionNorm {n : ℕ} (v z : Fin n → ℤ) : ℝ :=
  Real.sqrt (∑ i, perpendicularCoordinate v z i^2)

/-- Distance to the integers changes by at most the displacement on the real line. -/
theorem intDist_le_intDist_add_abs (x y : ℝ) : intDist x ≤ intDist y+|x-y| := by
  have he : intDist y = |y-(round y : ℝ)| := by simp [intDist, AddCircle.norm_eq]
  calc
    intDist x ≤ |x-(round y : ℝ)| := intDist_le_abs_sub x (round y)
    _ = |(x-y)+(y-(round y : ℝ))| := by congr 1; ring
    _ ≤ |x-y|+|y-(round y : ℝ)| := abs_add_le _ _
    _ = _ := by rw [he]; ring

theorem abs_perpendicularCoordinate_le {n : ℕ} (v z : Fin n → ℤ) (i : Fin n) :
    |perpendicularCoordinate v z i| ≤ projectionNorm v z := by
  have hs : 0 ≤ ∑ j, perpendicularCoordinate v z j^2 := Finset.sum_nonneg (fun j _ => sq_nonneg _)
  have ht := Finset.single_le_sum (f := fun j => perpendicularCoordinate v z j^2)
    (fun j _ => sq_nonneg _) (Finset.mem_univ i)
  have he := Real.sq_sqrt hs
  have hn := Real.sqrt_nonneg (∑ j, perpendicularCoordinate v z j^2)
  unfold projectionNorm
  nlinarith [sq_abs (perpendicularCoordinate v z i)]

/-- Rounding the transverse coefficient, then absorbing its parallel part,
gives one real orbit time approximating every coordinate of any plane point. -/
theorem plane_point_orbit_approximation {n : ℕ} (v z : Fin n → ℤ) (x y : ℝ) :
    ∃ t : ℝ, ∀ i, intDist (x*v i+y*z i) ≤ intDist (t*v i)+projectionNorm v z/2 := by
  let u : ℝ := y-(round y : ℝ)
  let t : ℝ := x+u*projectionCoefficient v z
  refine ⟨t, fun i => ?_⟩
  have he : x*v i+y*z i = t*v i+u*perpendicularCoordinate v z i+
      ((round y*z i : ℤ) : ℝ) := by
    dsimp [t, u, perpendicularCoordinate]
    push_cast
    ring
  rw [he, intDist_add_int]
  have hh := intDist_le_intDist_add_abs (t*v i+u*perpendicularCoordinate v z i) (t*v i)
  have hround : |u| ≤ (1:ℝ)/2 := abs_sub_round y
  have hb := mul_le_mul hround (abs_perpendicularCoordinate_le v z i)
    (abs_nonneg _) (by norm_num : (0:ℝ) ≤ 1/2)
  rw [← abs_mul] at hb
  have ha : |t*(v i : ℝ)+u*perpendicularCoordinate v z i-t*v i| =
      |u*perpendicularCoordinate v z i| := by congr 1; ring
  rw [ha] at hh
  linarith

/-- The density estimate for a containing integer plane, proved over all real points. -/
theorem planeLoneliness_le_add_projectionNorm {n : ℕ} [NeZero n] (v z : Fin n → ℤ) :
    planeLoneliness v z ≤ loneliness v+projectionNorm v z/2 := by
  apply csSup_le (Set.range_nonempty _)
  rintro _ ⟨⟨x,y⟩, rfl⟩
  let L := Finset.univ.inf' Finset.univ_nonempty (fun i => intDist (x*v i+y*z i))
  obtain ⟨t, ht⟩ := plane_point_orbit_approximation v z x y
  have hl : L-projectionNorm v z/2 ≤ loneliness v := by
    apply le_loneliness_of_time _ _ t
    intro i
    have hi : L ≤ intDist (x*v i+y*z i) := Finset.inf'_le _ (Finset.mem_univ i)
    linarith [ht i]
  change L ≤ _
  linarith

theorem speedNorm_pos {n : ℕ} (v : Fin n → ℤ) (hv : v ≠ 0) : 0 < speedNorm v := by
  apply Real.sqrt_pos.mpr
  apply Finset.sum_pos'
  · exact fun i _ => sq_nonneg _
  · have he : ∃ i, v i ≠ 0 := by
      by_contra hn
      push Not at hn
      exact hv (funext hn)
    obtain ⟨i, hi⟩ := he
    refine ⟨i, Finset.mem_univ i, sq_pos_of_ne_zero ?_⟩
    exact_mod_cast hi

theorem projectionNorm_sq {n : ℕ} (v z : Fin n → ℤ) :
    projectionNorm v z^2 = (∑ i, (z i : ℝ)^2) -
      2*projectionCoefficient v z*(∑ i, (v i : ℝ)*(z i : ℝ))+
      projectionCoefficient v z^2*(∑ i, (v i : ℝ)^2) := by
  rw [projectionNorm, Real.sq_sqrt (Finset.sum_nonneg (fun i _ => sq_nonneg _))]
  simp only [perpendicularCoordinate, sub_sq, mul_pow, Finset.sum_add_distrib, Finset.sum_sub_distrib,
    ← Finset.mul_sum]
  congr 2
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro i _
  ring

theorem planeHeight_eq_speedNorm_mul_projectionNorm {n : ℕ} (v z : Fin n → ℤ) (hv : v ≠ 0) :
    planeHeight v z = speedNorm v*projectionNorm v z := by
  have hS : 0 < ∑ i, (v i : ℝ)^2 := Real.sqrt_pos.mp (speedNorm_pos v hv)
  have he : (∑ i, (v i : ℝ)^2)*projectionNorm v z^2 =
      (∑ i, (v i : ℝ)^2)*(∑ i, (z i : ℝ)^2)-(∑ i, (v i : ℝ)*(z i : ℝ))^2 := by
    rw [projectionNorm_sq]
    unfold projectionCoefficient
    field_simp
    ring
  unfold planeHeight speedNorm
  have hp : 0 ≤ projectionNorm v z := Real.sqrt_nonneg _
  rw [← he, Real.sqrt_mul hS.le, Real.sqrt_sq hp]

/-- The projection-height density estimate used in the effective-bound proof.
The area and norm are defined from the integer columns; the estimate is not a hypothesis. -/
theorem planeLoneliness_le_add_height {n : ℕ} [NeZero n] (v z : Fin n → ℤ) (hv : v ≠ 0) :
    planeLoneliness v z ≤ loneliness v+planeHeight v z/(2*speedNorm v) := by
  rw [planeHeight_eq_speedNorm_mul_projectionNorm v z hv]
  have he : speedNorm v*projectionNorm v z/(2*speedNorm v) = projectionNorm v z/2 := by
    field_simp [(speedNorm_pos v hv).ne']
  rw [he]
  exact planeLoneliness_le_add_projectionNorm v z

/-- A good point of the whole plane supplies a lower bound on its loneliness. -/
theorem le_planeLoneliness_of_point {n : ℕ} [NeZero n] (v z : Fin n → ℤ)
    (x y L : ℝ) (h : ∀ i, L ≤ intDist (x*v i+y*z i)) : L ≤ planeLoneliness v z := by
  have hb : BddAbove (Set.range fun p : ℝ × ℝ => Finset.univ.inf' Finset.univ_nonempty
      (fun i => intDist (p.1*v i+p.2*z i))) := by
    refine ⟨1/2, ?_⟩
    rintro _ ⟨p, rfl⟩
    exact (Finset.inf'_le _ (Finset.mem_univ (0 : Fin n))).trans (intDist_le_half _)
  exact (Finset.le_inf' Finset.univ_nonempty _ (fun i _ => h i)).trans (le_csSup hb ⟨(x,y), rfl⟩)

/-- The original orbit is contained in its displayed integer plane. -/
theorem loneliness_le_planeLoneliness {n : ℕ} [NeZero n] (v z : Fin n → ℤ) :
    loneliness v ≤ planeLoneliness v z := by
  obtain ⟨t, _, ht⟩ := exists_maximizing_time v
  exact le_planeLoneliness_of_point v z t 0 _ (by simpa using ht)

theorem intDist_plane_fract {n : ℕ} (v z : Fin n → ℤ) (x y : ℝ) (i : Fin n) :
    intDist (Int.fract x*v i+Int.fract y*z i) = intDist (x*v i+y*z i) := by
  have he : Int.fract x*(v i : ℝ)+Int.fract y*z i =
      x*v i+y*z i-((⌊x⌋*v i+⌊y⌋*z i : ℤ) : ℝ) := by
    unfold Int.fract
    push_cast
    ring
  rw [he, intDist_sub_int]

/-- The full-plane maximum is attained on the unit parameter square. -/
theorem exists_plane_maximizer {n : ℕ} [NeZero n] (v z : Fin n → ℤ) :
    ∃ x ∈ Set.Icc (0:ℝ) 1, ∃ y ∈ Set.Icc (0:ℝ) 1,
      ∀ i, planeLoneliness v z ≤ intDist (x*v i+y*z i) := by
  let f : ℝ × ℝ → ℝ := fun p => Finset.univ.inf' Finset.univ_nonempty
    (fun i => intDist (p.1*v i+p.2*z i))
  have hf : Continuous f := by
    apply Continuous.finset_inf'_apply
    intro i _
    unfold intDist
    fun_prop
  have hc := (isCompact_Icc (a := (0:ℝ)) (b := 1)).prod
    (isCompact_Icc (a := (0:ℝ)) (b := 1))
  obtain ⟨p, hp, hmax⟩ := hc.exists_isMaxOn (f := f)
    ⟨(0,0), by norm_num⟩ hf.continuousOn
  have hu : planeLoneliness v z ≤ f p := by
    apply csSup_le (Set.range_nonempty _)
    rintro _ ⟨⟨x,y⟩, rfl⟩
    have hh := hmax (a := (Int.fract x, Int.fract y))
      ⟨⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩,
        ⟨Int.fract_nonneg _, (Int.fract_lt_one _).le⟩⟩
    change (Finset.univ.inf' Finset.univ_nonempty
      (fun i => intDist (Int.fract x*v i+Int.fract y*z i))) ≤ f p at hh
    simpa only [intDist_plane_fract] using hh
  exact ⟨p.1, hp.1, p.2, hp.2, fun i => hu.trans (Finset.inf'_le _ (Finset.mem_univ i))⟩

theorem planeLoneliness_nonneg {n : ℕ} [NeZero n] (v z : Fin n → ℤ) : 0 ≤ planeLoneliness v z :=
  le_planeLoneliness_of_point v z 0 0 0 (fun _i => intDist_nonneg _)

theorem planeLoneliness_le_half {n : ℕ} [NeZero n] (v z : Fin n → ℤ) : planeLoneliness v z ≤ 1/2 := by
  obtain ⟨x, _, y, _, h⟩ := exists_plane_maximizer v z
  exact (h 0).trans (intDist_le_half _)

end LonelyRunner
