"""Generate untrusted data for the proved six-speed modular search.

Generation is not verification. A prime cover is established only after its
aggregate Lean module builds. Root modules form one import chain to bound
simultaneous compilation and preserve reusable checks on individual roots.
"""
from argparse import ArgumentParser
from pathlib import Path

from generate_tight_five_lean import table

ROOT = Path(__file__).resolve().parents[1]
GENERATED_PRIMES = (179,)


def generate(p):
    w = p // 2 + 1
    fold = lambda n: min(n % p, -n % p)
    inv = [0] + [pow(x, -1, p) for x in range(1, w)]
    good = [sum(1 << t for t in range(w) if p < 6 * (x*t % p) < 5*p)
            for x in range(w)]
    roots = [r for r in range(2, w) if r <= fold(inv[r])]
    ns = f'LonelyRunner.SixModularSearch.Prime{p}'
    data_name = f'SixModular{p}Data'
    text = ('''import LonelyRunner.SixModularSearch

-- Generated untrusted data. Every claimed fact is checked by the ordinary Lean kernel.
set_option maxHeartbeats 0
set_option maxRecDepth 1000000
''' + f'namespace {ns}\n')
    text += table('inv', inv) + table('good', good)
    text += f'''theorem inv_ok : inverseCheck {p} {w} inv=true := by decide +kernel

theorem good_ok : ModularPairCover.masksCheck {p} {w} good=true := by decide +kernel

theorem transpose_ok : transposeCheck {w} good=true := by decide +kernel

def pivot := ModularSearch.bestPivot {w} good

end {ns}
'''
    files = {data_name: text}
    previous = None
    for r in roots:
        masks = [sum(1 << y for y in range(1, w)
                     if x != y and r <= fold(x*inv[y]) and r <= fold(y*inv[x]))
                 for x in range(w)]
        name = f'SixModular{p}Root{r}'
        text = (f'import LonelyRunner.{data_name}\n'
                'import LonelyRunner.SparseModularSearch\n')
        if previous is not None:
            text += f'import LonelyRunner.{previous}\n'
        text += f'''
-- Generated untrusted data. All checks use ordinary kernel reduction.
set_option maxHeartbeats 0
set_option maxRecDepth 1000000
namespace {ns}.Root{r}
'''
        text += table('pairs', masks)
        text += f'''theorem pairs_ok : pairCheck {p} {w} {r} inv pairs=true := by decide +kernel

theorem search_ok : ModularSearch.rootCheck {w} {r} good pairs (triples {p} {w}) pivot=true := by
  rw [← ModularSearch.fastRootCheck_eq]
  decide +kernel

end {ns}.Root{r}
'''
        files[name] = text
        previous = name
    text = f'''import LonelyRunner.{previous}

-- Generated by scripts/generate_six_modular_lean.py.
namespace {ns}

def pairs (r x : ℕ) : ℕ :=
  match r with
'''
    text += ''.join(f'  | {r} => Root{r}.pairs x\n' for r in roots)
    text += '  | _ => 0\n\n'
    text += f'''theorem sorted_cover : SortedSixCover {p} := by
  apply sorted_cover_of_checks {p} (by norm_num) inv good pairs pivot
    inv_ok good_ok transpose_ok
'''
    for kind in ('pairs', 'search'):
        text += '  · intro r hr2 hrw hrmin\n    interval_cases r\n'
        for r in range(2, w):
            if r not in roots:
                text += '    · norm_num [folded,inv] at hrmin\n'
            elif kind == 'pairs':
                text += (f'    · change pairCheck {p} {w} {r} inv Root{r}.pairs=true\n'
                         f'      exact Root{r}.pairs_ok\n')
            else:
                text += (f'    · change ModularSearch.rootCheck {w} {r} good Root{r}.pairs '
                         f'(triples {p} {w}) pivot=true\n'
                         f'      exact Root{r}.search_ok\n')
    text += f'''
theorem cover : SixModularCover {p} :=
  sixModularCover_of_normalized {p} (by norm_num)
    (normalizedSixCover_of_sorted {p} (by norm_num) sorted_cover)

end {ns}
'''
    files[f'SixModular{p}'] = text
    return files


def main():
    parser = ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    count = 0
    for p in GENERATED_PRIMES:
        for name, source in generate(p).items():
            path = ROOT / 'LonelyRunner' / (name + '.lean')
            if args.check:
                if not path.exists() or path.read_text() != source:
                    raise RuntimeError(f'Generated source differs: {path}')
            else:
                if not path.exists() or path.read_text() != source:
                    path.write_text(source)
            count += 1
    print(f'{"Checked" if args.check else "Generated"} {count} six-speed Lean modules; '
          'kernel compilation is required for every cover.')


if __name__ == '__main__':
    main()
