"""Replay and render the exact six-speed tail-product certificate.

The 85 nonnegative products were discovered by an exploratory linear program.
This script uses only rational arithmetic and the checked-in literals. Lean
independently proves nonnegativity and the complete polynomial identity.
"""
import json
from fractions import Fraction
from pathlib import Path
import argparse

root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check',action='store_true')
args=parser.parse_args()
data=json.loads((root/'certificates/six-tail-product.json').read_text())
if data['schema']!='cl-lean-six-tail-product-v1':
    raise RuntimeError('Unexpected certificate schema')
cert=data['terms']

# Sparse rational polynomial replay, independent of Lean and the exploratory LP.
zero=(0,0,0,0,0)
def plus(p,q):
    r=p.copy()
    for m,c in q.items():
        r[m]=r.get(m,Fraction(0))+c
        if not r[m]:del r[m]
    return r
def times(p,q):
    r={}
    for m,c in p.items():
        for n,d in q.items():
            key=tuple(a+b for a,b in zip(m,n))
            r[key]=r.get(key,Fraction(0))+c*d
    return {m:c for m,c in r.items() if c}
def linear(cs,c=0):
    r={zero:Fraction(c)} if c else {}
    for i,a in enumerate(cs):
        if a:r[tuple(int(j==i) for j in range(5))]=Fraction(a)
    return r
gpoly=[linear([1,0,0,0,-1]),
    linear(['4/25','21/25',0,0,'-4/25'],'-21/25'),
    linear(['1/25','21/100','3/4',0,'-1/25'],'-24/25'),
    linear(['1/100','21/400','3/16','3/4','-1/100'],'-99/100'),
    linear(['-1/7',1,0,0,0]),linear([0,'-21/100',1,0,0]),
    linear([0,0,'-3/16',1,0]),linear([0,0,0,0,1],'-1/2'),
    linear([0,0,0,0,-1],1)]
target={(1,1,1,1,0):Fraction(1),(0,0,0,0,1):Fraction(-1)}
def replay(items):
    total={}
    for item in items:
        coefficient=Fraction(item['coefficient'])
        factors=item['factors']
        if coefficient<=0 or not (1<=len(factors)<=4):
            raise RuntimeError('Invalid nonnegative-product term')
        p={zero:coefficient}
        for i in factors:
            if not isinstance(i,int) or not 0<=i<9:
                raise RuntimeError('Invalid factor index')
            p=times(p,gpoly[i])
        total=plus(total,p)
    return total
if replay(cert)!=target:
    raise RuntimeError('Certificate polynomial identity is false')
mutated=[dict(x) for x in cert]
mutated[0]['coefficient']=str(Fraction(mutated[0]['coefficient'])+1)
if replay(mutated)==target:
    raise RuntimeError('Mutated-coefficient negative control was accepted')

lines=['-- Generated by scripts/generate_tail_product_lean.py; do not edit.', 'import Mathlib.Tactic','', 'namespace LonelyRunner','',
'set_option maxHeartbeats 1600000','set_option maxRecDepth 4096','',
'/-- Exact nonnegative-product certificate for the normalized four-variable',
'product estimate used in the six-speed bound. -/',
'theorem four_tail_product_certificate (u₁ u₂ u₃ u₄ t : ℝ)',
'    (h₀ : t ≤ u₁) (h₁ : 4*t+21 ≤ 4*u₁+21*u₂)',
'    (h₂ : 4*t+96 ≤ 4*u₁+21*u₂+75*u₃)',
'    (h₃ : 4*t+396 ≤ 4*u₁+21*u₂+75*u₃+300*u₄)',
'    (h₄ : u₁ ≤ 7*u₂) (h₅ : 21*u₂ ≤ 100*u₃)',
'    (h₆ : 3*u₃ ≤ 16*u₄) (h₇ : 1/2 ≤ t) (h₈ : t ≤ 1) :',
'    t ≤ u₁*u₂*u₃*u₄ := by']
gs=['u₁-t','(4*u₁+21*u₂-4*t-21)/25',
'(4*u₁+21*u₂+75*u₃-4*t-96)/100',
'(4*u₁+21*u₂+75*u₃+300*u₄-4*t-396)/400',
'u₂-u₁/7','u₃-(21/100)*u₂','u₄-(3/16)*u₃','t-1/2','1-t']
for i,g in enumerate(gs):
 lines += [f'  let g{i} : ℝ := {g}',f'  have hg{i} : 0 ≤ g{i} := by dsimp [g{i}]; linarith']
terms=[]
for item in cert:
 v=Fraction(item['coefficient']);terms.append(f'({v.numerator}/{v.denominator})*'+'*'.join(f'g{i}' for i in item['factors']))
lines += ['  let p : ℝ :=']
lines += [('    ' if i==0 else '    + ')+v for i,v in enumerate(terms)]
lines += ['  have hpos : 0 ≤ p := by dsimp [p]; positivity',
'  have he : u₁*u₂*u₃*u₄-t = p := by',
'    dsimp [p,'+','.join(f'g{i}' for i in range(9))+']',
'    ring',
'  linarith','',
'/-- The small-first-length tail bound, with all linear hypotheses explicit. -/',
'theorem six_tail_product_bound (s a b c d : ℝ)',
'    (hs₀ : 0 ≤ s) (hs₁ : s ≤ 1/450)',
'    (h₂ : 1/225-s ≤ a) (h₃ : 1/36-s ≤ a+b)',
'    (h₄ : 1/9-s ≤ a+b+c) (h₅ : 4/9-s ≤ a+b+c+d)',
'    (hr₁ : 3*a ≤ 4*b) (hr₂ : 3*b ≤ 4*c) (hr₃ : 3*c ≤ 4*d) :',
'    (7/10800:ℝ)*(1/225-s) ≤ a*b*c*d := by',
'  have h := four_tail_product_certificate (225*a) ((300/7)*b) (12*c) (3*d) (1-225*s)',
'    (by linarith) (by linarith) (by linarith) (by linarith)',
'    (by linarith) (by linarith) (by linarith) (by linarith) (by linarith)',
'  nlinarith [h]','', 'end LonelyRunner','']
output='\n'.join(lines)
path=root/'LonelyRunner/TailProduct.lean'
if args.check:
    if path.read_text()!=output:
        raise RuntimeError('Generated Lean certificate differs from the exact literals')
else:
    path.write_text(output)
print(f'PASS: {len(cert)} exact nonnegative products, coefficient-mutation control, and Lean source')
