"""Regenerate the kernel-checked tight-five modular certificates.

Each generated module proves NormalizedFiveCover for one prime through the
proved checker in ModularPairCover. Python generates untrusted data only.
FORMAL_PRIMES records the completed formal scope, separately from the larger
external census. No external census is substituted for a Lean proof.
"""
from argparse import ArgumentParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FORMAL_PRIMES = (83,)
PROFILES = ((1, 2, 3, 4, 5), (1, 3, 4, 5, 9))


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def table(name, values):
    """A balanced lookup tree avoids logical list traversal during reduction."""
    def branch(lo, hi, indent):
        space = ' ' * indent
        if hi-lo == 1:
            return space + hex(values[lo])
        mid = (lo+hi)//2
        return (space + f'if a<{mid} then\n' + branch(lo, mid, indent+2) +
                '\n' + space + 'else\n' + branch(mid, hi, indent+2))
    return f'def {name} (a : ℕ) : ℕ :=\n' + branch(0, len(values), 2) + '\n\n'


def generate(p):
    w = p // 2 + 1
    masks = [sum(1 << t for t in range(w) if p < 6 * (t*a % p) < 5*p)
             for a in range(w)]
    profiles = sorted({tuple(sorted(min(a*pow(v, -1, p) % p,
                                        -a*pow(v, -1, p) % p) for a in profile))
                       for profile in PROFILES for v in profile})
    require(all(v[0] == 1 and len(set(v)) == 5 for v in profiles),
            f'Unexpected normalized profile at {p}')
    exceptions = []
    for _, b, c, d, e in profiles:
        exceptions.extend([(b, c, d, e), (b, c, e, d)])
    s = ('import LonelyRunner.ModularPairCover\n\n'
         '-- Generated by scripts/generate_tight_five_lean.py.\n'
         '-- All arithmetic certificates use ordinary kernel reduction.\n'
         'set_option maxHeartbeats 0\n'
         'set_option maxRecDepth 1000000\n\n')
    s += f'namespace LonelyRunner.ModularPairCover.Prime{p}\n\n'
    def tensor(m):
        return sum(m << (w*d) for d in range(w) if m >> d & 1)
    s += table('masks', masks)
    # Spread bit d into position w*d, using disjoint blocks. Lean checks every
    # resulting pair mask against tensor; this encoding is not a trusted lemma.
    stages = []
    for k in reversed(range((w-1).bit_length())):
        n = 1 << k
        groups = (w+n-1)//n
        bitmask = sum(((1 << n)-1) << (w*n*g) for g in range(groups))
        stages.append(((w-1)*n, bitmask))
    for m in masks:
        x = m
        for shift, bitmask in stages:
            x = (x | (x << shift)) & bitmask
        require(m*x == tensor(m), f'Pair encoding differs at {p}')
    s += 'def spread (m : ℕ) : ℕ :=\n'
    for i, (shift, bitmask) in enumerate(stages):
        previous = 'm' if i == 0 else f'x{i-1}'
        s += f'  let x{i} := ({previous} ||| ({previous} <<< {shift})) &&& {hex(bitmask)}\n'
    s += f'  x{len(stages)-1}\n\n'
    s += 'def pairs (a : ℕ) : ℕ := masks a * spread (masks a)\n\n'
    # Exact geometric sums encode the target rectangles. targets_ok verifies
    # every one against the simple recursive specification in Lean.
    s += (f'def targets (c : ℕ) : ℕ :=\n'
          f'  (2^{w}-2^c)*2^({w}*c)*((2^({w}*({w}-c))-1)/(2^{w}-1))\n\n')
    s += 'def exceptions : List Exception := [\n  ' + ',\n  '.join(
        '⟨' + ', '.join(map(str, r)) + '⟩' for r in exceptions) + ']\n\n'
    checks = [('masks_ok', f'masksCheck {p} {w} masks'),
              ('pairs_ok', f'pairsCheck {w} masks pairs'),
              ('targets_ok', f'targetsCheck {w} targets'),
              ('exceptions_ok', f'exceptionsCheck {p} {w} exceptions')]
    for name, prop in checks:
        s += f'theorem {name} : {prop}=true := by decide +kernel\n\n'
    block_size = 8
    block_count = (w-1+block_size-1)//block_size
    for q in range(block_count):
        s += (f'theorem block_{q} : blockCheck {w} masks pairs targets exceptions '
              f'{1+block_size*q} {block_size}=true := by decide +kernel\n\n')
    s += f'theorem rows_ok : rowsCheck {w} masks pairs targets exceptions=true := by\n'
    s += (f'  apply rowsCheck_of_blocks {w} masks pairs targets exceptions '
          f'{block_size} {block_count} (by decide) (by decide)\n'
          '  intro q hq\n  interval_cases q\n')
    for q in range(block_count):
        s += f'  · exact block_{q}\n'
    s += '\n'
    s += f'theorem normalized_cover : NormalizedFiveCover {p} :=\n'
    s += f'  normalized_of_checks {p} (by decide) masks pairs targets exceptions\n'
    s += '    masks_ok pairs_ok targets_ok exceptions_ok rows_ok\n\n'
    s += f'''/-- The finite certificate applies to every tight integer tuple. -/
theorem tight_cover (v : Fin 5 → ℤ) (hl : loneliness v=(1:ℝ)/6) :
    (∃ i, ({p}:ℤ) ∣ v i) ∨ ∀ j, ({p}:ℤ) ∣ tightFiveMoment v j := by
  by_cases hv : ∃ i, ({p}:ℤ) ∣ v i
  · exact Or.inl hv
  · exact Or.inr (moment_cover_of_normalized {p} (by decide) normalized_cover
      v hl (by simpa using hv))

'''
    if p == 83:
        s += ('-- A zero-time bit is invalid; deleting the exceptional profiles loses coverage.\n'
              'example : masksCheck 83 42 (fun a => if a=1 then masks a ||| 1 else masks a)=false := by\n'
              '  decide +kernel\n\n'
              'example : rowsCheck 42 masks pairs targets []=false := by decide +kernel\n\n'
              'example : pairsCheck 42 masks (fun _ => 2^(42*42)-1)=false := by decide +kernel\n\n'
              'example : targetsCheck 42 (fun _ => 0)=false := by decide +kernel\n\n'
              '-- This nontight profile fails at least one required moment congruence.\n'
              'example : exceptionsCheck 83 42 [⟨2,3,4,6⟩]=false := by decide +kernel\n\n')
    s += f'end LonelyRunner.ModularPairCover.Prime{p}\n'
    return s


def main():
    parser = ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    args = parser.parse_args()
    for p in FORMAL_PRIMES:
        path = ROOT / 'LonelyRunner' / f'TightFiveModular{p}.lean'
        generated = generate(p)
        if args.write:
            path.write_text(generated)
        else:
            require(path.read_text() == generated, f'Generated certificate differs: {path}')
    print(f'PASS: exact generated Lean sources for primes {FORMAL_PRIMES}')


if __name__ == '__main__':
    main()
